### ISSUE TITLE
Download Laravel Excel Not Working With Inertia

### ISSUE THREAD

**Issue by endrureza** [inertiajs/inertia-laravel#101]
I am trying to download excel file which i generate using maatwebsite/laravel-excel package and using inertia js, but everytime i download 

```html
<InertiaLink href="/transaction/export" :data="query" :class="{'btn btn-secondary btn-sm': true, 'disabled': _.isEmpty(details)}" preserve-state>Export to Excel</InertiaLink>
```

there will always be a pop up square windows displaying the file content rather than downloading the file. any idea how to fix this ?

**Comment by reinink** [comment]
Just make these regular links. They don't need to be Inertia links.

```html
<a href="/transaction/export?query..." :class="{'btn btn-secondary btn-sm': true, 'disabled': _.isEmpty(details)}">Export to Excel</a>
```

**Comment by mdabbas-cse** [comment]
i'm face this is problem. file download successfully, but its not store local system, it's store laravel storage directory,

**Comment by reinink** [comment]
@mdabbas-cse I am fairly confident that is not an issue related issue.

**Comment by mdabbas-cse** [comment]
ok, how can I fix this issue, any suggestions for me?

**Comment by fortiz-contactoit** [comment]
i recomend to use xlsx
`npm install xlsx`
