### ISSUE TITLE
Request::inertia() throws error in Laravel 7

### ISSUE THREAD

**Issue by gcw07** [inertiajs/inertia-laravel#106]
Using Request::inertia() macro is throwing an error in Laravel 7. Here is the error it is throwing:

ErrorException
Unbinding $this of closure is deprecated

**Comment by georgehanson** [comment]
I think this is an issue with PHP7.4 IIRC

**Comment by muarachmann** [comment]
Try checking your PHP version....

**Comment by reinink** [comment]
Yup, this doesn't appear to be an Inertia issue. See here: https://github.com/laravel/framework/issues/29411
