### ISSUE TITLE
Question: using Inertia in only part of a Laravel app

### ISSUE THREAD

**Issue by joevallender** [inertiajs/inertia-laravel#107]
Low priority question.

Is it possible to use Inertia in only part of Laravel app? Either on specific routes or route pattern? 

The use case is either using Inertia only for one part of an app (like an admin panel) or progressively adopting it into an existing larger app. 

From reading the documentation and looking at the sample app it appears to be all or nothing - is that correct? My apologies if I've missed something!

**Comment by joevallender** [comment]
Having just created a test app, I see that my desired behaviour happens automatically.

Looking at PingCRM I'd assumed that views/app.blade.php would supersede other views, however its invoked only for the Inertia responses. Which makes total sense. Nothing to see here :)

**Comment by reinink** [comment]
Yeah you can totally mix an Inertia app and regular Laravel app (regular Blade views) together. 👍

**Comment by robsontenorio** [comment]
But there is a problem, you will share one single `app.js`.

The example from PINGCRM consider you will ONLY use Inertia, there is no regular blades routes. Am i wrong @reinink ?

So , i needed to hack it . Probably there is a better solution.

```js
// Is it from regular blades or inertia?
const renderFuncion = app.dataset.page
    ? h => h(InertiaApp, {
        props: {
            initialPage: JSON.parse(app.dataset.page),
            resolveComponent: name => import(`./pages/${name}`).then(module => module.default),
        },
    })
    : undefined

new Vue({
    render: renderFuncion
}).$mount(app)
```

**Comment by sebastiandedeyne** [comment]
You wouldn't use the same `app.js` for Inertia and non-Inertia pages, you'd have separate scripts.

**Comment by abarreraaponte** [comment]
Well it depends, I do have one project where only the public (marketing/product) pages are using blade for SEO purposes, but everything that requires the user to be logged in is using Inertia. Because some Vue components (Like menus) are shared between the two contexts, I am sharing the same app.js for both. 

The main problem becomes bundle size for the marketing pages, but that can be addressed in its own way. 

---------------------

I do have another project however, where there was no need to share any components at all, and it that case, the approach of configuring laravel mix to generate two different js bundles was great.

**Comment by abdosaeedelhassan** [comment]
@robsontenorio , are you solve this problem?, share me you knowledge please

**Comment by joevallender** [comment]
> @robsontenorio , are you solve this problem?, share me you knowledge please

You can create separate .js files for each use case. For example

```js
// webpack.mix.js
mix.js('resources/js/inertia.js', 'public/js').vue();
mix.js('resources/js/blade.js', 'public/js').vue();
```

Put your usual Inertia setup in one file, and your code for blades in the other. 

Then refer to each one in the appropriate layout file, which might look like:

```html
// resources/views/app.php 
<script src="/js/inertia.js"></script>

// resources/views/layouts/default.php
<script src="/js/blade.js"></script>
```

**Comment by abdosaeedelhassan** [comment]
@joevallender I get it, thank you

**Comment by Ulrich15** [comment]
> > @robsontenorio , are you solve this problem?, share me you knowledge please
> 
> You can create separate .js files for each use case. For example
> 
> ```js
> // webpack.mix.js
> mix.js('resources/js/inertia.js', 'public/js').vue();
> mix.js('resources/js/blade.js', 'public/js').vue();
> ```
> 
> Put your usual Inertia setup in one file, and your code for blades in the other.
> 
> Then refer to each one in the appropriate layout file, which might look like:
> 
> ```
> // resources/views/app.php 
> <script src="/js/inertia.js"></script>
> 
> // resources/views/layouts/default.php
> <script src="/js/blade.js"></script>
> ```

But now how can i do to visit page from inertia Link to non inertia return response ?
