### ISSUE TITLE
Is it possible to load data for the initial request and have it persist afterward?

### ISSUE THREAD

**Issue by chinleung** [inertiajs/inertia-laravel#109]
I'm wondering if it's possible to load a set of data only on the first request and have them persist in the application without sending the data over again in the following requests.

For instance, sending some kind of config. I can achieve this with the following code:

```php
if ($request->header('x-inertia') !== true) {
   Inertia::share('config', ['name' => 'Laravel']);
}
```

However, this does not work for my following request as the `config` prop would be removed afterward.

**Comment by claudiodekker** [comment]
Hi,

Unfortunately, this isn't supported, and every request will re-fetch all the data it requests.
However, you could of course do some front-end trickery to solve your problem:

For example, you could create a VueX store, where you then store the data on the first request.
Then, on subsequent requests, you can 'merge' that request's data in/over the previously stored data, and then use that.

Of course, do keep in mind that this can become hairy and hard to maintain really quick, because it's quite likely you'll eventually run in to situation where you actually want to _omit_ certain data from the page, but because it's already there from the first or previous request, it'll still show up, requiring another workaround-hack or extra logic to keep things working as intended.

Hope this helps!

**Comment by claudiodekker** [comment]
Hi,

You should now be able to do this through [Lazy Props](https://inertiajs.com/partial-reloads#lazy-data-evaluation). 
Once your config is inside your Vue app, you could set it on a global variable, or set it on a data prop on the root Vue instance using something like `this.$root.prop = config`.

Hope this helps!

**Comment by laurentvd** [comment]
I just ran into a use case that makes this quite inconvenient. Basically, the application is multilingual and I need to be able to do something like `trans()` in the frontend. To do so, I need all possible translations in the frontend which can get quite large. 

Also, when I'm only sending the translations with the initial request, I run into issues when refreshing a page that does partial requests using `only`. The translation data is then omitted.

**Comment by claudiodekker** [comment]
@laurentvd Yeah, I do recognize that those kinds of limits exist with Inertia currently, but this isn't really the right place to discuss it, as this issue tracker is really intended for issues/bugs.

If you want, please do create a new feature request for this (if one doesn't already exist) over at https://github.com/inertiajs/inertia/discussions/categories/ideas (the main library repo). I think one might actually already exist, but I'm not 100% sure. 

We'll probably end up writing a solution to this at some point, but honestly, given the amount of 'more important things that are still on the TODO list, it will probably take us quite some time before we even get around to thinking about a way to do translations in a nice way.

Thanks!

**Comment by laurentvd** [comment]
Follow up at https://github.com/inertiajs/inertia/discussions/993

**Comment by qbuache** [comment]
Following https://tallpad.com/series/inertiajs-laravel-misc/lessons/handling-translations-in-laravel-and-inertiajs-applications

1. Make a Blade component
`php artisan make:component Translations`

2. In the `render` function of **Translations.php**, prepare all translations:
```
public function render() {
    $locale = App::getLocale();
    $translations = Cache::rememberForever("translations_$locale", function () use ($locale) {
        $phpTranslations = [];
        $jsonTranslations = [];

        if (File::exists(resource_path("lang/$locale"))) {
            $phpTranslations = collect(File::allFiles(resource_path("lang/$locale")))
                ->filter(fn ($file) => $file->getExtension() === "php")
                ->flatMap(fn ($file) => Arr::dot((File::getRequire($file->getRealPath()))))
                ->toArray();
        }

        if (File::exists(resource_path("lang/$locale.json"))) {
            $jsonTranslations = json_decode(File::get(resource_path("lang/$locale.json")), TRUE);
        }

        return array_merge($phpTranslations, $jsonTranslations);
    });

    return view("components.translations", ["translations" => $translations]);
}
```

3. In **translations.blade.php** define a global variable
```
<script>
    window._translations = @json($translations);
</script>
```

4. Import your component in **app.blade.php**
```
<body class="bg-light>
    @inertia
    <x-translations />
</body>
```

5. Create a vue composable (ex. useLang)
```
export function useLang(key, namespace = "", replacements = {}) {
    let translation = window._translations[`${namespace}${key}`] ?? key;
    Object.keys(replacements).forEach((r) => {
        translation.replace(`:${r}`, replacements[r]);
    });
    return translation;
}
```

Now you can import your composable and translate text using translations loaded only once at the page load

**Comment by mansoorkhan96** [comment]
> export function useLang(key, namespace = "", replacements = {}) {
>     let translation = window._translations[`${namespace}${key}`] ?? key;
>     Object.keys(replacements).forEach((r) => {
>         translation.replace(`:${r}`, replacements[r]);
>     });
>     return translation;
> }

This does not work if you are using SSR. window object is not available in SSR.
