### ISSUE TITLE
[Docs] Worth mentioning that Inertia data can just be an Arrayable class?

### ISSUE THREAD

**Issue by hailwood** [inertiajs/inertia-laravel#118]
So something cool I realised recently after my controllers grew substantially is that you don't have to pass an array to Inertia for the data, you can pass anything that is Arrayable.

This means that something like this just works

```php
use Illuminate\Contracts\Support\Arrayable;

class UsersInertiaDataProvider implements Arrayable
{
    public function users(): Collection
    {
        return User::query()->select(['id', 'name'])->
            ->with([ 'role' => fn(BelongsTo $query) => $query->select(['id']) ])
            ->get();
    }

    public function roles(): Collection
    {
        return Role::query()->select(['id', 'name'])->get();
    }

    public function toArray(): array
    {
        return [
            'users' => fn() => $this->users(),
            'roles' => fn() => $this->roles()
        ];
    }
}

class UsersController extends Controller
{
    public function Index()
    {
        return Inertia::render('Users/Index', new UsersInertiaDataProvider);
    }
}
```

I personally use the following base DataProvider 

```php
namespace App\Http\DataProviders;

use Illuminate\Support\Arr;
use Illuminate\Contracts\Support\Arrayable;

abstract class DataProvider implements Arrayable {

    protected array $staticData = [];

    public function toArray(): array
    {
        $excludedMethods = ['toArray', '__construct'];
        $publicMethods = array_diff(get_class_methods(static::class), $excludedMethods);

        $data = $this->staticData;
        foreach($publicMethods as $methodName) {
            $data[$methodName] = fn() => app()->call([$this, $methodName]);
        }

        return $data;
    }

}
```

Which means that a dataProvider looks like

```php
class UsersDataProvider extends DataProvider
{

    public function users(Request $request): Collection
    {
        return $request->user()->organisation->users()->select(['id', 'name'])->get();
    }

    public function roles(): Collection
    {
        return Role::query()->select(['id', 'name'])->get();
    }
}
```

As the base toArray will automatically add any public methods to the array and resolve them using the IOC container.

Anyway, I'm just wondering if it's worth mentioning in the docs that this is possible as it really tidies up some gnarly looking controllers!

**Comment by claudiodekker** [comment]
Hi,

While [you're absolutely right](https://github.com/inertiajs/inertia-laravel/blob/e7b95274dc0f6d4148380e2c45ba1c94f77c1c9c/src/ResponseFactory.php#L54) on the `Arrayable` implementation, the docs serve as a generic _one-architecture-fits-all_ overview of the Inertia framework, and not being able to document all the adapter-specific 'hidden gems' is one of the unfortunate side effects of this.

Of course, that does not take away that you can always try to suggest it by creating a PR to the docs: https://github.com/inertiajs/inertiajs.com/tree/master/pages

Hope this helps!

**Comment by NickSdot** [comment]
I also think it would be beneficial to document *some* adapter specific features. I can definitely think of a few things that would be worth documenting - but which would necessarily be adapter specific.

Considering a structure, it most likely wouldn't be worth to to try to force this into the existing pages structure. And neither I do think it makes sense that each adapter would have several pages. I rather think, and would like to propose, the following approach:

**Menu**
- Core concepts
- The basics
- **Adapters**
  - Laravel
  - Rails
  - [Community Packages](https://inertiajs.com/community-adapters)
- Advanced

In the end adapters are packages for Inertia.js. This in mind, it is a common pattern to use the above structure. The Laravel documentation for instance calls them [packages](https://laravel.com/docs/8.x/), PestPHP calls them [plugins](https://pestphp.com/docs/installation) and Inertia.js keeps calling them adapters.


---

By the way @reinink and @claudiodekker, [inertiajs/inertiajs.com](https://github.com/inertiajs/inertiajs.com/tree/master/pages) is still set to private. Is there any chance to switch the repo back to public now that SSR is (almost) released? It would enable to contribute again and issues related to the docs wouln't be forced to end up here.

**Comment by crnkovic** [comment]
Looks like the docs repo is public and anyone can submit docs changes: https://github.com/inertiajs/inertiajs.com

I personally think everyone can kinda infer from the context of the docs that you can use `Arrayable` (or essentially anything that you return as a response in Laravel), especially with something like this in the docs (where you can see an entire model is added to data):

```php
return Inertia::render('Event', ['event' => $event])
    ->withViewData(['meta' => $event->meta]);
```

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
