### ISSUE TITLE
Get request (replace) with data, returns 500 server error

### ISSUE THREAD

**Issue by msslgomez** [inertiajs/inertia-laravel#122]
I'm trying to use the replace request to filter some data but it crashes my website and returns a `This page isn’t working HTTP 500 ERROR` page on the browser. This request works locally without any issues, when I put it on the server and tried to do it I get a 500 error in the inspect and when the page reloads I get the full page 500 error and the page is down for at least 1-2 hours. 

This is the request code, I'm also doing some data manipulation in the if but it's very long so I removed it for reading sake 
```
this.$inertia.replace('/result/filter', {
    method: 'get',
    data: {
        period: this.filters.period_id,
        major: this.filters.major_id,
        course: this.filters.course_id,
        school: this.filters.school
    }
})
    .then(() => {
        if (this.$page.auth.user.flash.success) {
            this.survey_question = this.$page.auth.user.flash.success[0];                  
        } else if (this.$page.auth.user.flash.info || this.$page.auth.user.errors) {
            this.survey_question = [];
        }
    });
```

What could be causing the 500 server error?

**Comment by claudiodekker** [comment]
Hi,

This is a difficult thing to debug, as it has nothing to do with your javascript itself, but has everything to do with either your application's code or your server configuration (including how your application is deployed).

Anyway, to start at the beginning, I'm assuming that your application (in general) is working. 
As such, I'd recommend starting out by looking at the log files in your Laravel application. You can find these in the `storage/logs/` folder. 

Tip: An easy way to debug the issue (over SSH) is to do `tail storage/logs/your-laravel-log-file.log` and to make the request that causes this error. You should see the error show up in your terminal. To end the `tail` command, press `CTRL`+`C`.

Alternatively, you can enable debug in your `.env` file (`APP_DEBUG=true`) to show errors to the screen, but keep in mind that this isn't suitable for production environments, as it might expose sensitive data.

**Comment by herpaderpaldent** [comment]
I know the http allows a body for get requests but this request looks to me more like post?

**Comment by msslgomez** [comment]
I still don't know why it was doing it, I changed it to a post and it still persisted but now it's working no problem. I'm sure it has something to do with the server but after changing it to a post it seemed to help.

**Comment by herpaderpaldent** [comment]
If you want to us the get variant you should add the params as query paramenter.
