### ISSUE TITLE
Meta title only show , description and keywords not showing yet 

### ISSUE THREAD

**Issue by githubtagh** [inertiajs/inertia-laravel#126]
Meta title only show , description and keywords not showing yet after right click and view page source 
my code like
```
<script>
export default {
  props: ["job", "realtedJobs", "instructions", "mostViwedJobs"],
  metaInfo() {
    return {
      title: "Default App Title",
      meta: [
        { charset: "utf-8" },
        { name: "description", content: "this is description" },
        { name: "keywords", content: "this,is,key,words,data" },
        { name: "viewport", content: "width=device-width, initial-scale=1" }
      ]
    };
  }
};
</script>
```

**Comment by claudiodekker** [comment]
Hi,

To keep Inertia small and flexible, it doesn't ship with a built-in meta manager. While I do agree that the documentation doesn't explicitly state this, [the examples shown](https://inertiajs.com/pages#title-and-meta-tags) exist more as an example of how usage with [vue-meta](https://github.com/nuxt/vue-meta) would look like.

As such, have you tried installing & configuring [vue-meta](https://github.com/nuxt/vue-meta)?

**Comment by claudiodekker** [comment]
Hi,

Since there hasn't been any activity on this issue since my last reply a while back, I'll assume that the above solved your problem and will close this issue for now. If you feel like it hasn't, feel free to re-open it at any time by leaving a new comment. 

Thanks!
