### ISSUE TITLE
Cannot read property 'auth' of undefined" using ':src'

### ISSUE THREAD

**Issue by jajamoks** [inertiajs/inertia-laravel#128]
![image](https://user-images.githubusercontent.com/24262635/88460541-8568a000-cecf-11ea-87dd-519f7a0b6ac4.png)

![image](https://user-images.githubusercontent.com/24262635/88460600-f3ad6280-cecf-11ea-88b3-c98aab31307a.png)

![image](https://user-images.githubusercontent.com/24262635/88460559-a5985f00-cecf-11ea-8e56-94e4ccd5e65c.png)

but when I display it like this '{{$page.auth.user.avatar}} it got the correct value.

**Comment by Juhlinus** [comment]
Hi @jajamoks !

Try writing it like this: `:src="$page.auth.user.avatar"`. It should work much better for you.

Feel free to join our Discord if you have any other questions.

https://discord.gg/5nVZ4x

**Comment by jajamoks** [comment]
@Juhlinus I got same error 
"TypeError: Cannot read property 'auth' of undefined"

**Comment by jajamoks** [comment]
fixed using ':src="$page.auth.user.avatar"
