### ISSUE TITLE
Use Blade template views as fallback

### ISSUE THREAD

**Issue by ekafyi** [inertiajs/inertia-laravel#129]
I have an existing Laravel site with Blade views. It was originally built to work with no JS, but over time we added a lot of client-side vanilla JS here and there. We are looking to modernize our website to (1) serve modern JS UI lib/fw experience to users on supported browsers, (2) still give the existing basic version to users on unsupported browsers (be it no JS or old/nonstandard browsers).

I know Inertia does not support SSR, but I wonder if it’s possible to use Blade template as a “fallback”?

With the example function below, is there a way to render the Inertia view out of, say, `views/users/index.blade.php` instead of the default `app.blade.php`?

```php
class UsersController
{
    public function index()
    {
        $users = User::active()
            ->orderByName()
            ->get()
            ->only('id', 'name', 'email');

        return Inertia::render('Users', [
            'users' => $users
        ]); 
        // return with view('users.index') and the same data?
    }
}
```

The Blade template file will render basic no-JS code as well as the app element that will be replaced by the Inertia app if supported.

```html
<!DOCTYPE html>
<html>
  <head>
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet" />
    <script src="{{ mix('/js/app.js') }}" defer></script>
    <!-- etc -->
  </head>
  <body>

    <div id="app">
      <!-- fallback content for noJS here -->
    </div>
    
  </body>
</html>
```

Is this possible at all? Thank you.

**Comment by Juhlinus** [comment]
Hi @ekafyi !

I actually have a package for Laravel called [Depictr](https://github.com/juhlinus/depictr)  that handles the SSR for crawlers.

To answer your question: what you’re looking for is Inertia::setRootView(). This will change the root view for Inertia to what ever you wish.

**Comment by ekafyi** [comment]
Ooooh setRootView() is perfect @Juhlinus , thank you!

Another question, instead of `@inertia` directive is it possible to use eg. `<div id="app">` so I can render the fallback content (ie. for non-modern browsers or JS turned off) inside? Or maybe it's a better idea to have the fallback content separately and hide it from inside the Inertia app?

**Comment by claudiodekker** [comment]
Compatability wise, the latter would be better. However, you'd probably run into a [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) situation. Especially animations can start behaving really odd on the initial pageload.

Alternatively, you could try what you suggested by replacing the `@inertia` directive, which is fairly simple, but be warned that [here be dragons](https://en.wikipedia.org/wiki/Here_be_dragons), as it could be changed in the future without warning:
https://github.com/inertiajs/inertia-laravel/blob/e7b95274dc0f6d4148380e2c45ba1c94f77c1c9c/src/ServiceProvider.php#L28-L30

**Comment by reinink** [comment]
So, trying to mix Inertia.js and standard Blade views is going to be tricky. You'd essentially be duplicating all your templates in both Vue and Blade, and honestly that sounds like an enormous amount of work. That's not really something Inertia.js was designed for...even if it might technically be possible using the recommendations above.

That said, I wish you success with your efforts! 😊
