### ISSUE TITLE
Create Shared data that only loads on first page visit

### ISSUE THREAD

**Issue by zoomyboy** [inertiajs/inertia-laravel#134]
Hey guys,

I would like to use shared data that only evaluates at the first page visit - since this data is used by a single global static menu component that is rendered in the layout only once. The documentation says, that I can lazy loading of shared data when wrapping the data in a closure:

The server-side adapters provide a way to preassign shared data for each request. This is typically done outside of your controllers. Shared data will be automatically merged with the page props provided in your controller.

```
// Lazily
Inertia::share('auth.user', function () {
    if (Auth::user()) {
        return [
            'id' => Auth::user()->id,
            'first_name' => Auth::user()->first_name,
            'last_name' => Auth::user()->last_name,
        ];
    }
});
```

However, if I take a closer look at the Response (``src/Response.php:59``), I cannot see any condition which decides wether this data should be evaluated or not:

```
        array_walk_recursive($props, function (&$prop) use ($request) {
            if ($prop instanceof Closure) {
                $prop = App::call($prop);
            }

            if ($prop instanceof Responsable) {
                $prop = $prop->toResponse($request)->getData();
            }

            if ($prop instanceof Arrayable) {
                $prop = $prop->toArray();
            }
        });
```

I find this a bit confusing, because a closure is in fact not a lazy loaded value for the component. So what's the purpose of this lazily comment in the docs then? Or am I completely wrong with this solution?

**Comment by claudiodekker** [comment]
Hi,

Good question. In my personal opinion, you're absolutely right, and there isn't _really_ a way to lazy-load. 

However, if you interpret the docs slightly different, using a closure is exactly what allows you to lazy-load data using conditionals. For instance, in your example, your conditional is whether the user is authenticated or not. Here's an alternative example of that same exact perspective:

```php
// Lazily
Inertia::share('my-conditional-value', function () {
    if (request()->has('trigger')) {
        return Auth::user()->pages;
    }
});
```

This way, only if the lazy request has a `trigger` field in it, it'll actually query the current user's pages relationship.

Hope this helps!

**Comment by hailwood** [comment]
Adding onto this an `Inertia::shareOnce` method would be pretty awesome if the client knew to keep that data and merge it back in on every subsequent page visit.

Good for things like sending across translation objects, or enum maps

**Comment by zoomyboy** [comment]
@claudiodekker Well, the conditional of ``if (Auth::user())``is just preventing the properties from being null. Meaning if the same already authenticated user goes to another page, the condition would always be true.

So is there an initial condition which says "is this a full page visit or a partial page reload?". This would be appropriate I guess. Or I could e.g. cache the original value with some session identifier as a key somewhere and return that on subsequent visits. Kinda hacky still, but probably working.

However, I would agree with the suggestion of @hailwood since this would be resolved properly by the inertia core.

**Comment by claudiodekker** [comment]
Yeah, I definitely see the appeal, but I don't see us implementing it any time soon for a couple of reasons:

- Populating the client with an 'initial sate' kinda conflicts with ["The Inertia Way™"  of using the back-end state](https://inertiajs.com/who-is-it-for).
- Even if we would implement this as an optional feature, it would make the eventual need to (conditionally) update this state all the more complex, as that would require another separate feature.
- You can kind-of already detect this initial state: **On an initial page visit, Inertia renders the page based on the `app.blade.php` layout**. This theoretically allows you to include a `<script>` in the `<head>` there in which you do something like `window.myInitialSharedData = "{{ json_encode($initialData) }}"`

I hope that this answers your question and solves your need 👍

**Comment by reinink** [comment]
I agree with @claudiodekker's answer here. In a regular server-side rendered app, you don't think twice about re-rendering the app header (which displays the currently authenticated user) over and over on every page visit. Think of Inertia the same way.

The second you stop doing it this way, you've now got a state issue, and things become much more complex.

So yeah, just send it on every request. 👍

**Comment by hailwood** [comment]
@ibrunotome you can use `$request->inertia()` for a slightly less fragile check since the `X-Inertia` header is an implementation detail.

**Comment by sandcore-dev** [comment]
> In the response of the Laravel adapter the [shared props are merged with the component props](https://github.com/inertiajs/inertia-laravel/blob/726b1e0d4fc399089dd29820a78e40d1c9aad2eb/src/ResponseFactory.php#L70) which means the component props take precedence.

I'm experiencing a similar problem.

If shared data goes like this:
```php
['foo' => ['bar' => 1]]
```
and you want to do this in your controller:
```php
return Inertia::render(['foo' => ['baz' => 2]]);
```
then the shared `foo` array will be replaced by the local `foo` array. 

I would like to be able to modify this behavior, perhaps with an extra (optional) parameter to `ResponseFactory::render` so that `array_merge_recursive($this->sharedProps, $props)` will be used instead of `array_merge($this->sharedProps, $props)`.
