### ISSUE TITLE
Profile picture not saved 

### ISSUE THREAD

**Issue by Parsa237** [inertiajs/inertia-laravel#148]
For some reason, when I try to upload a profile picture it says it is saved. However, it is not. When I try this with changing my email and username it does get saved and it is visibly changed. I do not know what the problem is. I have been looking for a solution for over a day now and I cannot find it. Does anybody know how I can solve this?

**Comment by claudiodekker** [comment]
Since this issue has been open for quite a while without any further activity, I'll be closing it for now.
Feel free to re-open this by providing more details as requested in my previous comment.
