### ISSUE TITLE
Breaking change in 0.2.12

### ISSUE THREAD

**Issue by AlexVanderbist** [inertiajs/inertia-laravel#149]
If you're not using the default `web` middleware group, pulling in 0.2.12 by running `composer update` will break your app as the middleware wont be applied anymore out of the box. 
I'm all for this change but it should probable be tagged as a new minor pre-release (0.3.0) instead :)

**Comment by reinink** [comment]
Yeah, we probably should have, but I think it's too late for that now unfortunately. 😕 

Sorry about that @AlexVanderbist!
