### ISSUE TITLE
No way to set base url

### ISSUE THREAD

**Issue by gdinko** [inertiajs/inertia-laravel#157]
1. Install laravel 8 in subfolder localhost/blahblah
2. in jetstream / intertia all request and links does not work
3. No way to set the base url

**Comment by reinink** [comment]
Hmm, sorry you're having trouble, but I don't think this is really an Inertia related issue. This sounds much more like a Laravel issue. Trying to serve Laravel from a sub folder doesn't work great. I'd recommend asking about this on the Laracasts forums. 👍 

Good luck!

**Comment by naimurhasan** [comment]
any luck?

**Comment by khanks** [comment]
The only framework I've ever encountered where its already-strict "opinions" also include whining about being in a subfolder. Like, pretty much everyone who hosts multiple sites on a VPS does this (public_html/site1, public_html/site2/, yadayadayada).
