### ISSUE TITLE
HMR + Browsersync

### ISSUE THREAD

**Issue by nckrtl** [inertiajs/inertia-laravel#16]
I really like this project, however I'm wondering if what I'm trying to accomplish is currently possible. I would really like to develop with HMR (npm run hot), as you can change the content of vue files and they're being updated in the browser while maintaining the state of the component.

However, when I try to update css files, the browser becomes blank. Console is showing `TypeError: null is not an object (evaluating 'document.body.getElementsByTagName')`

With some searches on Google I came across a couple of posts stating that Laravel Mix and HMR mode only works well for .vue files. CSS files are not being watched/updated. So I wanted to switch to Browsersync to get CSS file changes being detected and auto reloading the browser. That won't work either because the inertialinks trigger an error because the domain 0.0.0.0:3000 is not the same as the project url. The console shows `Unhandled Promise Rejection: SecurityError: Blocked attempt to use history.pushState() to change session history URL from https://localhost:3000/about to https://<project>.test/.`.

I understand the project is very early stage, but I was wandering if its possible to get HMR working in combination with Browsersync. My goal is to get HMR working with support for CSS file changes, that would make development a real bliss. If you guys have an alternative development flow I'd be happy to learn about it.

Thanks

**Comment by reinink** [comment]
Pinging @sebastiandedeyne. I know he's done some work to get hot reloading working that might be related to this.

**Comment by sebastiandedeyne** [comment]
I got HMR working with Inertia in most cases. There's one issue where there's odd behaviour when a hot reload happens after you've navigated with Inertia, but I solved that by doing a full refresh in those cases.

I'm not using Laravel Mix, but my webpack is set up to mirror Mix as much as possible, so I don't think it really matters much. However this is _without_ BrowserSync.

I added this to my main `app.js` file and it seems to work:

```
if (module.hot) {
    const firstVisit = window.location.pathname;

    module.hot.accept();

    module.hot.dispose(() => {
        if (firstVisit !== window.location.pathname) {
            window.location.reload();
        }
    });
}
```

I assume this doesn't work for CSS either though (CSS changes cause full reloads), but that's not a problem for us since we're using Tailwind, so actual CSS changes are minimal.

**Comment by nckrtl** [comment]
Thx for your replies. @sebastiandedeyne your snippet doesn't seem to work for me. I alternatively got it working with mix like this:

```
const cssImport = require('postcss-import')
const cssNesting = require('postcss-nesting')
const mix = require('laravel-mix')
const path = require('path')
const tailwindcss = require('tailwindcss')

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.options({
  hmrOptions: {
    host: 'pingcrm.test',  // site's host name
  }
});

mix.js('resources/js/app.js', 'public/js')
  .postCss('resources/css/app.css', 'public/css', [
    cssImport(),
    cssNesting(),
    tailwindcss('tailwind.js'),
  ])
  .webpackConfig({
    output: { chunkFilename: 'js/[name].[contenthash].js' },
    resolve: {
      alias: {
        'vue$': 'vue/dist/vue.runtime.js',
        '@': path.resolve('resources/js'),
      },
    },
    devServer: {
      proxy: {
        host: '0.0.0.0',  // host machine ip
        port: 8080,
      },
      watchOptions:{
        aggregateTimeout:200,
        poll:5000
      },
    },
  })
  .version()
  .sourceMaps()
```

With adding (tailwind) classes / inline styling for development is actually working pretty well. It was something I haven't thought about yet. It's also pushing me to use tailwind more, which I like. Thx!

**Comment by jphms** [comment]
> I got HMR working with Inertia in most cases. There's one issue where there's odd behaviour when a hot reload happens after you've navigated with Inertia, but I solved that by doing a full refresh in those cases.
> 
> I'm not using Laravel Mix, but my webpack is set up to mirror Mix as much as possible, so I don't think it really matters much. However this is _without_ BrowserSync.
> 
> I added this to my main `app.js` file and it seems to work:
> 
> ```js
> if (module.hot) {
>     const firstVisit = window.location.pathname;
> 
>     module.hot.accept();
> 
>     module.hot.dispose(() => {
>         if (firstVisit !== window.location.pathname) {
>             window.location.reload();
>         }
>     });
> }
> ```
> 
> I assume this doesn't work for CSS either though (CSS changes cause full reloads), but that's not a problem for us since we're using Tailwind, so actual CSS changes are minimal.

I feel like this could very well be in the documentation somewhere. Thanks for the snippet, btw.
