### ISSUE TITLE
Inertia::share() in Jetstream/Laravel 8

### ISSUE THREAD

**Issue by gregupton** [inertiajs/inertia-laravel#160]
Trying to share user model relationship data `Auth::user()->allPermissions()`  via the `JetStreamServiceProvider`, but it seems that Auth::user() isn't available in the boot method and if I call my `$this->registerInertia();` method  that holds my ` Inertia::share([ // Data ])` in the register method I get 

```php
Illuminate\Contracts\Container\BindingResolutionException
Target class [hash] does not exist.
```

Can someone help get me pointed in the right direction? I know this is more of a ***Greg***/Laravel issue rather than an issue with inertia... but appreciate any help resolving this.

**Comment by reinink** [comment]
Have you tried lazy loading this? That's typically what's required.

```php
use Inertia\Inertia;
use Illuminate\Support\Facades\Auth;

// Lazily
Inertia::share('auth.permissions', function () {
    if (Auth::user()) {
        return Auth::user()->allPermissions();
    }
});
```

**Comment by gregupton** [comment]
Yep, that was it.
