### ISSUE TITLE
[Idea] Add response()->inertia($component, $props) macro

### ISSUE THREAD

**Issue by nmarschallek** [inertiajs/inertia-laravel#162]
I've found it quite useful using this macro in my projects, so I figured some others might as well. I've tried to create a pull request but I couldn't quite get the test to pass: https://github.com/nmarschallek/inertia-laravel/commit/4dd02d540d28e4b921ac3a3c47013666642c2ea2

It involves adding a response macro for inertia:

```php
response()->inertia('User/Edit', [
    'foo' => 'bar'
]);
```
Which works the same as:
```php
Inertia::render('User/Edit', [
    'foo' => 'bar'
]);
```

**Comment by reinink** [comment]
Are you aware that there is an `inertia()` helper. Is that sufficient?

**Comment by nmarschallek** [comment]
Was not aware, that's pretty nice. Thanks!

**Comment by reinink** [comment]
Yeah, nice and short, and no need to import anything. 👍

**Comment by herpaderpaldent** [comment]
Seems undocumented?

**Comment by claudiodekker** [comment]
@herpaderpaldent Yeah, that's because it's a thing that's specific to the Laravel adapter. The documentation itself only covers the primary functionalities as well as the way Inertia works, so having `Inertia::render` there is already sufficient.

For example, another helper that exists and isn't documented is the following, which is really just a GET method that returns the Inertia view directly:
```php
Route::inertia('/example', 'Example/Page', [
    'prop' => 'value'
]);
```

**Comment by reinink** [comment]
> The documentation itself only covers the primary functionalities as well as the way Inertia works, so having `Inertia::render` there is already sufficient.

It might be worth adding it though...we show alternative ways of doing things in other places. For example, the Svelte links can use the `inertia` directive or `<InertiaLink>` component.

**Comment by reinink** [comment]
Added: https://github.com/inertiajs/inertiajs.com/commit/06b076c6f18a06cbc4cf31a78107a1725b9d4ee6

**Comment by herpaderpaldent** [comment]
i couldn't ask for more <3
