### ISSUE TITLE
Inertia ignores my form errors

### ISSUE THREAD

**Issue by wassim** [inertiajs/inertia-laravel#172]
I'm using Laravel + Jetstream + Inertia. Errors are printed on form, but the promise is continuing anyway...

```
data() {
    return {
        form: this.$inertia.form({
            title: this.title,
            desc: this.desc
         }, {
             bag: 'createPost',
             resetOnSuccess: false,
         }),
    }
},

methods: {
    createPost() {
        this.form.post(route('posts.store'), {
            preserveScroll: true
        }).then(() => {
            // then is executed even when there is errors
        })
    },
},
```

In my controller:

```
$validatedData = $request->validateWithBag('createPost', [
    'title' => ['required', 'string', 'max:255'],
    'desc' => ['required', 'string'],
]);
```

Any ideas?

**Comment by reinink** [comment]
Yes, that makes sense...a validation error doesn't generate a `422`, but rather a `200`, because a redirect happens server-side, resulting in a valid `200` page visit that has the validation errors in the session (flash).

Because it's a `200` response, the promise `then()` function is called.

This is confusing, which is why we've deprecated the visit promises, and are recommended using event callbacks instead.

You can read more about that here: https://inertiajs.com/manual-visits#promise-deprecation

Hope that helps! 👍

**Comment by wassim** [comment]
@reinink thanks for the fast response! This is a bit confusing indeed.

I tried with the following but getting the same result:

```
methods: {
    createSite() {
        this.form.post(route('sites.store'), {
            preserveScroll: true,
            onSuccess: () => {
                console.log("success")
           },
       })
    },
},
```

**Comment by claudiodekker** [comment]
Hi @wassim,

This is expected, because the [`onSuccess` event callback](https://inertiajs.com/events#success) doesn't indicate that the action itself succeeded, but rather that a successful Inertia page visit occurred (meaning, a valid response usable by Inertia came back)

**Comment by reinink** [comment]
Here is how you check for validation errors:

```js
methods: {
    createSite() {
        this.form.post(route('sites.store'), {
            preserveScroll: true,
            onSuccess: page => {
                if (Object.keys(page.errors).length === 0) {
                  console.log("success")
                }
           },
       })
    },
},
```

You can see we actually do this in Ping CRM, [here](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Edit.vue#L91).

The point is, a `200` Inertia visit back to the form page with validation errors is considered a successful Inertia visit.

**Comment by wassim** [comment]
@claudiodekker @reinink thanks! that's make sense. Just a little fix of your code:

```
if (Object.keys(page.props.errors).length === 0) {
    console.log("success")
}
```

You may also want to add the Ping CRM link on the https://inertiajs.com/how-it-works page maybe?

**Comment by claudiodekker** [comment]
@wassim That's still done the `.then()` way.. In the next major release, it'll be included 👍  https://github.com/laravel/jetstream/pull/344/files/b8625ed6bcc2cc3b074fe8f21657e090a4f6c50d#diff-c4e6c30ef5d730ce76c9e0a251811e0ccb93b57d9f876efca478ec7fb997e38a

**Comment by anubra266** [comment]
> Here is how you check for validation errors:
> 
> ```js
> methods: {
>     createSite() {
>         this.form.post(route('sites.store'), {
>             preserveScroll: true,
>             onSuccess: page => {
>                 if (Object.keys(page.errors).length === 0) {
>                   console.log("success")
>                 }
>            },
>        })
>     },
> },
> ```
> 
> You can see we actually do this in Ping CRM, [here](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Users/Edit.vue?rgh-link-date=2020-10-22T13%3A59%3A34Z#L91).
> 
> The point is, a `200` Inertia visit back to the form page with validation errors is considered a successful Inertia visit.

Please how does this work in React? @reinink 
I just upated Inertia, and was long gone, before I found out there were lots of changes from my previous Inertia version, just got aware of the middleware minutes ago

**Comment by anubra266** [comment]
I just did some research around the working of this stuff, so would I be right to believe that in the newer versions, Inertia automatically shares errors to my frontend? @reinink

**Comment by reinink** [comment]
Yes, the Laravel adapter automatically shares validation errors as of [v0.2.9](https://github.com/inertiajs/inertia-laravel/releases/tag/v0.2.9).

**Comment by anubra266** [comment]
Okay thanks a lot @reinink
