### ISSUE TITLE
The PATCH method is not supported for this route after redirect back

### ISSUE THREAD

**Issue by tanshiqi** [inertiajs/inertia-laravel#173]
I use a link for quick submit updates on list page：
```
<inertia-link method="patch" :href="route(......)" preserve-scroll>update</inertial-link>
```
on Controller:
```
// Do update and success
return redirect()->back();
```
I got this error:
```
The PATCH method is not supported for this route. Supported methods: GET, HEAD, POST.
```
It seems that the GET request is not used when returning, but the PATCH method when updating before
This problem did not occur in v0.2

**Comment by claudiodekker** [comment]
Hi @tanshiqi,

Just to be clear: This error occurred _after_ the upgrade, right? What I mean by this, is: The endpoint used to work just fine _before_ the upgrade?

(Ref: https://github.com/inertiajs/inertia/issues/284)

**Comment by tanshiqi** [comment]
@claudiodekker Yes. everything is fine before upgrade.
I just tried reinstall a fresh website by laravel jetstream. Still have this problem

**Comment by tanshiqi** [comment]
I think i found the problem.
A new middleware should be registered after upgrade to v0.3...
I should read changlog first

**Comment by claudiodekker** [comment]
Thanks! Good to hear you managed to solve it, and good to know that this is one-of the side effects of missing part of the upgrade! 👍

**Comment by reinink** [comment]
Yeah this makes sense, since without the middleware installed, `302` redirects are not changed to `303` redirects, which means you can only redirect to a `GET` endpoint from a `GET` or `POST` request (see [here](https://inertiajs.com/redirects#303-response-code)). The Inertia middleware automatically changes this for you. 👍
