### ISSUE TITLE
Inertia doesn't catch data from server side redirect

### ISSUE THREAD

**Issue by wassim** [inertiajs/inertia-laravel#177]
I don't if this is a normal behavior.

Controller:

```php
...
$post->save();

return back()->with([ 'post' => $post]);
```

Vue:

```javascript
props: {
    post: Object
},

data() {
    return {
        form: this.$inertia.form({
            title: '',
            ...
        }, {
           bag: 'createPost',
           resetOnSuccess: false,
        }),
    }
},

methods: {
    createPost() {
        this.form.post(route('posts.store'), {
            preserveScroll: true,
            onSuccess: page => {
                if (! this.form.hasErrors()) {
                    console.log(this.post); // undefined
                    console.log(page); // no trace of post in page object
                }
            }
        })
    },
},
```

**Comment by reinink** [comment]
Inertia will not automatically share your flash data. You need to do this yourself. See the [shared data](https://inertiajs.com/shared-data) page for more information.

That said, the better way to do this is, after you create your new post, redirect to your show post page (`/posts/{id}`). That endpoint will then include the `post` as part of the page props.

If you have a posts index page, that lists all the posts, and has a form to create a new post, then simply redirect back to the posts page...which will include all the `posts` in the page props...including the newly created post.

Point is, don't try to return data from the store post endpoint. Rather, redirect to a different page that will return a prop Inertia response (page) with the appropriate data.

**Comment by reinink** [comment]
As a follow up:

Don't think of Inertia as a different way to make xhr/fetch requests.

Instead, think of it like a classic server-side rendered application that does full page loads. In that context, after you submit a form to a `store` endpoint, you don't return data back...but instead you redirect to a different page. Maybe it's your post index page, or the post show page...wherever.
