### ISSUE TITLE
The PUT method is not supported for this route. Supported methods: GET, HEAD

### ISSUE THREAD

**Issue by steven-lury** [inertiajs/inertia-laravel#180]
I'm using Inertia and Laravel. I registered routes in web.php. When I send data to the server, I get error 405 which tells me `MethodNotAllowedHttpException` and the `PUT methods is not allowed for this route` but the data was updated successfully in database;
in `question.vue`

 
    update () {
                this.$inertia.put(`questions/${this.id}`, this.question, {
                    onSuccess: () => {
                    //do some stuffs
             })
      }

in `QuestionsController.php`

          public function update(AskQuestionRequest $request, Question $question)
              {
          
          $question->update($request->only(['title', 'body']));
          return redirect()->back()->with('successMsg', 'Your Question has been updated successfully');
         }

![response](https://user-images.githubusercontent.com/36078546/97787741-51390580-1bc9-11eb-8cca-2ec24f2f8b6b.png)
![rl](https://user-images.githubusercontent.com/36078546/97787745-55652300-1bc9-11eb-8470-546cad472199.png)

**Comment by claudiodekker** [comment]
Hi,

Because of a long-term bug somewhere in either Symfony or PHP, forms unfortunately can't make 'real' PUT, PATCH, or DELETE requests. However, Laravel has a workaround for this, which involves making the request as a `POST`-call, and adding a `_method` field containing the 'actual' method to spoof these HTTP verbs.

That said, because Inertia's clients-side adapters aren't backend-framework specific, there isn't automatic behaviour to solve this problem. So, what you'll have to do instead, is make your call like this:

```js
this.$inertia.post(`questions/${this.id}`, { 
    _method: 'put',  
    ... this.question 
  }, {
    onSuccess: () => {
      //do some stuffs
    }
  }
)
```

Hope this helps!

**Comment by steven-lury** [comment]
@claudiodekker Thanks for your reply. Unfortunately the problem is still remained. I think the problem is related to the `QuestionsController.php` when I update the question , if I comment the `return redirect()->....` it doesn't produce the error 302.
I looked the **pingcrm** project , I follow that code, but still get stuck with this problem. any help

**Comment by claudiodekker** [comment]
Hi,

Hmm.. Do you have the [Inertia middleware](https://inertiajs.com/server-side-setup#middleware) registered? 
Inertia turns 302 redirects into 303's, which should solve the 302 'error'

Let me know if this helps!

**Comment by reinink** [comment]
Yeah this 100% seems like a missing middleware issue.

Assume you're on version `0.3.x` of this package, see the upgrade guide [here](https://github.com/inertiajs/inertia-laravel/releases/tag/v0.3.0).
