### ISSUE TITLE
Inrtia.reload not working properly

### ISSUE THREAD

**Issue by zendzo** [inertiajs/inertia-laravel#182]
i try to make reload since my controller action is return to same page after creating
but it is okay when i use `Inertia.visit(route('package.index'), { only: ['activePackages'] }`
below are my code 
```
methods: {
    handleSubmit() {
      Inertia.post(route("package.store"), this.newPackage,{
        onSuccess: () => {
          Inertia.reload({only: ['activePackages']})
        },
      })
    }
```

```
public function store(Request $request)
    {
        $this->validate($request, $this->rules);
        
        Package::create([
            'name' => $request->name,
            'amount' => $request->amount,
            'days' => $request->days
        ]);

        return Redirect::route('package.index');
    }
```

**Comment by claudiodekker** [comment]
Hi,

If I'm assuming correctly, the page on which this form exists is the `package.index` endpoint/page, and that's the page you're trying to reload after the form is submitted?

If so, all you have to do is this:
```js
      Inertia.post(route("package.store"), this.newPackage, {
        only: ['activePackages'],
      })
```

This would then cause the following flow:
1. You load the `package.index` endpoint/page, which will automatically load all props (to render the page)
2. You submit the form, which calls the `package.store` endpoint with the `only: ['activePackages']` parameter
3. Laravel processes the request in your controller, and redirects Inertia to the `package.index` endpoint, passing the `only: ['activePackages']` parameter along with this redirect
4. The `package.index` page gets loaded (again), but this time sees that there is an `only: ['activePackages']` parameter, so it only loads those parameters into the Inertia response.
5. The JS app receives the response, sees that the page is the same and that there's a `only: ['activePackages']` on the response, at which point it only 'overwrites' that property in it's current state.

I hope this helps!
