### ISSUE TITLE
route().current() doesn't work with a port number in the URL

### ISSUE THREAD

**Issue by joseph-d** [inertiajs/inertia-laravel#183]
Running a fresh install of Laravel 8 with Jetstream (Inertia) scaffolding, I have come across an issue whereby `route().current()` does not work if there is a port number in the URL. For example, while developing using Browsersync (typically port 3000).

A quick way to check this is to access the dashboard URL on a fresh Jetstream/Inertia installation at `http://laravel.local` and then type `route().current()` in the console and it will correctly return `dashboard`. However, if you then run the same app through Browsersync and go to `https://laravel.local:3000` (for example) and type `route().current()` then it will return `undefined`

Routing is not completely broken, though. It still works in terms of linking to named routes etc., it just seems to be the `route().current()` which isn't working.

**Comment by sinnbeck** [comment]
That sounds like a problem with Ziggy, not inertia. There is no `route()` help in Inertia to my knowledge.

https://github.com/tighten/ziggy

**Comment by joseph-d** [comment]
Ah, ok. I'll close this and post a new issue there then. 

Thank you!
