### ISSUE TITLE
The right way to handle response?

### ISSUE THREAD

**Issue by djdev12** [inertiajs/inertia-laravel#185]
I'm not sure how to handle this response when working with Inertia. Hopefully you can tell me how to handle it.

I have a blog post and in the post view you have the option to upload an image. Images has their own model and the image upload is separate from the blog post update/save.

What should I return as the successful response and also the error response, if something goes wrong with the upload? Normally I would return JSON but not sure how to do it here with Inertia, at least not the proper way to do it.
`
public function store(Request $request)
	{
		$file = $request->file('image');

		$name = $file->getClientOriginalName();
		$extension = $file->getClientOriginalExtension();

		$path = 'images/' . Str::random(15) . '/';

		$image = Storage::disk('public')->putFileAs($path, $file, $name);

		if($image) {
			Auth::user()->images()->create([
				'path' => 'storage/' . $path,
				'name' => $name,
				'extension' => $extension,
				'imageable_id' => $request->id,
				'imageable_type' => 'App\\Models\\' . $request->type
			]);
			// Success response
		}

		// Error response
	}
`

**Comment by reinink** [comment]
In these situations, just use regular validation like you would with a normal Laravel application. You can read more about this here: https://inertiajs.com/forms#server-side-validation

Unrelated to Inertia, but still helpful to know as a Laravel developer—it's possible to manually throw a `ValidationException`. For example:

```php
$path = Request::file('photo')->store('photos');

if ($path === false) {
    throw ValidationException::withMessages(['file' => 'Unable to save file.']);
}
```

Hope that helps!
