### ISSUE TITLE
Shared Validation Errors missing in newest release

### ISSUE THREAD

**Issue by xyNNN** [inertiajs/inertia-laravel#188]
Hi!

I'm wondering why the shared validation errors from the 0.2.x release (see https://github.com/inertiajs/inertia-laravel/blob/v0.2.15/src/ServiceProvider.php#L27) isn't anymore in the 0.3.x release? I don't find any informations about this breaking change? Am I missing something out?

Thanks in advance!

Greets!

**Comment by xyNNN** [comment]
This commit broke the whole thing, see https://github.com/inertiajs/inertia-laravel/commit/b7e0c5f1ef1f67ea4f6446f901a2a0aad25aec45#diff-0dcb363b46434ce2fc8f2969d3e4a183bab1157c17425fb826da41427cff01e6

**Comment by RobertBoes** [comment]
v0.3.0 introduced a new middleware, see the release notes here https://github.com/inertiajs/inertia-laravel/releases/tag/v0.3.0

As you can see in the commit you linked, the validation errors have been moved to the middleware

**Comment by xyNNN** [comment]
Thanks @RobertBoes, make sense. It was not clear for me at the beginning ;) All fine, issue can be closed.
