### ISSUE TITLE
@inertiajs change root element id

### ISSUE THREAD

**Issue by muarachmann** [inertiajs/inertia-laravel#190]
Is there anyway to change the default root element id created using the Blade directive when we call `@inertiajs`? I see in this is done here - https://github.com/inertiajs/inertia-laravel/blob/91345989b5ee1d1d9ddcfaab578d442e4334321f/src/ServiceProvider.php#L28

**Comment by Hassanj343** [comment]
You can just replace @inertia tag to <div id="your-id-name goes here" data-page="{{ json_encode($page) }}"></div>

**Comment by sebastiandedeyne** [comment]
As Hassan mentioned, I believe that's the way to go. I don't think we necessarily need to expand the `@inertia` directive to support this, since the output is just a oneliner.

**Comment by muarachmann** [comment]
Hi @Hassanj343 thanks for your response... @sebastiandedeyne sure, I already had a way around that just wanted to know if there was a cooler way to do things. Thanks guys

**Comment by claudiodekker** [comment]
We actually had this implemented already at some point, but it caused issues (#140) so we had to revert it.
As of right now, there's several in-progress PRs for this, meaning it is still being considered: #186, #141, #178, #139

That said, @Hassanj343's suggestion is indeed pretty much the recommended approach for now 👍

**Comment by claudiodekker** [comment]
We've actually re-implemented this as part of #339, which should land soon 👍
