### ISSUE TITLE
User data always shared on fresh Laravel Jetstream install

### ISSUE THREAD

**Issue by marcomessa** [inertiajs/inertia-laravel#191]
Hi there, first of all thank you for your wonderful framework!! I'm really enjoying it.

I noticed that after a login in a fresh Laravel Jeststream application, all user data are always passed to the view and are accessible from the client. In addition, I can't overwrite this using HandleInertiaRequests middleware / Inertia::share and putting only user data I really need. I wonder if this is a wanted behavior and if there is an official way to change it.

Thank you again, have a nice day!

**Comment by maggz69** [comment]
This is actually more of a jetstream question rather than inertiajs. But to answer your question, 

The user data is shared from the ShareInertiaData middleware `{PROJECT_INSTALLATION_FOLDER}\vendor\laravel\jetstream\src\Http\Middleware\ShareInertiaData.php`

This middleware is added to the web group. You could thus override this middleware with your own custom one indicating what data you'd like to to share. Then go ahead and append your custom middleware to the web group.

**Comment by marcomessa** [comment]
Thank you very muchfor your help, @maggz69! Cheers!

**Comment by claudiodekker** [comment]
Thanks for helping out here, @maggz69! 👍

**Comment by jaulz** [comment]
@maggz69 how is it possible to override that middleware? As far as I can see I can only override the keys that were set but I cannot completely disable the middleware.

**Comment by marcomessa** [comment]
@jaulz you need to:
- copy original `\vendor\laravel\jetstream\src\Http\Middleware\ShareInertiaData.php` in you `App\Http\Middleware`
- change its namespace to `App\Http\Middleware`
- register it in `App\Http\Kernel` "web" group
- override

**Comment by claudiodekker** [comment]
You should also be able to use the `->withoutMiddleware` flag in Laravel's routes if necessary: https://laravel.com/docs/8.x/middleware#excluding-middleware

**Comment by newmaidumosa** [comment]
> @anditsung inside the class you'll find `handle()` method, which returns an array of your app's shared data. There you need to edit / remove the user section. For example, this is how I eager loaded some relationships:
> 
> ```
> 'user' => function () use ($request) {
>     if (! $request->user()) {
>         return;
>     }
> 
>     if (Jetstream::hasTeamFeatures() && $request->user()) {
>         $request->user()->currentTeam;
>     }
>     return array_merge(
>         $user = $request->user()->load(['courses.pivot.videos', 'courses.labels', 'center'])->toArray(),
>         array_filter([
>         'all_teams' => Jetstream::hasTeamFeatures() ? $user->allTeams() : null,
>     ]), [
>         'two_factor_enabled' => ! is_null($request->user()->two_factor_secret),
>     ]);
> },
> ```

When I do this, it still loads the data from the settings in the vendor folder. Is there anyway to prevent this?

**Comment by anditsung** [comment]
> > @anditsung inside the class you'll find `handle()` method, which returns an array of your app's shared data. There you need to edit / remove the user section. For example, this is how I eager loaded some relationships:
> > ```
> > 'user' => function () use ($request) {
> >     if (! $request->user()) {
> >         return;
> >     }
> > 
> >     if (Jetstream::hasTeamFeatures() && $request->user()) {
> >         $request->user()->currentTeam;
> >     }
> >     return array_merge(
> >         $user = $request->user()->load(['courses.pivot.videos', 'courses.labels', 'center'])->toArray(),
> >         array_filter([
> >         'all_teams' => Jetstream::hasTeamFeatures() ? $user->allTeams() : null,
> >     ]), [
> >         'two_factor_enabled' => ! is_null($request->user()->two_factor_secret),
> >     ]);
> > },
> > ```
> 
> When I do this, it still loads the data from the settings in the vendor folder. Is there anyway to prevent this?

have you add that middleware to kernel.php on middleware folder?

**Comment by michaelhume** [comment]
As a side note you can also control which attributes of your user model are exposed by setting either the `$hidden` or `$visible` properties on your User model. 

ex User.php :

```php

protected $visible = [
        'id', 'name', 'email', 'created_at', 'username', 'profile_photo_url', 'current_team_id', 'currentTeam'
    ];

```

**Comment by moradchalaby** [comment]
> This is actually more of a jetstream question rather than inertiajs. But to answer your question,
> 
> The user data is shared from the ShareInertiaData middleware `{PROJECT_INSTALLATION_FOLDER}\vendor\laravel\jetstream\src\Http\Middleware\ShareInertiaData.php`
> 
> This middleware is added to the web group. You could thus override this middleware with your own custom one indicating what data you'd like to to share. Then go ahead and append your custom middleware to the web group.

thank you master. this works for me
