### ISSUE TITLE
 flock() expects parameter 1 to be resource, boolean given 

### ISSUE THREAD

**Issue by usaikoo** [inertiajs/inertia-laravel#194]
flock() expects parameter 1 to be resource, boolean given in api route. I am testing with three project and i got this same error for api routes. I hope to fix this.

**Comment by claudiodekker** [comment]
Hi,

Unfortunately, this doesn't seem to be Inertia-related as Inertia doesn't use a `flock()` method anywhere.
Nevertheless, I wish you the best of luck solving this issue!
