### ISSUE TITLE
How to preserve current GET url in the browser while making POST request to server in Laravel-8 and InertiaJs

### ISSUE THREAD

**Issue by faisaldeveloper** [inertiajs/inertia-laravel#199]
I am using Inertia JS in Laravel 8, with following POST request to server. The problem is that the browser URL is also updated with POST request, which may be a expected behavior in some cases but I want to keep the actual GET request in the browser despite sending different types of requests to server using multiple Laravel routes.

```
this.$inertia.put(`/task/${task_id}`, {order, category_id});

this.$inertia.visit(`/task/${task_id}`, {
    method: 'put',
    data: {order, category_id},
    only: ['categories', 'msg'],
    replace: true,
    preserveState: true,
    preserveScroll: true,
});
```
Kindly guide me, how I can preserve existing GET URL in the browser while send POST requests to server using Inertia JS?

**Comment by reinink** [comment]
Have you considered using a redirect "back" in your controller? Like this:

```php
// your controller method code
return Redirect::back();
```

Basically when you make a visit with Inertia, the client-side code making the visit doesn't determine where you go next, but rather the server-side code (a redirect). If you really want to control it from the client-side, you could always pass a `redirectToUrl` parameter with your request, and then do a redirect server-side to that page.

I hope that helps! 👍
