### ISSUE TITLE
Root view blade helper

### ISSUE THREAD

**Issue by alexbowers** [inertiajs/inertia-laravel#2]
I feel like anybody who will end up using Inertia will always have to refer to the documentation to get the root `<div>` and it's `data-component` details.

Have you thought about whether an `@inertia` blade action would be worthwhile?

**Comment by sixlive** [comment]
I think a blade helper could be nice. If @reinink doesn't I'd put together a Laravel Preset for Inertia too where we would just publish the view anyway.

**Comment by reinink** [comment]
Yup, a `@inertia` directive is totally the plan.

**Comment by reinink** [comment]
@alexbowers @sixlive If either of you had time to PR an `@inertia` directive addition, I'd be grateful. Thinking it should generate this:

```blade
<div id="app" data-component="{{ $component }}" data-props="{{ json_encode((object) $props) }}"></div>
```

**Comment by alexbowers** [comment]
@reinink PR made https://github.com/inertiajs/inertia-laravel/pull/6

**Comment by sixlive** [comment]
Beat me to it! Was just opening up my laptop to do it haha

**Comment by reinink** [comment]
YOU GUYS ROCK
