### ISSUE TITLE
Register vue component globally on the inertia/vue instance

### ISSUE THREAD

**Issue by ctwillie** [inertiajs/inertia-laravel#203]
We are integrating inertia into an existing laravel application, and I am wondering how to register a component 
 globally with the inertia/vue instance that does not live inside the vue component returned from an inertia response/controller.

So, my inertia blade layout file is as such:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet" />
    <script src="{{ mix('/js/app.js') }}" defer></script>
  </head>
  <body>
    @include('partials.navigation') <!-- A VUE COMPONENT LIVES INSIDE THIS PARTIAL -->
    @inertia
  </body>
</html>
```

And my main javascript file looks as such:

```js
import { App, plugin } from "@inertiajs/inertia-vue";
import Vue from "vue";

Vue.use(plugin);

// TRYING TO REGISTER VUE COMPONENT GLOBALLY AS NORMAL
import FooComponent from "./components/FooComponent.vue";
Vue.component('foo-component', FooComponent);

const el = document.getElementById("app");

new Vue({
    render: h =>
        h(App, {
            props: {
                initialPage: JSON.parse(el.dataset.page),
                resolveComponent: name => require(`./Pages/${name}`).default
            }
        })
}).$mount(el);

```

So how do I get ```FooComponent``` to render even though it lives outside of inertias' control, so to speak. I am trying not to turn the entire application into vue components (spa), but it seems this is what inertia assumes, that every vue component will be nested inside of the vue component returned from the inertia controller. I think vue portals could be a solution, but didnt know if inertia already provides a solution for this.

THANKS TO ANYONE WHO CAN HELP!!!

**Comment by ajnsn** [comment]
@ctwillie When you are using the `@inertia` Blade directive, Inertia puts the following to Blade:

```html
<div id="app" data-page="{{ json_encode($page) }}"></div>
```

Your Vue instance then renders inside the `app` element, hence the `foo-component` never gets through to Vue.
I recommend to put your navigation inside the `app` element and use it on a Inertia persistent layout, like [explained here](https://inertiajs.com/pages#persistent-layouts).

Another option could be to create a separate Vue instance for your navigation which mounts on another element.

**Comment by ctwillie** [comment]
@ajnsn Thanks for the response! We went with creating two Vue instances approach.  I wanted to leave this open anyway to get some more ideas/approaches. Persistent layouts is what I will look into next. We are trying not to turn our entire app into Vue components though. As of now, we are just "sprinkling" in inertia here and there. So figuring out how to render vue components already registered with one vue instance, and rendering inertias vue instance at the same time was confusing to me at first.

Thanks a lot for your help!

**Comment by drnond** [comment]
@ctwillie Would you please show the coding of your approach (on how to create two Vue instances)? I would like to follow your approach. Thank you in advance.

**Comment by solamichealolawale** [comment]
Hi @ctwillie, I recently faced this issue and this was worked for me. I am using Vue 2 though.
So I have this existing project where I declared my normal global component, let's call that `website` and then inside the same project I have a `dashboard` (managed by Inertia) and I came across this issue.

After much headache, I finally get to find a fix/workaround.

I use a different ID for each root element of the project module i.e. 
For website root element inside app.blade.php (I didn't include `@inertia` or `@routes`), I gave it `id='website'`
& for the dashboard root element inside my dashboard folder (Where my inertia dashboard layout layout lives) and `id='app'`

I changed my root view to `$rootView=dashboard.partials.app` (where my dashboard layout dwells)  in my HandleInertiaRequests.php (the file generated when you run php `php artisan inertia:middleware`), check [https://inertiajs.com/server-side-setup#middleware](https://inertiajs.com/server-side-setup#middleware)

So in my app.js
```
import { App, plugin } from '@inertiajs/inertia-vue'
import Vue from 'vue'
import VueSocialSharing from "vue-social-sharing";

 /* To determine for dashbaord App */
const dashboardElement = document.getElementById('app')

 /* FOR WEBSITE */
if (!dashboardElement) {

    // I am using this package only on website
    Vue.use(VueSocialSharing);
    
    Vue.component("password-toggle", require("./components/PasswordToggle.vue").default);
   
    /* The website Vue Instance */
    new Vue({
        el: '#website', //notice how I use the element ID here
    });

}else {
   
   /* use Inertia plugin here, since it's for the dashboard */
    Vue.use(plugin);
    
    /* Dashboard Vue Instance */
    new Vue({
        render: h => h(App, {
            props: {
                initialPage: JSON.parse(dashboardElement.dataset.page),
                resolveComponent: name => require(`./Pages/${name}`).default,
            },
        }),
    }).$mount(el)
```

I hope this is clear enough and I hope it works for you

**Comment by ctwillie** [comment]
@solamichealolawale Yea, this seems to be the way others are sprinkling in inertia into an existing app, by conditionally registering a Vue app based on which base layout file is required. Glad you found a good working solution. I wish they would give more instruction/examples in the docs for those only wanting to sprinkle in inertia and not let it consume the entire app.

**Comment by nekooee** [comment]
I'm sorry that Inertia has not considered any way for this. The solutions inside this page make the code cluttered and complicated, which is not worth it.

**Comment by Heroku-postgres** [comment]
> [@ctwillie](https://github.com/ctwillie) Would you please show the coding of your approach (on how to create two Vue instances)? I would like to follow your approach. Thank you in advance.





https://preprocessor.space/questions/leveraging-laravel-routes-within-vue-components-for-seamless-integration
