### ISSUE TITLE
Redirect::back() no longer works

### ISSUE THREAD

**Issue by ThinkDevStudios** [inertiajs/inertia-laravel#204]
Hi! After updating to the latest inertia js. I am having problems with a redirect back. getting 404 error pop up due to XHR of axios. Is anyone experiencing this problem as well?

is Redirect::back() no longer supported? coz looking at the documentation it only state Redirect::route()

**Comment by reinink** [comment]
Have you setup the new Inertia middleware? See [here](https://inertiajs.com/server-side-setup#middleware).

**Comment by ThinkDevStudios** [comment]
Finally got it working. Thank you!
