### ISSUE TITLE
[Feature request]: Enable transformProps in handleInertiaRequest middleware

### ISSUE THREAD

**Issue by albertpratomo** [inertiajs/inertia-laravel#208]
Conventionally, Laravel (PHP) uses `snake_case` for it's model attributes, while Vue (JS) uses `camelCase` for its attributes.

By default the `props` passed by Inertia to the Vue page component will be in `snake_case`. To make it `camelCase`, I can use [`transformProps`](https://inertiajs.com/transforming-props#top) in the main `app.js`.

But there is a weakness to do the `transformProps` in client side. When using the form helper (`$inertia.form()`), it's `errors` object are still in `snake_case`. I suppose this is because the `form.errors` is not part of props of the Vue component.

Therefore I would like to request a way to `transformProps` in the Laravel side, preferably in the `handleInertiaRequest` middleware. 

Thanks before..

**Comment by ajnsn** [comment]
@albertpratomo Typically you are defining the root props in each of your Inertia's [responses](https://inertiajs.com/responses). You can easily define a camelCase prop like so:

```php
return Inertia::render('Event/Show', [
    'myVueProp' => $event->only('id', 'title', 'start_date', 'description'),
]);
````
The `start_date` is inside the `myVueProp` object. It does not need to be changed except cosmetic reasons?

If you want to transform all of your model attribute to camelCase, you could look at these [Collection macros](https://github.com/laravel/ideas/issues/186#issuecomment-513453369), look at [this library](https://github.com/kirkbushell/eloquence) or override the `toArray()` or `getAttribute()` and `setAttribute()` method on your models.

**Comment by albertpratomo** [comment]
Yeah or I can use `JSON resource` to serialize my models..

**Comment by claudiodekker** [comment]
Hey all,

Given that we've removed the `transformProps` functionality altogether (https://github.com/inertiajs/inertia/pull/693), this issue no longer applies, so I'll be closing this issue now.

**Comment by mohkoma** [comment]
This can be bit late 😅!
I made a small package that can allow you to transform your props before you receive them in your page component,
It's a good replacement for the old `transformProps` functionality 🎉.
It gives you also the possibility to hydrate your prop to typescript model/class.
https://github.com/mohkoma/inertiajs-transform-props

```
props: {
      comment: {
          type: String,
          required: true,
          transform: (comment) => new Comment(comment)
      },
      title: {
           type: String,
           required: true,
           transform: (title) => title. toLowerCase()
      },
      description: {
          type: String,
          required: true,
          transform: 'Anything'
      },
  }
```
