### ISSUE TITLE
Innertia response data conflict with global sharing

### ISSUE THREAD

**Issue by donmbelembe** [inertiajs/inertia-laravel#209]
In `app\Http\Middleware\HandleInertiaRequests.php` I'm sharing the current tenant like this, 
```
public function share(Request $request)
{
        return array_merge(parent::share($request), [
            'tenant' => tenant()
        ]);
}
```

**_tenant_** should be `null` if browsing from the central domain

Now I have a show tenant page accessible only from the central domain like this

```
public function show(Tenant $tenant)
    {
        return Inertia::render('Tenants/Show', [
            'tenant' => $tenant
        ]);
    }
```

Since I'm using Vue adapter, what I'm expecting is that we should have 
`$page.props.tenant = null` and `tenant` props inside the Show.vue page should have the data from the controller, but unfortunately `$page.props.tenant ` is also getting the same data from the controller

**Comment by ajnsn** [comment]
@donmbelembe A prop only exists once. In the Vue adapter, the value of `$page.props.tenant` is equal to your defined `tenant` in your component `props`. There's no direct method to only access shared props.

In the response of the Laravel adapter the [shared props are merged with the component props](https://github.com/inertiajs/inertia-laravel/blob/726b1e0d4fc399089dd29820a78e40d1c9aad2eb/src/ResponseFactory.php#L70) which means the component props takes precedence.

**Comment by claudiodekker** [comment]
Thanks for helping out here @ajnsn! 👍

**Comment by sandcore-dev** [comment]
> In the response of the Laravel adapter the [shared props are merged with the component props](https://github.com/inertiajs/inertia-laravel/blob/726b1e0d4fc399089dd29820a78e40d1c9aad2eb/src/ResponseFactory.php#L70) which means the component props take precedence.

I'm experiencing a similar problem.

If shared data goes like this:
```php
['foo' => ['bar' => 1]]
```
and you want to do this in your controller:
```php
return Inertia::render(['foo' => ['baz' => 2]]);
```
then the shared `foo` array will be replaced by the local `foo` array. 

I would like to be able to modify this behavior, perhaps with an extra (optional) parameter to `ResponseFactory::render` so that `array_merge_recursive($this->sharedProps, $props)` will be used instead of `array_merge($this->sharedProps, $props)`.
