### ISSUE TITLE
Best possible way how to transform laravel authentication to inertia

### ISSUE THREAD

**Issue by steveljko** [inertiajs/inertia-laravel#21]
What would be the best way to transform original Laravel authentication to Inertia?

I saw PingCRM demo, but I can't get authentication working well like one in PingCRM...

Thanks for helping!

**Comment by reinink** [comment]
Other than converting the login form template to Vue/React, there isn't really anything special required. The default session auth in Laravel works really well with Inertia out of the box.

You'll need to update the `LoginController` to return an Inertia response for the login page:

```php
public function showLoginForm()
{
    return Inertia::render('Auth/Login');
}
```

The `Login.vue` example in the PingCRM demo app is a great reference for how to create the login page and form. See [here](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Auth/Login.vue).

Good luck!
