### ISSUE TITLE
Is Inertia support use case for not using Model in Laravel?

### ISSUE THREAD

**Issue by wingfranky** [inertiajs/inertia-laravel#212]
Thanks for the idea and I would really love to adopt this into my existing development. I can see that it can simplify the effort for full stack developer. 

I would like to check if Inertia support the use case for not using Model in Laravel. In our use case, we have custom library and external API handling the database rather than using the Model in Laravel (i.e. the Controller will call other function). I already has adopted React, Redux in the frontend side as Single Page Application. The Laravel side output JSON via response()->json() , and use $id, Request $request for input. 
e.g. 
public function update(Request $request, string $id): JsonResponse
....
 return response()->json($result)
....

From the document and PingCMS source code, it seems that Inertia must use Model in Laravel for input? 
e.g. 
public function update(Contact $contact)

Is Inertia support this kind of use? Thanks.

**Comment by ajnsn** [comment]
@wingfranky You can pass any data to `Inertia::render`. More options like lazy loading can [be found here](https://inertiajs.com/partial-reloads#lazy-data-evaluation). You cannot return a `json` response though. Hope this helps :)

**Comment by reinink** [comment]
So, there is nothing stopping you from using modals in Inertia.js. I do it all the time. The hard part is simply having modals that have their own history that. That's a bit tricker, and something we want to solve eventually. See Inertia.js, see [here](https://github.com/inertiajs/inertia/discussions/249).

I'll often create modals that have forms, that submit using Inertia, and then redirect elsewhere. It works very well.
