### ISSUE TITLE
setRootView not working in service provider

### ISSUE THREAD

**Issue by SamuelNitsche** [inertiajs/inertia-laravel#217]
I try to use a custom blade file for my root view and in previous projects I was able to call `Inertia::setRootView()` from my `AppServiceProvider`.
In the latest version of inertia there is an exception telling me that the `app` view could not be found.
When I call `Inertia::setRootView()` in my controller, before calling `Inertia::render()`, everything works fine.

Am I doing something wrong or is this a bug?

**Comment by SamuelNitsche** [comment]
Hmm, looks like this functionality moved to the middleware. Can you please update the documentation for this? (https://inertiajs.com/server-side-setup#root-template)

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
