### ISSUE TITLE
Question: How do I prevent an <inertia-link> from navigating

### ISSUE THREAD

**Issue by seewhy17** [inertiajs/inertia-laravel#218]
Essentially what I want is this effect: a dummy link that goes nowhere but instead triggers a drop down.
```
<a>Company</a>
```
but using :
```
<inertia-link>Company</inertia-link>
```
 adds ```undefined``` to the get request which in a 404

I also noticed I cannot add Vue events to it any way around these issues?

**Comment by reinink** [comment]
I'd recommend not using an Inertia link this situation, but rather just a plain button or link. If you're preventing the default Inertia link behaviour, there really is no point in using it.
