### ISSUE TITLE
Using Inertia and Blade in the same projet ?

### ISSUE THREAD

**Issue by anothersailor** [inertiajs/inertia-laravel#219]
Is there a way to use Laravel Blade for one part of a multipage site (e-commerce), and Inertia/Vue for some specific pages (like the basket and the admin pages)? Not mixing the two on the same pages, I mean.

The first category is a load of pages that are merely static, need fast loading and robust SEO referencing (product pages and catalogues). The second do not need to be indexed, but need a lot of user interactions.

Many thanks,
E.

**Comment by reinink** [comment]
Yeah, you can totally use both Inertia.js and regular Blade templates in the same project. Just be careful though to use regular `<a>` links when linking to Blade files, as Inertia is unable to do an XHR visit to a Blade endpoint. It would end up showing it in a modal. And the same goes for visiting an Inertia page from a Blade endpoint.

Point is though, you can totally mix. I sometimes do this myself. I have Blade files for the public site of the site (where SEO matters), and I'll use Inertia for the secure part of the site, for the app/control panel. 👍

**Comment by Ulrich15** [comment]
> Yeah, you can totally use both Inertia.js and regular Blade templates in the same project. Just be careful though to use regular `<a>` links when linking to Blade files, as Inertia is unable to do an XHR visit to a Blade endpoint. It would end up showing it in a modal. And the same goes for visiting an Inertia page from a Blade endpoint.
> 
> Point is though, you can totally mix. I sometimes do this myself. I have Blade files for the public site of the site (where SEO matters), and I'll use Inertia for the secure part of the site, for the app/control panel. 👍

Morning,

And what about the client-side main js file ?, it's a separate file, one for inertia and one for pure blade ? or only one file for both?. Thanks

**Comment by anothersailor** [comment]
Not sure what you call the main js file...
The way I did it is by importing Inertia and creating the InertiaApp in app.js:

```
createInertiaApp({
    resolve: name => import(`./Pages/${name}`),
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(i18n)
            .mount(el)
    },
})
```

Then the route to the view that uses Vue calls the inertia middleware with the target PHP template as an argument (product.index in this case):
```
    Route::get("/$shop_name/products", 'App\Http\Controllers\ProductController@index')
        // Call inertia middleware and pass it the custom Blade RootView
        ->middleware('inertia:product.index')
        ->name("product.index");
```

And the controller that is called by the route, calls the Vue template (ProductSelectionVue3):
```
return Inertia::render('ProductSelectionVue3', $parameters_for_vue)->withViewData(['viewData' => $parameters_for_blade]);
```

It works, but this is my first time, so you may find better with somebody else... One open question for me for example, is if you use Vue in another page, do you create a second Vue app, or do you reuse the same. I believe the first, but I'd have to look at my notes to see how.

Cheers,
E.
