### ISSUE TITLE
setRootView returns blank page on Admin view

### ISSUE THREAD

**Issue by nfunwigabga** [inertiajs/inertia-laravel#22]
My app contains two views - a frontend and a backend with different layouts. The `resources/js` folder also has 2 different Vue instances - one for frontend and one for backend. I have the frontend rendering Inertia components and pages just fine, but when I try to implement the same in the backend, I get a blank page with empty HTML tags. This is my setup:

```php
/* in AppServiceProvider */
public function register()
{
    // dynamically set the rootview based on whether the route is backend or frontend 
    // can also be done in a middleware that wraps all admin routes
    if(request()->is('admin/*')){
        Inertia::setRootView('admin.app');
    } else {
        Inertia::setRootView('frontend.app');
    }
    ....
}
```
In my `resources/views` I have a `frontend/app.blade.php` file with the `@inertia` helper, which works great and renders the Vue components as expected. But the same setup in `admin/app.blade.php` returns a blank page, does not even render the metatags or the style and script tags on the page talk less of content. But the `setRootView` seems to work because when I pass in a view name that does not exist, I get an error. So I suppose it is reading the appropriate view file but not rendering anything.

Not sure what I am doing wrong.

**Comment by nfunwigabga** [comment]
This was totally my error. I forgot to `return` the view in my controller `return Inertia::render()`.

**Comment by Neophen** [comment]
@nfunwigabga did you get this working?

**Comment by jxclsv** [comment]
`
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class FrontendDashboardBaseController extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function __construct()
    {
        \Inertia\Inertia::setRootView('layouts.dashboard');
    }
}
`

I tried this method creating separate base controllers and inserting constructor for inertia default root view.

> @nfunwigabga did you get this working?

**Comment by anothersailor** [comment]
Hi there !
I am trying to achieve exactly the same thing with Laravel 8: one Instance & Blade layout for the public site, another two for the admin site.

Two questions: 
1. When calling the page, the "AppServiceProvider" is not called, so register() is not called either. Did you do something special there ?
2. How do you scaffold your /resources/ folder to allow 2 Vue instances to live together:
    - /resources/js/backend/, /resources/js/frontend/, /resources/views/backend/, /resources/views/frontend/
    - Something else ?

Many thanks,
E.
