### ISSUE TITLE
[Testing] Support for suffixed page files (Auth/LoginPage.vue but used as Auth/Login)

### ISSUE THREAD

**Issue by johanvanhelden** [inertiajs/inertia-laravel#221]
I love the fact that, thanks to @claudiodekker , we can now test Inertia out of the box.
But I would love to see support for suffixed components.

For example, this is my controller:
```php
public function index(): Response
{
    return Inertia::render('Dashboard/Index');
}
```

But my Vue file is actually called `IndexPage.vue`.
The `Page` part is suffixed in my main.js file like this:

```js
resolveComponent: (page) => files(`./pages/${page}Page.vue`).default,
```

Unfortunatly I now have to disable the detection of the filesystem because I can not get the tests to pass.
Because if I use `Dashboard/IndexPage` in the test, it fails because:
```bash
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Auth/LoginPage'
+'Auth/Login'
``` 
and if I assert  `Dashboard/Index` it fails because `Inertia page component file [Dashboard/Index] does not exist.`

I would propose a new config option:
`page_suffix` which, by default, is `null` but if  it has the value `"Page"`, on the filesystem, it will look for `{Name}Page.vue`

**Comment by claudiodekker** [comment]
Hmm.. interesting, this means we'll need to add a `resolveComponent`-like method on the back-end that you can then 'rebind' yourself if needed, which isn't a bad idea.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
