### ISSUE TITLE
JSON Request option?

### ISSUE THREAD

**Issue by dangerdan** [inertiajs/inertia-laravel#223]
It would be nice for Inertia to understand JSON requests. I'm using this to help make modal windows work in a cleaner way (by not mixing concerns in unrelated controllers). I've got code similar to below in a helper function, it'd be cool if the framework did this out of the box!

Apologies if I've missed a way in which this can already be done.

```
function renderJsonOrInertia($component, $data) {
        if (Request::hasHeader('X-Inertia') == false && Request::expectsJson()) {
            return response()->json($data);
        }

        return Inertia::render($component, $data);
}
```

**Comment by reinink** [comment]
Hello @dangerdan, thanks for your interest in Inertia.js.

Because of how the Inertia client-side routing works, it's not possible to support both Inertia responses and plain JSON responses.

If you'd like to make a standard XHR requests, simply use XHR directly, or via a library like axios, or even fetch.

The docs have a note about this: https://inertiajs.com/forms#classic-xhr-submits

**Comment by dangerdan** [comment]
Thanks for the reply @reinink. I am actually using the method outline above so make XHR requests to Inertia routes that then provide plain json via "response()->json", this saves me duplicating controller calls to return the same data when I need to manipulate it for models etc outside of the client-side Inertia JS. Just thought this would be a useful approach to share to reduce code duplication for those that need raw access to the same data Inertia controller methods provide.

**Comment by Benoit1980** [comment]
I have the exact same problem and no one found a solution on this:

Versions:
 "inertiajs/inertia-laravel": "^0.3.5",
    "@inertiajs/inertia": "^0.8.4",
    "@inertiajs/inertia-vue3": "^0.3.5",
    "@inertiajs/progress": "^0.2.4",

Steps to reproduce:
```
    axios.get('/test-connection')
                .then(response => {
                    this.TestConnection = response.data;
                })
```

Response is a json object from Laravel:
`return response()->json($data);`


The response is always returning { "cookies": {}, "transferStats": {} }, I am not the only people with this issue, others on Laracast experience this too.

Tried everything I could, I cannot get a normal response in Json with Axios when Intertia is installed. Any hints please?
