### ISSUE TITLE
Can't give vue app instance

### ISSUE THREAD

**Issue by t3946** [inertiajs/inertia-laravel#228]
app.js
`require( './bootstrap' );
require( './main' );

// Import modules...
import {createApp, h} from 'vue';
import {App as InertiaApp, plugin as InertiaPlugin} from '@inertiajs/inertia-vue3';
import {InertiaProgress} from '@inertiajs/progress';
import 'popper.js';
import 'bootstrap';

const el = document.getElementById( 'app' );

// include font awesome
import { library } from '@fortawesome/fontawesome-svg-core';
import { faUserSecret } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
library.add( faUserSecret )
//InertiaApp has not component method
InertiaApp.component('font-awesome-icon', FontAwesomeIcon);

createApp({
    render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => require(`./Pages/${name}`).default,
        }),
})
    .mixin({methods: {route}})
    .use(InertiaPlugin)
    .mount(el);

InertiaProgress.init( { color: '#4B5563' } );
`

I have a problem with the Font Awsome library. To do this, you need to enable the global component. Usually vue does it like App.component ('my-component', MyComponent); where MyComponent is a VueComponent instance. But InertiaApp doesn't have a component method to include vue global components. How can I include global vue component?

**Comment by muarachmann** [comment]
inertia is not responsible for this. Please refer to the [docs](https://v3.vuejs.org/guide/component-registration.html) 

```
const app = createApp({
       render: () =>
            h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => require(./Pages/${name}).default,
       }),
  })
.mixin({methods: {route}})
.use(InertiaPlugin)
.mount(el);

app.component('font-awesome-icon', FontAwesomeIcon);  // global registration of font awesome
```

**Comment by reinink** [comment]
@muarachmann Thanks for your help here. 👍
