### ISSUE TITLE
error when using a custom port

### ISSUE THREAD

**Issue by philippkuehn** [inertiajs/inertia-laravel#23]
Hey, when using a custom port for local development this seems to be a problem. I'm running my app at `localhost:3000`. I created two routes `/test` and `/test2` but whenever I go to another route with `<inertia-link />` I will get this error in my console:

```
Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://localhost/test2' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/test'.
    at Object.setState (webpack-internal:///./node_modules/inertia/src/inertia.js:124:59)
    at eval (webpack-internal:///./node_modules/inertia/src/inertia.js:93:14)
```

It seems that my port is lost here: https://github.com/inertiajs/inertia-laravel/blob/master/src/Component.php#L59. Changing `Request::fullUrl()` to `Request::path()` does the trick for me but I'm not sure if this will cause any other problems.

**Comment by reinink** [comment]
> but I'm not sure if this will cause any other problems.

Unfortunately it will. You'll have a new history state pushed for every page visit, even if it's the same page, or it's a "replace" visit. This is because the full URL is used to check this.

That said, I've already been considering switching to just the path and query strings, because this isn't the first time we've run into issues with the domain.

**Comment by reinink** [comment]
I've updated Inertia (https://github.com/inertiajs/inertia/commit/1fcf3e513b5239d084378874f8373be27724ed6f) to only use the path and query strings, and have removed the domain requirement entirely. You'll need update all your Inertia dependencies.

**Comment by philippkuehn** [comment]
thank you!
