### ISSUE TITLE
Debugbar doesn't show

### ISSUE THREAD

**Issue by stygiansabyss** [inertiajs/inertia-laravel#230]
I love using inertiajs, but when I do the barryvdh/laravel-debugbar doesn't show on the bottom of the page anymore.  Does anyone know a way to make it show up again?

Thanks!

**Comment by reinink** [comment]
Hey there! So, I am able to use the `barryvdh/laravel-debugbar` without issue in my Inertia.js apps, and there aren't any known issues here. So, without more code/information, this is going to be very hard to diagnose for you. I suspect this has something more to do with how you have the Laravel Debugbar setup, than it does with Inertia.js. I'd recommend reaching out to the maintainers of that package for help. Good luck. 👍
