### ISSUE TITLE
Modifying default user prop value

### ISSUE THREAD

**Issue by andreliem** [inertiajs/inertia-laravel#233]
I may have missed this in the documentation, but I can't figure out how to modify the user object that is defined in `initialPage->props->user`? I wanted to add in a few more relationships but wasn't sure where in the code the user data is passed to the initialPage props.

**Comment by piljac1** [comment]
Perhaps this is what you're looking for: https://inertiajs.com/shared-data

**Comment by andreliem** [comment]
Thanks @piljac1. That's useful! 

Although I'm still not sure where the `initialPage` props is being set with my app as I want to extend the data that is being loaded into the user prop. I thought it came built into the app setup, but maybe I added it or it's part of Jetstream

**Comment by andreliem** [comment]
And I just confirmed it's because of JetStream.

It has a Middleware `ShareInertiaData` that was being loaded in.
