### ISSUE TITLE
[Feature request]: Allow for missing filtering

### ISSUE THREAD

**Issue by eithed** [inertiajs/inertia-laravel#235]
Consider a response that shouldn't contain an element of certain format, ie

```
{
   data: {
      fields: [{ id: 'foo'}]
   }
}
```

is ok, but

```
{
   data: {
      fields: [{id: 'bar'}]
   }
}
```

or 

```
{
   data: {
      fields: [{id: 'foo'}, {id: 'bar'}]
   }
}
```

is not (element with id: bar shouldn't be present)

Currently from looking over the documentation I can't find how one would create such assertion, as I cannot target specific node within `fields` for missingness.

A possible workaround is to do:

```
$response->assertJson(function (AssertableJson $json) {
   $json->where('data.fields', function($field){
      return !$field->pluck('id')->contains('bar');
   });
})
```

However, as with previous feature request, this makes further filtering awkward (ie I want to assert that given json fragment doesn't contain element with id foo and option that contains xyz).

Thinking about it, syntax of:

```
$response->assertJson(function (AssertableJson $json) {
   $json->missing('data.fields.*', function(AssertableJson $json){
      $json->where('id', 'bar');
   });
})
```

or 

```
$response->assertJson(function (AssertableJson $json) {
   $json->missingAny('data.fields', function(AssertableJson $json){
      $json->where('id', 'bar');
   });
})
```

is intuitive, but also elevates `missing` to the same level as `has` in terms of scoping.

**Comment by crnkovic** [comment]
This is unrelated to Inertia as it just uses Laravel's testing tooling. If you can test it in Laravel, you can test it "here".

Also, looks like you can do this now: https://laravel.com/docs/9.x/http-tests#fluent-json-testing. There are methods like `whereNot` that may help you out -- not sure which of these methods where there when you submitted an issue.

@eithed make sure to close the issue if this has been resolved.

**Comment by eithed** [comment]
@crnkovic TBH I don't remember as it was some time ago.

Yes, I'm using fluent json testing in Laravel; if such feature existed in Inertia I'd be able to use it in my tests in Laravel. I'd assumed this is the correct library to request the feature in. If you think that's not correct, feel free to close.

The issue here will be that `whereNot` only targets the "current" node that we're testing - ie, for the provided json I'd have to do:

```
$response->assertJson(function (AssertableJson $json) {
   $json->whereNot('data.fields.0.id', 'bar');
})
```

(and then do the same for all the `data.fields.**x**`). So, afaik there's currently no way to test for missingness of element that has specific property

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
