### ISSUE TITLE
Vue dev toolbar not working

### ISSUE THREAD

**Issue by andreas83** [inertiajs/inertia-laravel#240]
Not 100% sure if its a inertia related topic, but for some reasons the vue developer toolbar is not recognizing jetstream + inertia app as a vue application. 

any hints are highly appreciated.

**Comment by claudiodekker** [comment]
Hmm, strange.. I can tell you for sure that that's definitely not Inertia-related, as we use the dev tools all the time.

Are you perhaps using the wrong version of the Vue dev tools? In my experience, the ones for Vue 3 don't work for Vue 2 and vice-versa.

**Comment by andreas83** [comment]
i installed the vue dev tools **beta**, and it works again:
vue dev tools beta:
https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg/related?hl=en

vue dev tools - version 5.3.4 (not working for me)
https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en
