### ISSUE TITLE
Laravel Spark Billing page error in Jetstream with Inertia

### ISSUE THREAD

**Issue by pascut** [inertiajs/inertia-laravel#241]
I have installed Laravel 8 with Jetstream based on Inertia Js.

Later I installed Laravel Spark (New Spark) and it created a new route: "billing". When I access this route directly in browser it works.

But when I added the route in menu and I click the menu link I receive the following error:

`Uncaught (in promise) Error: Cannot find module './BillingPortal'`

The code used:

```
<jet-dropdown-link href="/billing">
    Billing
</jet-dropdown-link>
```

I also tried:

```
<jet-dropdown-link :href="route('spark.portal')">
    Billing
</jet-dropdown-link>
```

If for example I use:

```
<a href="/billing">
    Billing
</a>
```

The design is bad, but the billing page works well.

I tried to clear the routes, the config, I ran the command: npm run dev

Any advice regarding what I am doing wrong and how can I fix it? Thank you.

**Comment by pascut** [comment]
I found a combined answer.

I used the a href, but the inertia classes:

```
    <a href="/billing" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">
        Billing
    </a>
```

It seems that Inertia was looking for a custom module and using a href allow us to skip adding this functionality.

**Comment by claudiodekker** [comment]
Hi,

So, your fix essentially disables SPA-mode entirely, as you then just make a normal visit.

Internally, here's what's happening:
1. Inertia calls the back-end on `/billing`
2. Inertia's `Inertia::render('BillingPortal', ...)` sends an Inertia response
3. The Inertia request (on the front-end) receives this response, and sees it needs to load the `BillingPortal` component.
4. Inertia uses [the `resolveComponent` callback](https://inertiajs.com/client-side-setup#initialize-app) to load that Vue component
5. Inertia switches out the pages, showing you the BillingPortal page.

Unfortunately, though, that error is very typical for when step 4 fails. This means that for some reason, it can't find the `BillingPortal.vue` file.

To fix this properly, I recommend looking at where your `BillingPortal.vue` file is located, and to either move it to a place that Inertia can reach, or modify the `resolveComponent` callback so it can load it for you.

Hope this helps!
