### ISSUE TITLE
v-model not working

### ISSUE THREAD

**Issue by RomkaLTU** [inertiajs/inertia-laravel#242]
I have a simple input component:

```
<app-input id="name" type="text" v-model="form.name" required />
```

And here is data of parent component:

```
data() {
        return {
            form: this.$inertia.form({
                name: 'Jack Doe',
                email: '',
                phone: '867777777',
                address1: '',
                address2: '',
                postalCode: '',
                city: '',
                country: '',
                workHours: '',
                agreeTos: false,
            })
        }
    },
```

"name", "phone" not setting up
if I use simple object instead everything is working fine:

```
data() {
        return {
            form: {
                name: 'Jack Doe',
                email: '',
                phone: '867777777',
                address1: '',
                address2: '',
                postalCode: '',
                city: '',
                country: '',
                workHours: '',
                agreeTos: false,
            }
        }
    },
```

It's actually working when navigating between routes, when components re-renders, **but not right after refresh**.

**Comment by RomkaLTU** [comment]
Ok, I don't know why, but I need to set all initial values when mounted()

```
mounted() {
    this.form.name = 'Jack Doe'
    this.form.email = 'jack@example.com'
    ...
 }
```

**Comment by reinink** [comment]
You might need to update to the latest versions of `inertia` and `inertia-vue`/`inertia-vue3`, as there were a couple bugs with the form helpers in the latest release.

If, after you updated to the latest versions, and you still have issues, please report back. I'm going to close this issue in the meantime. 👍
