### ISSUE TITLE
clean errors - persisten layouts

### ISSUE THREAD

**Issue by edwingromero** [inertiajs/inertia-laravel#243]
I am using Persistent layouts.
How do I clean the props errors from a method?

I want to clear the error messages in validation.
I only use 1 modal to create and update data. Then it happens that the errors of creating remain at the time of opening update

![image](https://user-images.githubusercontent.com/4934593/113376874-652f9180-9338-11eb-9933-7f53a3eac3f5.png)

**Comment by reinink** [comment]
You cannot modify props in Vue/React/Svelte. As suggested, when doing this, use some local state, and then clear that.

However, in my experience, I generally never do this. When there are errors, I render them. To clear errors, submit the form again, and if there are no errors, the prop will automatically update.

Alternatively, use the Inertia [form helper](https://inertiajs.com/forms#form-helper), which has a `form.clearErrors()` method. 👍

**Comment by edwingromero** [comment]
What I want is to clean the errors when opening the modal for the second time

https://user-images.githubusercontent.com/4934593/113523856-3ac81900-9570-11eb-8662-08cf00469a7b.mp4

**Comment by reinink** [comment]
Definitely check out the  form helper. It allows you to do this.
