### ISSUE TITLE
how to measure page request load time (performance)?

### ISSUE THREAD

**Issue by fardiansyah-bioelite** [inertiajs/inertia-laravel#248]
Hi, 
i need to measure page load performance. since inertiajs is more like SPA, we can't do server side render time after index page loaded. i just wondering is there a way to do this in inertiajs app?to measure how long the time between page routes/requests.

**Comment by pimski** [comment]
To measure the time spent on the server I use laravel laravel-debugbar. Or you can use the Network tab in chrome devtools.

To measure the actual page rendering time (in my Vue application) I use a custom piece of code on the layout that watches for changes in de $page object. Wrote a post about it here:
https://pimveelders.nl/posts/2021-03-05-measuring-front-end-render-times-in-inertia-and-vue

You need to use a persistent layout, else it won't work.

**Comment by reinink** [comment]
Thanks for helping here @pimski. 👏
