### ISSUE TITLE
Add the ability to call Inertia::share() with only a callback

### ISSUE THREAD

**Issue by reinink** [inertiajs/inertia-laravel#25]
Instead of calling Inertia::share() many times for each piece of data:

```php
Inertia::share('app.name', Config::get('app.name'));
Inertia::share('flash', function () {...});
Inertia::share('errors', function () {...});
Inertia::share('auth.user', function () {...});
```

It would be nice to define this in a single callback:

```php
Inertia::share(function () {
    return [
        'flash' => [
            'success' => Session::get('success'),
        ],
        'errors' => Session::get('errors') ? Session::get('errors')->getBag('default')->getMessages() : (object) [],
        'auth' => [
            'user' => Auth::user() ? [
                'id' => Auth::user()->id,
                'first_name' => Auth::user()->first_name,
                'last_name' => Auth::user()->last_name,
                'email' => Auth::user()->email,
            ] : null
        ],
    ];
});
```

**Comment by codeitlikemiley** [comment]
HI @reinink  , is there a way we can cache the Auth User ?
its really a bummer since on my share im using spatie permissions
and it has around 54 permissions and 3  roles
that is loaded everytime the page loads or redirect to other page

can you show an elegant way to handle

**Comment by reinink** [comment]
I wouldn't include all these permissions on page load (as shared data), personally. I'd include the necessary permissions for each individual page with those responses.

**Comment by codeitlikemiley** [comment]
Is there a way we can do something like on view composer in laravel
where in for example on layout , or sidebar we can specifically put a Inertia::share 
data?
