### ISSUE TITLE
Uncaught (in promise) TypeError: parent is null

### ISSUE THREAD

**Issue by pascut** [inertiajs/inertia-laravel#254]
I am using Laravel 8, with Jetstream & Inertia JS.

I replicated the following tutorial:

https://www.itsolutionstuff.com/post/laravel-8-inertia-js-crud-with-jetstream-tailwind-cssexample.html

When I insert or update I receive the following error: **Uncaught (in promise) TypeError: parent is null**

The error location is this line:

`parent.insertBefore(child, anchor || null);`

Which I understand that is part of Vue Js 3.

I found a similar question here: https://laracasts.com/discuss/channels/general-discussion/inertiajs-vue-error but the solution is not clear. Someone said that he/she forgot to add the @ symbol. But where and why should the @ be added?

**Comment by kbellpostman** [comment]
Has something todo with scoped slots. 

https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

I solved it by binding the form and data variables. Cost me 5 hours trying virtually everything grrrr... 

![image](https://user-images.githubusercontent.com/60920059/115976561-81a59f00-a56f-11eb-934c-479269b92b1e.png)

**Comment by caveman86** [comment]
> 
> 
> Has something todo with scoped slots.
> 
> https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots
> 
> I solved it by binding the form and data variables. Cost me 5 hours trying virtually everything grrrr...
> 
> ![image](https://user-images.githubusercontent.com/60920059/115976561-81a59f00-a56f-11eb-934c-479269b92b1e.png)

thank you very much bro , you have made my day .. 
but even I understand the scoped slot , I still didn't understand why it gives the error after second click on the create or edit button  ?
I mean : while we are handling the "data" in same place at parent , why we must use scoped slot and binding the "form" and "data" ? 
thanks for @pascutand for you @kbellpostman  again ..

**Comment by kbellpostman** [comment]
Well... not sure if this is on purpose or just bad practice. But the lack of reactiveness is also happening inside the prebuild Jetstream functionalities loading inside the app-layout. Apparently it's not a problem for their use cases.

I also noticed that if I would first delete an item... somehow suddenly everything would work like charm. So somehow the delete would trigger reactivity. Anyway, don't like the fix but I lost a whole Saturday on it so I'll take it ;)

**Comment by caveman86** [comment]
still didn't understand  .. but thanks anyway :)

**Comment by kbellpostman** [comment]
I think it's a VUE thing ;)

**Comment by reinink** [comment]
> I think it's a VUE thing ;)

Glad you got it figured out. Closing this as it doesn't sound related to the Inertia Laravel adapter. 👍

**Comment by futurewebsites** [comment]
Removing <app-layout> from your template also fixes the issue and importing your layout in your script section

`<script>
import AppLayout from '@/Layouts/AppLayout'

export default {
    components: {
        AppLayout,
    },
    layout: AppLayout,
}
</script>`

**Comment by sohaibilyas** [comment]
> Removing < app-layout > from your template also fixes the issue and importing your layout in your script section
> 
> ```
> import AppLayout from '@/Layouts/AppLayout'
> 
> export default {
>     components: {
>         AppLayout,
>     },
>     layout: AppLayout,
> }
> </script>```
> ```

@futurewebsites thank you so much, v-bind thing didnt work for me,  in-script layout worked but one thing; header slot is not working anymore, is there a diff approach to set header while using in-script layout?

**Comment by kbellpostman** [comment]
@sohaibilyas Wrap your whole component in an additional div. 

```
<template>
  <div>
      <AppLayout>.....
  </div>
</template>
```
