### ISSUE TITLE
Not able to download a file from Controller (file sent through form)

### ISSUE THREAD

**Issue by jotajotaramos** [inertiajs/inertia-laravel#255]
Hello:

I have just sent a form (that contains an input file) from Inertia to a Laravel's controller.
It is a CSV file.

I need to treat the file in the Laravel's controller and then download it, but the file won't download. Instead, the content of the file is showing in the modal.

I have seen another issues that solve this problem changing the inertia links for <a>.
I understand that inertia is waiting for an Inertia's response, but in this case I am not calling the route through a link but from a form.

Thanks for you help.

My best regards.

**Comment by muarachmann** [comment]
@jotajotaramos sending via inertia necessitates you must return a valid inertia response. It wont work that way. Either you use ajax or axios for your request.

**Comment by claudiodekker** [comment]
Thanks @muarachmann
