### ISSUE TITLE
Is it remember query string is deprecated?? 

### ISSUE THREAD

**Issue by HlaingMinThan** [inertiajs/inertia-laravel#260]

**Comment by HlaingMinThan** [comment]
i'm inertia beginner user.i test ping app and i see query string is remember on url with searched pagination results.
but in my own app it's not working like that. Is it remember query string is deprecated?? or i understand wrong way??
pls help

**Comment by reinink** [comment]
This is done using my [Remember Query Strings](https://github.com/reinink/remember-query-strings) library, which is also used by Ping CRM. Follow the instructions on that repo to get it setup in your own app. 👍

**Comment by HlaingMinThan** [comment]
oops thanks <3 i thought that was inertia default package
