### ISSUE TITLE
Upgrading with Jetstream

### ISSUE THREAD

**Issue by kenrowland** [inertiajs/inertia-laravel#266]
Question, is it OK to upgrade the version of inertiajs/inertia-laravel in my top level composer.json for my laravel app outside of the current version of Jetstream I am using? There are new testing features available in the latest version that I would like to use, but Jetstream has a dependency set to "^0.3". 

I don't see any upgrade guides for this package.

Thanks.

**Comment by Juhlinus** [comment]
@kenrowland How to upgrade inertia-laravel is covered here:
https://inertiajs.com/releases/inertia-laravel-0.4.0-2021-03-02

Also, be aware that a config can be published, as of version `0.4.0`.
https://github.com/inertiajs/inertia-laravel/blob/master/config/inertia.php

**Comment by claudiodekker** [comment]
Hey @kenrowland, yes, it's absolutely OK to update your Jetstream application separately. 
Jetstream only serves as a way to set up a starting point for your application, it does not handle updates / upgrades.

(Thanks @Juhlinus 👍)
