### ISSUE TITLE
Float props are rendered as integers

### ISSUE THREAD

**Issue by Livijn** [inertiajs/inertia-laravel#267]
It seems that when I try to test this array it fails due to rounding issues. Is there a better way of solving this than my current solution?

```php
    public static function averagePrices(): array
    {
        // This is a mock to reveal the problem
        return [
            'average_price' => 6560.0
        ];
    }

    // Works:
    $response->assertInertia(fn (Assert $page) => $page
        ->where('averagePrices', json_decode(json_encode(Ad::averagePrices()), true))
    );

    // Does not work:
    $response->assertInertia(fn (Assert $page) => $page
        ->where('averagePrices', Ad::averagePrices())
    );
```

**Comment by betaSavvy** [comment]
Seems like I have also encountered the same problem. 

Using custom casting, the return value I get is 1000.0 and when using inertia testing the expected turns it into 1000 instead.

**Comment by claudiodekker** [comment]
This honestly seems related to an age-old problem related to float precision, and not specifically Inertia or the assertions. Generally, a well-accepted solution to this is to not use floats in transit/storage, but to instead use multiplication.

For instance, for the number 1234.56, you'd instead turn it into 123456 by multiplying by 100 and converting it to an integer. Then, whenever you need it as a float, you simply divide it by 100 to end up with 1234.56 again.

**Comment by alexvcasillas** [comment]
Hey @claudiodekker 👋🏻  This is still a persistent issue. I'm working on a project with floating point number calculations and I need to pass this data from Laravel to React to perform calculations with these floating point numbers and it's constantly turning them into integers which left me from `0.05` to ' 0` and it's not an option for me as I need that `0.05` value to reach my frontend. On the other hand, your suggestion of turning the floating point numbers into integers and then performing the conversion back to integers in JavaScript is very cumbersome and tedious and sadly it's not a suitable solution for a project of this scale :)
