### ISSUE TITLE
support for API Resources?

### ISSUE THREAD

**Issue by ceejayoz** [inertiajs/inertia-laravel#27]
Is support for Eloquent's [API Resources](https://laravel.com/docs/5.8/eloquent-resources) planned? We have models that a) have properties only available after a certain date and b) other properties only available to admin users.

With an API resource, we can just do stuff like:

```
$return = [
    'id' => $this->id,
    'name' => $this->id,
];

if(auth()->user()->isAdmin) {
    $return['answer'] = 'foo';
}

return $return;
```

Being able to do this would be spectacular:

    return Inertia::render('Model')
        ->with('model', new ModelResource($model);

and this:

    return Inertia::render('List')
        ->with('models', new ModelResource::collection(Model::all());

**Comment by ceejayoz** [comment]
Aaaaaand I should've tried it before writing this up.

**Comment by adriandmitroca** [comment]
Hi @ceejayoz!

Have you somehow managed to how pass pagination data alongside models?

**Comment by ceejayoz** [comment]
@adriandmitrica I have not. It seems to be added to the resource via the toResponse function, which Inertia doesn’t trigger. 

Trying to completely confirm before I embarrass myself again with another issue. 🤪

**Comment by ceejayoz** [comment]
@adriandmitroca I opened #28 about this.

**Comment by adriandmitroca** [comment]
Good one!

**Comment by adriandmitroca** [comment]
This is weird, in my case `$this->links()` returns null. Are you returning this within `toArray` method?

**Comment by reinink** [comment]
I've added support for "Responsable" props: 2b966ac27964534ee3bbe585b0ea0fff8babb53a

I've tested this with both single resource responses and collection resource responses, and it works great. 👍
