### ISSUE TITLE
There are no commands defined in the "inertia" namespace.

### ISSUE THREAD

**Issue by johnhalsey** [inertiajs/inertia-laravel#270]
After installing inertia into my Laravel app with `composer require inertiajs/inertia-laravel` as per the docs I am unable to to run the `php artisan inertia:middleware` command as I get the above error.

I've attempted clearing caches with artisan / composer commands to no avail.

**Comment by johnhalsey** [comment]
OK, actually I solved this by adding `\Inertia\ServiceProvider::class,` into the app.php

**Comment by Juhlinus** [comment]
@johnhalsey If your issue has been resolved then close the issue, please. 😄

**Comment by reinink** [comment]
Glad you got it figured out. 👍
