### ISSUE TITLE
Use FormRequest with useForm

### ISSUE THREAD

**Issue by n8udd** [inertiajs/inertia-laravel#277]
I'm new to Inertia, and am used to form submissions being intercepted with a custom FormRequest. 

I'm using the `useForm` helper, and am returning the error messages successfully, but I'd like to customise them to be a bit more user friendly in the same way you can with standard Laravel - https://laravel.com/docs/8.x/validation#customizing-the-error-messages 

Is this possible?

**Comment by reinink** [comment]
Yes, just modify them using the instructions in the Laravel documentation. This isn't something you need to do at the Inertia layer, but rather server-side, where the errors originate. 👍
