### ISSUE TITLE
Laravel Testing: InvalidArgumentException: View [app] not found.

### ISSUE THREAD

**Issue by pmochine** [inertiajs/inertia-laravel#278]
I want to PHPUnit test my controllers that are using Inertia. 

BUT now comes the but, I'm not using Inertia inside Laravel app itself but inside a Module package.

You can find a dummy repository here: https://github.com/pmochine/inertia-test

If you fire the code you will get the error:

```
Inertiatest\Browser\Tests\Unit\BrowseTest::browse_shows_all_topics
InvalidArgumentException: View [app] not found.
```

The problem is that Inertia sets its `protected $rootView = 'app';` to app. I know I can change it with `setRootView()`, but I don't know how to use it in my case.

Probable solution: 

Adding a dummy `app.blade.php` file in `tests/Fixtures/resources/views`. But how can I load this in?

Thank you for your time and help! I really appreciate it!

**Comment by claudiodekker** [comment]
Hey @pmochine,

You'll want to make sure the Inertia middleware is registered on your routes. In our documentation we suggest doing this through adding this to your HTTP Kernel, but you can also manually do this on a (group of) route(s): https://laravel.com/docs/8.x/middleware#assigning-middleware-to-routes

Please note that you can (as described in the Laravel docs) assign middleware without registering them in the Kernel when providing it's full class instead.

Hope this helps!
