### ISSUE TITLE
Cannot unbind $this of closure using .../src/Illuminate/Macroable/Traits/Macroable.php:85

### ISSUE THREAD

**Issue by muhammedkaraoglu** [inertiajs/inertia-laravel#279]
Hello guys, I encountered an error today. All I want to do is to with form validation but I get an error.

<img width="1260" alt="Ekran Resmi 2021-06-23 03 22 11" src="https://user-images.githubusercontent.com/25641500/123015948-36bed100-d3d2-11eb-82ad-b2df940fb75c.png">

Php Version : PHP 8.0.7
Laravel Framework 8.47.0

Packages : 

![Ekran Resmi 2021-06-23 03 20 17](https://user-images.githubusercontent.com/25641500/123015833-f2333580-d3d1-11eb-90d0-cb3666993fa5.png)

**NoteController.php**
```
use Illuminate\Http\Request;
....

Request::validate([
  'title' => ['required','min:3'],
   'description' => ['required']
]);

$note = new Note();
$note->title = $request->title;
$note->description = $request->description;
$note->save();
   return redirect()->route('app.dashboard');

```
**NoteForm.vue**
```
...
...
...
data() {
    return {
      notes: [],
      note: this.$inertia.form({
        title: null,
        description: null,
        created_at: null,
        updated_at: null,
      }),
    };
  },
```

**Comment by reinink** [comment]
I don't think this is an Inertia issue, but rather a Laravel issue. See here: https://github.com/laravel/framework/issues/29411

**Comment by csikoszoltan** [comment]
Hey! I had the same issue today when updated a model.
I changed the validation to this and it worked:

```
$validated = $request->validate([
    'partner_name' => ['required', 'max:255', 'unique:partners'],
]);
```

**Comment by reinink** [comment]
@csikoszoltan Thanks for sharing. 👍

**Comment by d8vjork** [comment]
Weird... I actually have this same issue trying to create my own redirector (we're maintaining a legacy version of the app inside an InertiaJS app based on AngularJS)

![code](https://user-images.githubusercontent.com/2331052/124455339-c036b180-dd89-11eb-98ca-cfa3d565472a.png)

I just changed `$this->header()` with the global helper one `request()->header()` on the Inertia's ServiceProvider.php

In my case I was using the `Request::inertia()` on a custom Facade for my app:

```php
    public static function redirect($to, array $with = [])
    {
        if (! Request::inertia() && ! static::isLegacyUser(request())) {
            return Redirect::to($to)->with($with);
        }

        if (! empty($with)) {
            Inertia::share($with);
        }

        return Inertia::location($to);
    }
```

**Comment by nathan-gratitude** [comment]
> 
> 
> Hey! I had the same issue today when updated a model.
> I changed the validation to this and it worked:
> 
> ```
> $validated = $request->validate([
>     'partner_name' => ['required', 'max:255', 'unique:partners'],
> ]);
> ```

This solved my issue in laravel 8, changing how to call request inputs

**Comment by barcovanrhijn** [comment]
> Hey! I had the same issue today when updated a model. I changed the validation to this and it worked:
> 
> ```
> $validated = $request->validate([
>     'partner_name' => ['required', 'max:255', 'unique:partners'],
> ]);
> ```

Thanks @csikoszoltan the above also works with Laravel 9 and PHP 8.0. 

_In case anyone else is wondering:_
This solution does require you to add the data with Eloquent if the validation succeeds. But that can be added below this step in your code. Failed validation still redirects back to the page with the validation error as usual for [Laravel](https://laravel.com/docs/9.x/validation).
