### ISSUE TITLE
Wrong link to release notes 0.4.3

### ISSUE THREAD

**Issue by meduzen** [inertiajs/inertia-laravel#282]
The link pointing to the release notes in [0.4.3](https://github.com/inertiajs/inertia-laravel/releases/tag/v0.4.3) should be:

https://inertiajs.com/releases/inertia-laravel-0.4.3-2021-07-12

instead of

https://inertiajs.com/releases/inertia-laravel-0.4.3 (which leads to a 404).

**Comment by reinink** [comment]
Good call, thanks! Fixed.
