### ISSUE TITLE
submit multiple data Array or Object with Inertiajs

### ISSUE THREAD

**Issue by Professor93M** [inertiajs/inertia-laravel#283]
How can I submit arrays or object data using Vuejs

I tried that:

```
Inertia.post('/',{
    data:{'first':this.data,'second':this.order}
})
```

is there any other way?

**Comment by ordago** [comment]
```javascript
Inertia.post('/settings', {
    favorite_colors: ['green', 'red', 'blue']
})
```

**Comment by reinink** [comment]
What @ordago is correct. With Inertia you can send arrays and objects just like you would send strings or integers. 👍
