### ISSUE TITLE
Skipping 'index' in controller is working but not in test

### ISSUE THREAD

**Issue by itsfaqih** [inertiajs/inertia-laravel#284]
I tried something like this in the controller and it works fine, no errors and I also could open it manually in the browser:
```php
// In the controller
public function index()
{
    return Inertia::render('Dashboard');
}
```
In `resources/js`:
```
├── Pages
│   ├── Dashboard
│      ├── index.vue
```

But when I try to test it using `assertInertia`:
```php
$response
    ->assertInertia(
        fn (Assert $page) => $page
            ->component('Dashboard')
    );
```
It will fail with a message: `Inertia page component file [Dashboard] does not exist.`
But if I were to change it to `$page->component('Dashboard/index')`, it will pass the previous test, but will fail with:
```
--- Expected
+++ Actual
@@ @@
-'Dashboard/index'
+'Dashboard'
```

I know that it's recommended to use uppercase filenames for Vue components, but I still hope to be able to use `index.vue` without explicitly writing it in the render method since it would add the possibility to have consistent path for something like this:
```
├── Pages
│   ├── Book
│      ├── Index.vue (Using Index.vue instead of Index directory because it's simple page)
│      ├── Show.vue
│   ├── Author
│      ├── Index
│         ├── index.vue (Importing the sub-components)
│         ├── AuthorFilters.vue
│         ├── AuthorModal.vue
```
```php
// In BookController
public function index()
{
    return Inertia::render('Book/Index');
}

// In AuthorController
public function index()
{
    // Consistently using 'Index' for Index page instead of 'Index/index'
    return Inertia::render('Author/Index');
}
```

**Comment by reinink** [comment]
You should be able to use a lowercase version of the file (`index.vue`).

In the controller:

```php
public function index()
{
    return Inertia::render('Dashboard/index');
}
```

In your tests:

```php
$response
    ->assertInertia(
        fn (Assert $page) => $page
            ->component('Dashboard/index')
    );
```
Have you tried this?

**Comment by itsfaqih** [comment]
Yes I have tried this, but it will show another type of failure:
```
--- Expected
+++ Actual
@@ @@
-'Dashboard/index'
+'Dashboard'
```

**Comment by reinink** [comment]
Are you sure you're testing the correct endpoint? Can you dump the response to verify the component name coming from the controller?

**Comment by itsfaqih** [comment]
Ahh sorry I just misread your comment
>In the controller:
>```php
>public function index()
>{
>    return Inertia::render('Dashboard/index');
>}
>```
I thought it was `'Dashboard'`. 
If I do it like that, yes it works. But the point of this issue is a suggestion to make it possible to pass the test without adding `/index` so that we can use it like what I've mentioned above.

```
├── Pages
│   ├── Book
│      ├── Index.vue (Using Index.vue instead of Index directory because it's simple page)
│      ├── Show.vue
│   ├── Author
│      ├── Index
│         ├── index.vue (Importing the sub-components)
│         ├── AuthorFilters.vue
│         ├── AuthorModal.vue
```
```php
// In BookController
public function index()
{
    return Inertia::render('Book/Index');
}

// In AuthorController
public function index()
{
    // Consistently using 'Index' for Index page instead of 'Index/index'
    return Inertia::render('Author/Index');
}
```

**Comment by reinink** [comment]
> If I do it like that, yes it works. But the point of this issue is a suggestion to make it possible to pass the test without adding `/index` so that we can use it like what I've mentioned above.

Ahh, understood. Sorry, I don't think this is a change I want to make. While I get why you might want this (so it behaves likes a `index.html` page), I think it's better to be explicit here with what component you're using. And, practically, on the client-side, this would require some work to figure out when to append "index" to the component name, which is not a road I'm prepared to go down at this time.
