### ISSUE TITLE
How to use app globalConfig using latest inertia implementation?

### ISSUE THREAD

**Issue by dgvai** [inertiajs/inertia-laravel#287]
Latest implementation of Inertia Laravel is:

```
//app.js
createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => require(`./Pages/${name}.vue`),
    setup({ el, app, props, plugin }) {
        return createApp({ render: () => h(app, props) })
            .use(plugin)
            .use(PrimeVue)
            .mixin({ methods: { route } })
            .mount(el);
    },
});

```

In normal Vue3 apps, there is a way to setup global config, like:

```
app.config.globalProperties.$date = dayjs;
```

How to implement this one?

**Comment by dgvai** [comment]
I have also tried in this way, but still not working:

```
createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => require(`./Pages/${name}.vue`),
    setup({ el, app, props, plugin }) {
        const VueApp = createApp({ render: () => h(app, props) });

        VueApp.use(plugin)
            .use(PrimeVue)
            .mixin({ methods: { route } })
            .mount(el);

        VueApp.config.globalProperties.$date = dayjs;
    },
});
```

It shows error in pages like : `_ctx.$date is not a function`

**Comment by RobertBoes** [comment]
```js
createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => require(`./Pages/${name}.vue`),
    setup({ el, app, props, plugin }) {
        const VueApp = createApp({ render: () => h(app, props) });

        VueApp.config.globalProperties.$date = dayjs;

        VueApp.use(plugin)
            .use(PrimeVue)
            .mixin({ methods: { route } })
            .mount(el);
    },
});
```
This should work. This way the global property is set before the app mounts, just like with plugins and mixins.

**Comment by reinink** [comment]
Yup, @RobertBoes is correct. 👍

**Comment by irfanahmad7272** [comment]
@RobertBoes you really saved my day 👍 ❤️

**Comment by phh** [comment]
Found this issue when this was not working for Vue3:
https://inertiajs.com/routing

@reinink Any change to leave an example like this in the docs? Would love to add it myself, but doesn't seems like there is an Inertia docs repo I can contribute to. Feel free to send me in the right direction if there is 🙏 .

**Comment by abdusfauzi** [comment]
awesome @RobertBoes 👍

**Comment by jEstevezRod** [comment]
so @reinink, is not possible to use createApp() outside of setup() method of createInertiaApp?
And if it is not possible, how it would possible to export that vue app instance outside?

**Comment by reinink** [comment]
@jEstevezRod Hey that's correct — for v1.0 we're hoping to just use the `setup()` method in `createInertiaApp()`, just to simplify the API surface area — and it also makes it easier to modify things between the `createInertiaApp()` function and the `<App>` component without creating breaking changes.

Is there any reason that you couldn't use the `createInertiaApp()` function instead of manually setting up the Vue instance?

**Comment by jayveeinfinity** [comment]
> ```js
> createInertiaApp({
>     title: (title) => `${title} - ${appName}`,
>     resolve: (name) => require(`./Pages/${name}.vue`),
>     setup({ el, app, props, plugin }) {
>         const VueApp = createApp({ render: () => h(app, props) });
> 
>         VueApp.config.globalProperties.$date = dayjs;
> 
>         VueApp.use(plugin)
>             .use(PrimeVue)
>             .mixin({ methods: { route } })
>             .mount(el);
>     },
> });
> ```
> 
> This should work. This way the global property is set before the app mounts, just like with plugins and mixins.

Save the day! Thanks <3

**Comment by geneowak** [comment]
@reinink I think @RobertBoes's answer should be included in the docs. I thought of adding it here https://inertiajs.com/routing, but it doesn't seem to be the right place for it and thought of creating a section in the docs but still that doesn't seem right either, hence reaching out since out as you'd be in a better position to know where to add it. I think having it there would make life much easier, especially for people just starting out.

**Comment by jsponceA** [comment]
it's work for me:
```
setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .directive("tooltip", Tooltip)
            .directive("badge", BadgeDirective)
            .directive("ripple", Ripple)
            .directive("styleclass", StyleClass)
            .directive("focustrap", FocusTrap)
            .directive("animateonscroll", AnimateOnScroll)
            .use(plugin)
            .use(PrimeVue, {
                ripple: true,
                unstyled: true,
                pt: Aura,
            })
            .use(ToastService)
            .mixin({ methods: { $route: route } })
            .mount(el);
    },
```

**Comment by mr-ragman** [comment]
@RobertBoes saved my beautiful Saturday morning.. Thanks bro
