### ISSUE TITLE
Potential `Inertia::location()` enhancement?

### ISSUE THREAD

**Issue by daronspence** [inertiajs/inertia-laravel#295]
Heya! 👋 

If I'm `#doingitwrong` please let me know, but I ran into something that I think can be handled at the adapter level and wanted to run it by the team here before making a PR.

I have a controller method, where I want to hard reload the page after doing something. `Inertia::location` is a perfect use case, but it fails in the scenario where the user somehow ends up on that URL via a manual GET/POST request. In that scenario, the user gets a blank screen as the response is a 409. I know this is edge-case-y.

My proposed solution, is to check if the request is an Inertia request before sending the 409 response, otherwise send a normal redirect.

This would be the new method

```php
public function location($url)
{
  if (Request::inertia()) {
    return BaseResponse::make('', 409, ['X-Inertia-Location' => $url]);
  }
  return redirect($url);
}
```

If this has been covered elsewhere, apologies! Thanks again for making such a fantastic tool ❤️

**Comment by innocenzi** [comment]
I've completely been bitten by that. Here's a snippet in my current codebase: 

```php
if (request()->inertia()) {
    return inertia()->location(config('legacy.login_redirect_url'));
}

return redirect()->to(config('legacy.login_redirect_url'));
```
