### ISSUE TITLE
How can I use it with laravel-vite?

### ISSUE THREAD

**Issue by wsy998** [inertiajs/inertia-laravel#299]
How can I use it with laravel-vite?

**Comment by ordago** [comment]
https://sebastiandedeyne.com/vite-with-laravel/inertia/

**Comment by wsy998** [comment]
> https://sebastiandedeyne.com/vite-with-laravel/inertia/

I can't understand this article,where should I  write `resolveComponent`？

**Comment by wsy998** [comment]
I understand it，`resolveComponent` is `resolve`, thank you.

**Comment by wsy998** [comment]
I understand it，`resolveComponent` is `resolve`, thank you.

**Comment by reinink** [comment]
> I understand it，`resolveComponent` is `resolve`, thank you.

Yes, this is correct. The `resolveComponent` method was simplified to just `resolve` when we added the `createInertiaApp()` helper method. 👍 

See here: https://inertiajs.com/releases/inertia-vue3-0.4.1-2021-05-31
