### ISSUE TITLE
Render trying to call string

### ISSUE THREAD

**Issue by scottzirkel** [inertiajs/inertia-laravel#30]
So I have a strange edge case with the latest render function (included for posterity). 

From ResponseFactory.php
```
public function render($component, $props = [])
    {
        $props = array_merge($this->sharedProps, $props);

        foreach ($this->sharedPropsCallbacks as $callback) {
            $props = array_merge($props, App::call($callback));
        }

        array_walk_recursive($props, function (&$prop) {
            if (is_callable($prop)) {
                $prop = App::call($prop);
            }
        });

        return new Response($component, $props, $this->rootView, $this->getVersion());
    }
```

I have an array of color options I'm passing through to the view. One of these colors is tan (saved as `Tan`). When it gets to checking the callable props, it assumes I mean `tan()` and gives me an error on the proper usage of the tan function. Anyway to escape out things like that? Works fine in the previous iteration.

**Comment by alexpersegona** [comment]
Having same issue. As a test, try and update a user's name to "dump." It will try to invoke the dump().

**Comment by scottzirkel** [comment]
Yeah, any string that is callable will error out. Obviously this is not going to work since we're dealing with user provided data.

I checked in the PingCRM app, and it errors out there too. Was thinking I was doing something wrong. I'm not sure why the props are being called recursively like that, but everything works smooth with that commented out.

**Comment by alexpersegona** [comment]
@scottzirkel 

Funny, I did the same thing, I checked PingCRM to see if the mistake was on my end. 

What do you think about using a specific key name, for all user input, that skips the recursive calls? I'm just worried about removing it completely in case the creator has some purpose for it that I don't know about.

**Comment by scottzirkel** [comment]
Oh I have no doubt it serves a purpose, I just haven't sorted out what that is yet. I've had it commented out locally and have yet to see an error from it.

I feel like it should be the opposite, specify a key name for what should be called? Not sure. Without knowing it's true purpose, I'm kind of at a loss.

**Comment by Resin01** [comment]
I have the same issue. If I use ->with($data) instead, it seems to work properly.

**Comment by scottzirkel** [comment]
Sure enough, I hadn't refactored that. Thanks @Resin01!

**Comment by AlexVanderbist** [comment]
I think the purpose might be to have lazy props (props that are only resolved when they're actually needed)? 

Either way this is a pretty big security concern, for example a user entering `phpinfo` as a value somewhere that'll be passed back to the Inertia component, will actually execute `phpinfo()`!

**Comment by AlexVanderbist** [comment]
For example, given the right circumstances you can get `phpinfo` to execute:
![inertiajs](https://user-images.githubusercontent.com/6287961/62690862-ca00e000-b9cd-11e9-818b-b4f72c2571e9.gif)

**Comment by reinink** [comment]
Yeah sorry folks, I had fixed this **serious** security bug back in June. See d09e6b1284266212dac3db3704775309c170b999. Are you on the latest version of inertia-laravel?

**Comment by AlexVanderbist** [comment]
My bad, composer dependencies were indeed locked on a certain commit 🙈 So sorry for the unnecessary commotion

**Comment by reinink** [comment]
All good. When it comes to security bugs, commotion is required.

Also, thanks @scottzirkel, you obviously found this in May already, thanks for reporting.
