### ISSUE TITLE
Call to a member function getBags() on string

### ISSUE THREAD

**Issue by msslgomez** [inertiajs/inertia-laravel#314]
I'm trying to return session errors but no matter if I add the errors to the shared data or not I still get this error. 

This is how I'm returning the errors
```
return back()->with('errors', 'Email or Password does not match out credentials.');
```

I installed as specified on the website and everything else seems to work fine. I've gotten this error on 2 separate projects, one was a fresh install and the other was a project that is a couple months old on this one I cloned it and then started getting this error when trying to return back with errors as well. I can't find anything on this issue online anywhere.

**Comment by claudiodekker** [comment]
Thanks @ajnsn!
