### ISSUE TITLE
How can I achieve Live Input Validation in Laravel and React.

### ISSUE THREAD

**Issue by kevinjn0123** [inertiajs/inertia-laravel#315]
Live Input Validation is a good practice for User Experience towards the project. Laravel Livewire has 'Live Validation' documented in their documentation. So will it be possible for implementing it into Inertia and React.

If so please help.

Here it is in Livewire's documentation,
https://laravel-livewire.com/docs/2.x/input-validation  -> Real-time Validation.

// It should be like, as user types in the input or blur the input, Validation errors are shown without submitting the form. 
This results in quick-knowing for the user than to submit each time for the new errors.

For Livewire it is also mentioned in this blog Post.
https://larainfo.com/blogs/laravel-livewire-real-time-validation-using-lifecycle-hooks

**Comment by claudiodekker** [comment]
Yeah, we currently indeed don't have any plans to do real-time, front-end input validation using back-end defined validation rules, as that would provide a whole different (and opinionated) layer on top of Inertia that we feel it simply isn't the right time for.

If you really want an interactive/"live" front-end validation, I'd probably recommend a custom solution like the one that @ajnsn mentioned above, or to use one of the many existing input validation libraries out there (which unfortunately does mean repeating your validation rules on the front-end, but so be it.)

If you decide to go the custom solution option, It would be awesome if you could make it available as an open-source package, though! That way, others can take advantage of it as well! 👍
