### ISSUE TITLE
Manual Visit causes HMR to stop reloading

### ISSUE THREAD

**Issue by XGhozt** [inertiajs/inertia-laravel#317]
It seems anytime I do a "manual visit" via Inertia that the subsequent changes expected via hot loading stop coming in. What's interesting is that it works the first time, and doesn't reload anymore after that, until I refresh the page manually. The console is still showing hot reload requests being made, so it's aware that changes happened but the changes never show up on the page.

Additionally, from what I can tell, CSS and parent components / layouts still work. So it's only the component that executed the manual visit which no longer reloads showing changes.

In my case I'm taking advantage of the Lazy partial reloading to get more data after the page initially loads on demand.

Edit: Vue 2

**Comment by NickSdot** [comment]
Sounds like this could be related to https://github.com/inertiajs/inertia/issues/811. 

Do you also have problems with the url/port the request returns?

**Comment by XGhozt** [comment]
Thanks @NickSdot -- I'm not sure if it's related. My pagination and other links work fine. Browsersync is also fine. It's just the mix hot-reload that causes it. It just only hot-reloads once IF _manual_ inertia requests are made before the next hot reload.

**Comment by NickSdot** [comment]
@XGhozt can you provide a minimal reproduction?

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
