### ISSUE TITLE
how to use inertia component in Blade View?

### ISSUE THREAD

**Issue by wenguang-chang** [inertiajs/inertia-laravel#319]
i write a navbar vue component, use it in inertia page , but this component i want to use it in view() render also , how to handle it ?

navbar component used inertia render data , can not render in view('index',[ data here ])

when i use view() render , how to send data to inertia vue component ?

PostController
```php
view('index',compact('data'));
```

index.blade.php
```php
<div>
//inertia vue component, Inertia::render('index',compact('data'))
//how to send data to inertia vue component ?
<navbar />
</div>
```

**Comment by ajnsn** [comment]
Hey @wenguang-chang 
you need to directly return `Inertia::render` from your controller. Please also review the setup guide [over here](https://inertiajs.com/server-side-setup). There's no view involved. The "view" will be the Vue component.

The [demo application](https://github.com/inertiajs/pingcrm) is also a good start.

**Comment by claudiodekker** [comment]
Thanks @ajnsn
