### ISSUE TITLE
put audio tag that unchanged when changing page

### ISSUE THREAD

**Issue by nemesisKO** [inertiajs/inertia-laravel#322]
where can i audio tag  that mounting pages in vue doesnt affect audio tag and reset this element. saw answers in vue router but not worked in inertia

**Comment by reinink** [comment]
To do this see persistent layouts: https://inertiajs.com/pages#persistent-layouts

You may also find this talk helpful, as it covers exactly this: https://vimeo.com/showcase/7060635/video/452360085

This isn't really an issue, so I'm going to close this.
