### ISSUE TITLE
Vue Config and errorHandler

### ISSUE THREAD

**Issue by EmilMoe** [inertiajs/inertia-laravel#330]
Where do I insert Vue.config.errorHandler in an Inertia setup?

https://v3.vuejs.org/api/application-config.html#errorhandler

```javascript
createInertiaApp({
    resolve: (name) => require(`./Pages/${name}`),
    setup({ el, app, props, plugin }) {
        createApp({
            render: () => h(app, props),
        })
    },
});
```

I need to insert this from Airbrake

```javascript
Vue.config.errorHandler = function (err, vm, info) {
  airbrake.notify({
    error: err,
    params: {info: info}
  });
}
```

**Comment by ajnsn** [comment]
Hey @EmilMoe 
here is an example which might answer your question: https://github.com/inertiajs/inertia/discussions/818#discussioncomment-1032136

**Comment by EmilMoe** [comment]
> Hey @EmilMoe here is an example which might answer your question: [inertiajs/inertia#818 (comment)](https://github.com/inertiajs/inertia/discussions/818#discussioncomment-1032136)

Thanks. However, I'm experiencing an error. Can't really point out where my code differs:

```javascript
Invalid vnode type when creating vnode: undefined. 
  at <App>
```

```javascript
createInertiaApp({
    resolve: (name) => require(`./Pages/${name}`),
    setup({ el, inertiaApp, props, plugin }) {
        const app = createApp({ render: () => h(inertiaApp, props) })
            .mixin({
                methods: {
                    route: window.route,
                }
            })
            .use(plugin)

        app.config.errorHandler = function (err, vm, info) {
            airbrake.notify({
                error: err,
                params: {info: info}
            });
        }
        app.mount(el)
    },
});
```

**Comment by ajnsn** [comment]
The destructed variable of `setup` is called `App` and not `InertiaApp`. To avoid conflicts with the later `const app`, you need to rename/assign it while destructing, e.g.

```js
setup({ el, App: inertiaApp, props, plugin })
```

Note that `app` was renamed to `App` some time ago and `app` [is deprecated](https://github.com/inertiajs/inertia/blob/master/packages/inertia-vue3/src/createInertiaApp.js#L15-L16).

Another solution would be to keep using `App` and rename your `const app` to something like `const vueApp`. Also replace `inertiaApp` in the `h` method.

**Comment by EmilMoe** [comment]
Perfect thanks! That was the detail I couldn't see 😄
