### ISSUE TITLE
Some requests get canceled after redirecting to a named route

### ISSUE THREAD

**Issue by Baspa** [inertiajs/inertia-laravel#334]
I am currently redirecting from a store route back to my index route with a flash message like this:

```php
    public function store(StoreMemberRequest $request)
    {
        $this->authorize('create', Member::class);

        RegisterNewMember::run($request);

        return redirect()->route('admin.members.index')->with('success', 'Member successfully created');
    }
```

Normally this flash message shows me a notification on my frontend. I have this bit of code in my HandleInertiaRequests middleware which shares the flash data:

```php
    public function share(Request $request)
    {
        return array_merge(parent::share($request), [
            'auth' => [
                'user' => $request->user(),
            ],
            'flash' => fn () => [
                'success' => session('success'),
                'error' => session('error'),
            ],
        ]);
    }
   ```

However, when I redirect back to my `admin.members.index` route the flash message is not shown. The only difference between the pages where it works and where it doesn't work is that I see that two requests are being canceled in the console:
<img width="1440" alt="Screenshot 2021-12-18 at 14 43 56" src="https://user-images.githubusercontent.com/10845460/146643204-f2684872-0b91-45cb-8525-d6424547d9ce.png">

More detailed information about the request (the response couldn't be loaded because no data was found):
<img width="1440" alt="Screenshot 2021-12-18 at 14 49 07" src="https://user-images.githubusercontent.com/10845460/146643371-78efe3e4-7596-4e5f-9fea-9afe36df91a9.png">

What could be the cause of the notification not showing? It does show on all other pages where the requests doesn't get canceled. The two canceled requests are literally the only differences that I could find. If someone needs any more detailed information than I would be happy to provide that. 

Versions:

- "@inertiajs/inertia": "^0.10.0"
- "@inertiajs/inertia-react": "^0.7.0"
- "inertiajs/inertia-laravel": "^0.4.5"
- "laravel/framework": "^8.65",

**Comment by RobertBoes** [comment]
My guess would either be something like CORS or a preflight that's failing (although I doubt it) or you're sending multiple Inertia requests at once.
When an Inertia request is made all other active requests are cancelled. Let's say you have 1 request that renders the same component and performs an action on that page, another request that renders a different component. If both requests are sent at the same time, the second request may arrive first, so a different component is rendered. Then the first request arrives, rendering the first component again, thus creating weird behavior. By cancelling the first request you're always getting the result of the last request being made.

**Comment by Baspa** [comment]
@RobertBoes okay that's a good explanation thank you. I will try to take a look at why there are multiple requests being made.

**Comment by Baspa** [comment]
Ah I created a function which is called on page load that checks for search and sort string in the url. It then makes a new request to the same page with the query parameters.
