### ISSUE TITLE
Weird issue with route groups

### ISSUE THREAD

**Issue by damcclean** [inertiajs/inertia-laravel#34]
When I use route groups in my `web.php` file it sometimes breaks my app.

For example I tried to do this and my entire app showed a blank screen (although the login screens seem to work)

```
Route::group(['suffix' => 'profile'], function() {
     Route::get('/', 'ProfileController@index')->name('profile.index');
});
```

However, when I take my routes out of groups, like this everything works perfectly fine.

```
Route::get('/profile', 'ProfileController@index')->name('profile.index');
```

This is what my `ProfileController.php` file looks like:

```
<?php

namespace App\Http\Controllers;

use App\User;
use Inertia\Inertia;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return Inertia::render('Profile/Index');
    }
}
```

**Comment by sylarbg** [comment]
@damcclean
[prefix not suffix ](https://laravel.com/docs/5.8/routing#route-group-prefixes)

**Comment by njoguamos** [comment]
> @damcclean
> [prefix not suffix ](https://laravel.com/docs/5.8/routing#route-group-prefixes)

As @damcclean said, you should use prefix not suffix i.e

```php
Route::group(['prefix' => 'profile'], function() {
     Route::get('/', 'ProfileController@index')->name('profile.index');
});
```

**Comment by damcclean** [comment]
I've decided to not build my app in Inertia so I'm going to close this issue. Although thanks @sylarbg and @njoguamos for your help 👍
