### ISSUE TITLE
v^0.5.1 – Any way to manipulate the HTML output in SSR?

### ISSUE THREAD

**Issue by craigrileyuk** [inertiajs/inertia-laravel#345]
Prior to the latest update, I used to run the HTML output provided by the SSR renderer through a tidy function a la 

```
@if ($ssr)
      @php
      $config = array(
          'indent'         => true,
          'output-html'   => true,
          'show-body-only' => true,
          'wrap'           => 200
      );
        // Tidy
    $tidy = new \tidy;
    $tidy->parseString($ssr['body'], $config, 'utf8');
    $tidy->cleanRepair();
    @endphp
    {!! $tidy !!}
@else
    @inertia
@endif
```

May seem pointless, but a few of our clients like to inspect the HTML output of their pages and get SEO experts and the like to look at it, and it didn't make a great impression when the entire page was a single line of output.

Is there any way I could reimplement this previous function without having to hack any of the vendor files? Perhaps you might even consider an entirely optional setting in the config/inertia.php to format the output if not.

Thanks for the great work on this feature.

**Comment by RobertBoes** [comment]
You'd have to register your own Gateway implementation, something like the following might work. Haven't tested it, but I think you'll get the idea :)

```php
// Bind the implementation in a service provider
$this->app->bind(Gateway::class, \App\Inertia\TidyHttpGateway::class);
```

```php
<?php

namespace App\Inertia;

use Inertia\Ssr\HttpGateway;
use Inertia\Ssr\Response;

class TidyHttpGateway extends HttpGateway
{
    public function dispatch(array $page): ?Response
    {
        $response = parent::dispatch($page);
        
        if (is_null($response)) {
            return null;
        }

        $config = [
            'indent'         => true,
            'output-html'   => true,
            'show-body-only' => true,
            'wrap'           => 200,
        ];

        $tidy = new \tidy;
        $tidy->parseString($response->body, $config, 'utf8');
        $tidy->cleanRepair();

        $response->body = tidy_get_output($tidy);
        return $response;
    }
}

**Comment by craigrileyuk** [comment]
I had to change the code a little `$this->app->bind(Gateway::class, \App\Inertia\TidyHttpGateway::class);` didn't work, but `$this->app->bind(\Inertia\Ssr\HttpGateway::class, \App\Inertia\TidyHttpGateway::class);` did.

But yeah. This seems to be a good userland solution to my problem.

**Comment by claudiodekker** [comment]
Yep, that's indeed how we recommend doing it 👍
