### ISSUE TITLE
laravel preset for inertia

### ISSUE THREAD

**Issue by codeitlikemiley** [inertiajs/inertia-laravel#35]
Hi i made a preset for laravel
which scaffold all the stuff you had in a very basic app install of inertia

```
composer require codeitlikemiley/vuetified-laravel-preset
```

I would love to improved this preset to either choose vuetify/tailwind for front end

for vuetify i can use my layouts from here
`
https://github.com/codeitlikemiley/vuetified
`
So basically this will be an upgrade of that repo.

Which has

custom authentication either jwt or laravel passport

custom websocket either by laravel echo server and laravel websockets

custom make:auth (tailwind/vuetify or both)

I would really love to here a feedback from you guys.

Since the main Author of inertia use tailwind. maybe  i can stub some of the login/register pages etc. for those that dont use vuetify

**Comment by leMaur** [comment]
Hi @codeitlikemiley,
Cool idea, I would like to do the same but finally I did a [repo template](https://github.com/leMaur/laravel-inertia-vue-template) on Github. I'm too lazy 😄!
What do you think?

**Comment by RSpeekenbrink** [comment]
https://github.com/laravel-frontend-presets/inertiajs

**Comment by reinink** [comment]
Thanks for sharing this @codeitlikemiley. Closing this as nothing further is required from this end.
