### ISSUE TITLE
 error  upgrade Laravel 9

### ISSUE THREAD

**Issue by Ali7med** [inertiajs/inertia-laravel#363]
its give me error in upgrade Laravel 9
 - inertiajs/inertia-laravel[v0.4.1, ..., v0.4.5] require laravel/framework ^5.4|^6.0|^7.0|^8.0 -> found laravel/framework[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
    - Root composer.json requires inertiajs/inertia-laravel ^0.4.1 -> satisfiable by inertiajs/inertia-laravel[v0.4.1, ..., v0.4.5].

**Comment by paulbrosowsky** [comment]
Upgrade to `"inertiajs/inertia-laravel": "^0.5.4"` did it for me.

**Comment by Ali7med** [comment]
thanks

**Comment by crnkovic** [comment]
@reinink looks like this can be closed as well 👍

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
