### ISSUE TITLE
Code editors not showing errors in Laravel Breeze + Inertia + React project

### ISSUE THREAD

**Issue by jrafaaael** [inertiajs/inertia-laravel#364]
By example, if a component is not imported, normally, the editor show an error. The same if a variable is not defined, among others. But with the installation of Laravel Breeze + Inertia + React these is not working...
![Screenshot_2022-02-10_11-31-16](https://user-images.githubusercontent.com/70046023/153440618-6af59d01-c172-48c6-954a-0d431ee8498a.png)

As you can see, when I comment the `Head` component and the `Authenticated` component, this would be an error because these components are not being imported. The same happens with the variable `kjds` which does not exist but the editor does not throw the error...

**Comment by crnkovic** [comment]
@jrafaaael can you test if this is still relevant? Otherwise, please close the issue.

This is also not really related to Inertia.

**Comment by reinink** [comment]
Yeah I agree @crnkovic, this might be an issue, but it doesn't have anything to do with the Inertia Laravel adapter.

I'd recommend asking this question on our [Discord channel](https://discord.gg/inertiajs) or [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) 👍
