### ISSUE TITLE
Lazy loading not working with nested response

### ISSUE THREAD

**Issue by andelwebsolutions** [inertiajs/inertia-laravel#365]
Lazy loading the revenue data doesn't work when it's nested. See example below.

See DashboardController.

    return Inertia::render('Dashboard', [
    'charts' => Inertia::lazy(fn () => [
        'revenue' => Inertia::lazy(fn () => (new RevenueChart(Carbon::now()->subYear(1), Carbon::now()))->getData())
    ])
]);

And in Dashboard.vue

    onMounted(() => {

        Inertia.replace(route('dashboard'), {
            preserveState: true,
            preserveScroll: true,
            replace: true,
            only: ['charts.revenue']
        })
    })

The revenue chart data is not being loaded lazily but on page request instead.

**Comment by crnkovic** [comment]
Hm, why would you nest lazy loads? The same can be accomplished with this:

```php
return Inertia::render('Dashboard', [
    'charts' => [
        'revenue' => Inertia::lazy(fn () => ...),
        'profit' => Inertia::lazy(fn () => ...),
        'somethingElse' => Inertia::lazy(fn () => ...),
    ],
]);
```

With lazy loading you're not running expensive computations when not needed. With the example I gave, you'll always get an empty `charts` array as a response (which is not computation heavy), but nested keys will only be loaded when asked for, thus giving you lazy loading that you asked for.

@andelwebsolutions make sure to close the issue if this has been resolved.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
