### ISSUE TITLE
Moving data-page from dom attribute to inertia-head?

### ISSUE THREAD

**Issue by jakedowns** [inertiajs/inertia-laravel#369]
would there ever be a possibility of an option to have the server-client handoff of $page happen in a script tag in the head, rather than based on attributes on the wrapping element?

i assume attributes are nice cause they can be observed?

i dunno, it's a nitpicky DevEx thing, but scrolling past a block of page props when trying to inspect elements in chrome is kind of annoying.

not the end of the world. and... i'm working to reduce the size of my $page object, but still-- just a thought i had

**Comment by RobertBoes** [comment]
I think you can actually do this, but you'll have to render the Inertia div yourself and render the page props in a script tag assigned to a variable, then you can pass the page like this: ```js
createInertiaApp({
  page: window.page,
  //Along with the usual that's used to setup Inertia
})
```

**Comment by jakedowns** [comment]
nice, i'll have to try this tip! hoping it plays nice with inertia Links

**Comment by jakedowns** [comment]
as a follow up, i tried this, and unless i didn't set it up, it seems like overriding page in createInertiaApp doesn't play nice with Server Side Rendering / partial page loads

gonna look into setting up a minimal test case repo
