### ISSUE TITLE
[IDEA] Custom classes on the root component

### ISSUE THREAD

**Issue by c-fitzmaurice** [inertiajs/inertia-laravel#370]
```
@inertia('custom-app-id', 'h-full bg-white')
```

Rendering:

```html
<div id="'.$id.'" class="'.$classes.'" data-page="{{ json_encode($page) }}"></div>
```

This could come in handy when you need to add classes to the main div without having to overwrite it or nest the app inside further components.

**Comment by RobertBoes** [comment]
I'm not sure if Inertia should include this, because of different ways frontend frameworks might render/mount. As an example, Vue 2 replaces the mount point with the mounted component:
```html
<body>
  <div id="app"></div>
</body>

<script>
  const vm = new Vue({
    template:`<h1>Vue 2 Demo</h1>`
  })
  vm.$mount("#app")
</script>

<!-- Output -->
<body>
  <h1>Vue 2 Demo</h1>
</body>
```
Vue 3 does mount inside the mounting point, which would result in the following output:
```html
<body>
    <div id="app"></div>
</body>
<script>
  const app = Vue.createApp({
    template:`<h1>Vue 3 Demo</h1>`
  })
  app.mount("#app")
</script>

<!-- Output -->
<body>
  <div id="app">
    <h1>Vue 3 Demo</h1>
  </div>
</body>
```
These differences between frameworks means it won't be a reliable solution and will only work for certain frameworks

**Comment by nurdism** [comment]
> I'm not sure if Inertia should include this, because of different ways frontend frameworks might render/mount. As an example, Vue 2 replaces the mount point with the mounted component, which means the added classes won't have any effect:

I don't see why that would be an issue. If it doesn't work on/for a given framework then that shouldn't stop this from being included. Simply don't use it if your framework doesn't support it. This would be a very helpful feature as there is no way to accomplish this w/o modifying the package.

**Comment by riabiy-denis** [comment]
Meanwhile I consider this an east-fix
https://stackoverflow.com/a/72671986/6252398

**Comment by mreduar** [comment]
Another idea would also be to add it here.
```
createInertiaApp({
  class: 'h-full bg-white',
  // ...
})
```

**Comment by lucaSabato** [comment]
Any update?

**Comment by Justinborzi** [comment]
@lucaSabato if you want to fix this yourself @nurdism has a PR for it https://github.com/inertiajs/inertia-laravel/pull/382
