### ISSUE TITLE
How to get valid inertia form with with Composition API syntax?

### ISSUE THREAD

**Issue by sergeynilov** [inertiajs/inertia-laravel#373]
In laravel 9 with Inertiajs 3 I use $inertia.form for data saving, like :

    <template>
        <div v-if="!formEditor.processing">
            <input type="text" class="form-control" v-model="formEditor.name"
            :class="{ 'is-invalid' : formEditor.errors && formEditor.errors.name }"
        >
            <div class="invalid-feedback mb-3" v-if="formEditor.errors"
            :class="{ 'd-block' : formEditor.errors && formEditor.errors.name}">
            {{ formEditor.errors.name }}
        </div>
    </div>
    ...
    
    </template>
    
    
    
    <script>
        import AdminLayout from '@/Layouts/AdminLayout'
    
        export default {
        props: ['currency', 'is_insert'], // I got these data from controller
    
        components: {
        AdminLayout,
    },
        data() {
            return {
                formEditor: this.$inertia.form({
                    id: '',
                    name: '',
                }),
            }
        },
        methods: {
            saveCurrency() {
                this.formEditor.post(this.route('admin.currencies.store'), {
                    onError: (e) => {
                        console.log(e)
                    }
                })
            }, // saveCurrency() {
        }
    }
    </script>

where formEditor is valid  inertia form and it worked ok for me, but I failed to remake this code with Composition API, like :

    <script>
    import AdminLayout from '@/Layouts/AdminLayout'
    
    import {settingsJsMomentDatetimeFormat, settingsAppColors} from '@/app.settings.js'
    import {ref} from "vue";
    
    
    let self= this
    console.log('self::')
    console.log(self)      // I have undefined here
    
    export default {
        props: ['currency'],
    
        name: 'CurrencyForm',
        components: {
            AdminLayout
        },
        setup(props) {
            let currency = ref(props.currency)
            console.log('CurrencyForm $inertia::')
            console.log($inertia) // I got "ReferenceError: $inertia is not defined error" here
    
            console.log('CurrencyForm this.$inertia::')
            console.log(this.$inertia) // THIS WAY DOES NOT WORK here
    
            console.log('CurrencyForm self.$inertia::')
            console.log(self.$inertia)  // THIS WAY DOES NOT WORK here
    
            let form = this.$inertia.form({
                id: '',
                name: '',
            })
            const formEditor = ref( form )
    
            const adminCurrencyFormOnMounted = async () => {
               ...
            }
            onMounted(adminCurrencyFormOnMounted)
    
            return { // setup return
               ...
            }
        }, // setup() {
    
    }

I failed to create inertia form as I suppose I lost valid inertia context. How can I get it and fix this error ?

Thanks!

**Comment by craigrileyuk** [comment]
First of all, I'd recommend using the <script setup> syntax which removes the need for a 'setup' function and for having to return all your variables/components/directives to be used in the template. [More info here](https://vuejs.org/api/sfc-script-setup.html#script-setup)

Secondly, there is no `this` object in the Composition API. The form helper works by way of the `useForm` function provided by @inertiajs/inertia-vue3. There's an [example here](https://inertiajs.com/releases/inertia-vue3-0.3.0-2020-12-23#new-form-helper), but it boils down to:

```js
import { useForm } from "@inertiajs/inertia-vue3";

const myForm = useForm({
    field: "",
    someOtherField: ""
});
```

**Comment by sergeynilov** [comment]
Thanks!. It helped!
