### ISSUE TITLE
Head component causes blank page

### ISSUE THREAD

**Issue by DelaneyArkICT** [inertiajs/inertia-laravel#375]
When using laravel jetstream and enabling SSR the page will render for a second or two and then go blank the reason for this is due to using the 'Head' component anywhere in the page.

After finally tracking this down I found that removing the head component fixed the issue and SSR worked within jetstream.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
