### ISSUE TITLE
Parameter in Inertia::render is not in props of vue component

### ISSUE THREAD

**Issue by sergeynilov** [inertiajs/inertia-laravel#379]
In laravel 9 with Inertiajs 3/vuejs 3 I pass parameter to vuejs side in control 

    public function index()
    {
    
        $rate_decimal_numbers = Settings::getValue('rate_decimal_numbers', CheckValueType::cvtInteger, 2);
        \Log::info(  varDump($rate_decimal_numbers, ' -1 $rate_decimal_numbers::') );  // I see valid value in log file
        return Inertia::render('Home/Home',
            ['rate_decimal_numbers'=> $rate_decimal_numbers]
        );
    }

But I do not have this parameter in vue page :

        <script>
        import FrontendLayout from '@/Layouts/FrontendLayout'
        import axios from 'axios'
        import {$vfm, VueFinalModal, ModalsContainer} from 'vue-final-modal'
        ...
        import {
            getHeaderIcon,
            ...
        } from '@/commonFuncs'
        import {ref, computed, onMounted} from 'vue'
        
    export default {
        name: 'HomePage',
        components: {
            FrontendLayout,
            ...
        },
        setup(props) {
            console.log('HOME props::')
            console.log(props)
    
            console.log('HOME props.rate_decimal_numbers::')
            console.log(props.rate_decimal_numbers) // I see undefined here and next error.

        
Checking vue tab in my broswer I see :        

https://prnt.sc/ZtLN6j2MWua0
and for my component:
https://prnt.sc/AcrSa3_7Yllw
but I see valid value in attrs :

https://prnt.sc/-VFRtomUHGt5

Why so and how that can be fixed ?

**Comment by scss-brad** [comment]
You need to define the props received by the Vue3 app.

You can read about defining props here: [Vue3 Props](https://vuejs.org/guide/components/props.html)

Here is example code:
```
export default {
    name: 'HomePage',
    components: {
        FrontendLayout,
        ...
    },
   props: {
       rate_decimal_numbers: Number,
   }
}
```
Assuming your rate_decimal_numbers is a number, otherwise choose Object or String.
