### ISSUE TITLE
Inertia + PHPUnit + GitHub actions = Failing assert that '1' is identical to 1 

### ISSUE THREAD

**Issue by maxonfjvipon** [inertiajs/inertia-laravel#383]
Hey everyone!  
[This](https://stackoverflow.com/questions/71540887/laravel-phpunit-github-actions-failed-asserting-that-1-is-identical-to-1) is the link to my question on stackoverflow, no answers for now.

I'm trying to make "continues integration" pipeline and run tests on github actions server after push to master. Major part of tests work fine, but there are some curious things.  

This is my test, which works fine on my local machine:
```php
// some code before assetion
$this->actingAs($user)
      ->get(route('profile.index'))
      ->assertStatus(200)
      ->assertInertia(fn(AssertableInertia $page) => $page
          ->component('User::Profile', false)
          // other assertions
          ->has('discounts')
          ->count('discounts', $user->discounts()->whereDiscountableType('pump_series')->count())
          ->has('discounts.0', fn(AssertableInertia $page) => $page
              ->has('key')
              ->has('discountable_id')
              ->has('discountable_type')
              ->where('user_id', $user->id)  // <---- here I get the exception
              ->has('name')
              ->has('value')
              // other assertions
          )
      );
```

And I get the exception when this test runs on Github-actions server:  

![image](https://user-images.githubusercontent.com/37025995/160696800-ef5a7a8c-26d6-4fbe-a7da-e8a0873d9ce1.png)

As I understand, value is correct, but somehow (idk why) expected value is `'1'` (string) and given is `1` (int). Obviously it must be int. And there are some more places like this where I get such errors.  

I I can assume that this is due to about operation system but I'm not really sure and I don't know what to do with this information. I use mac, github-actions "uses" ubuntu (obviously). 

I tried to do: `->where('user_id', (string)$user->id)` and test fails on my local machine. So there is no any background conversions.

Any ideas? Thanks

**Comment by crnkovic** [comment]
@maxonfjvipon is this still relevant or did you solve it? Please make sure to close the issue if this has been resolved.

Ah, where would PHP be if it only had very strict typing. Inertia uses Laravel's testing tooling under the hood so this is not related to Inertia, but casting is probably the way to go.

Since `where()` method uses `PHPUnit::assertSame()` that also compares the types, you should probably go with model casting that somebody has replied to you on StackOverflow.

**Comment by maxonfjvipon** [comment]
@crnkovic yeah, I figured it out. Thanks to your notes.
