### ISSUE TITLE
Inertia Link does not mimic Browser scroll to the top in Firefox

### ISSUE THREAD

**Issue by dajoeberlei** [inertiajs/inertia-laravel#385]
Hello,

first of all. Inertia is amazing! Thanks for providing such an amazing tool.

Im having a slight issue which only appears in firefox but not in chrome and safari.
Im using a very basic Link 

```
<Link :href="route('booking.schedule')">Schedule</Link>
```

as you can see im not using preserve-scroll attribute on the link.

the Link is at the Bottom of the Page. When clicking on it in Safari and Chrome it will go to the given booking.schedule page and you can see the scroll smoothly moving to the top of the page.

In Firefox however it stays at the same position at the end of the page.

This is how it looks in firefox V99.0 (wrong behaviour!): 

![21f54f008cedce80ff0e966667b2172e](https://user-images.githubusercontent.com/9009638/162427111-3c37e0b1-8120-4481-bd55-8be1e4810220.gif)

This is how it looks in safari/chrome (wanted behaviour! NOT preserving scroll):

![dc313e0a70bab973504d5b5d10a0523a](https://user-images.githubusercontent.com/9009638/162427158-638f927a-446e-4825-91df-8292cfcedead.gif)

I hope you guys can help me! Thanks in advance.

**Comment by RobertBoes** [comment]
Do you have a scroll region defined in your document? It almost looks like scrolling the document has no effect in your first screen recording. Inertia sets the scrollTop on the document when navigating, does executing `document.documentElement.scrollTop = 0` in console work on your page?
If that doesn't work you might have to define a scroll-region on the element that's actually scrolling, see https://inertiajs.com/scroll-management#scroll-regions
I have no idea why that would behave differently on Firefox vs Chrome, could be something else interfering and also setting scroll position, which could be executed at different states in these browsers

**Comment by dajoeberlei** [comment]
Actually using document.documentElement.scrollTop = 0 in the console works yes. It scrolls to the top in firefox as well.
Well, i have this issue on all sites on any links in this project. I have not set any scroll-region anywhere. But just to test it out i've had it set on the main div inside my layouts body and it doesnt do anything unfortunately.

**Comment by dajoeberlei** [comment]
That just made me think about it differently and i realised i have had this in my apps css:

```
html {
   scroll-behavior: smooth;
}
```

when i take it out it works! I mean, i think i can leave it out for now, but is there a way to get it working together?

**Comment by RobertBoes** [comment]
Ah, yeah that causes the issue. I've done a bit of testing and it seems to be caused by Inertia setting both `scrollTop` and `scrollLeft` to 0 at the same time, since the browser is still scrolling to the top, when the `scrollLeft` is set to 0 it cancels scrolling entirely

I did find a workaround, which uses `scrollTo()`, sets both values simultaniously and respects the scroll behaviour:
```js
import { Inertia } from '@inertiajs/inertia';

Inertia.resetScrollPositions = (function() {
    document.documentElement.scrollTo(0, 0)

    this.scrollRegions().forEach(region => {
        region.scrollTo(0, 0)
    })
    this.saveScrollPositions()
    if (window.location.hash) {
        document.getElementById(window.location.hash.slice(1))?.scrollIntoView()
    }
}).bind(Inertia)
```
You should place this somewhere in your `app.js` before `createInertiaApp`

Not sure if I should introduce this as PR just yet, might require some more testing

**Comment by RobertBoes** [comment]
I see there's already a PR for it: inertiajs/inertia#1099

**Comment by dajoeberlei** [comment]
Oh thank you very much! Perfect. ill close this issue then.
