### ISSUE TITLE
Link component only updates URL bar

### ISSUE THREAD

**Issue by moseskamau338** [inertiajs/inertia-laravel#386]
**Environment**: Default Laravel Sail docker configuration

**Description:**

I have Inertia already set up in my app on a fresh install of Laravel,
I pull in Ziggy and Tailwind to help out on the project
Creating a few links and corresponding pages work perfectly;y using the `inertia-link` component.

**Issue**
Immediately I add a separate dashboard layout, `Inertia-link` doesn't work.
I noticed however that on pages where there are no layouts expressly declared (whether persistent or otherwise), it works perfectly.

Is this an issue with the `Link` component or what could be wrong?

Your help is greatly appreciated!

**Comment by BryanMeurisse** [comment]
Hey did you find the issue on your side ?

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.

**Comment by moseskamau338** [comment]
> Hey did you find the issue on your side?

I never got a solution... I quit Inertia altogether
