### ISSUE TITLE
inject script to head

### ISSUE THREAD

**Issue by nemesisKO** [inertiajs/inertia-laravel#390]
is there any way to inject application/ld+json script to head when in vue-inertia?

**Comment by stormtomz0** [comment]
You could do it like this:
```vue
<Head>
  <component is="script" type="application/ld+json" head-key="jsonld"> {{ $page.props.jsonld }} </component>
</Head>
```
Works in SSR too, atleast with Vite.

**Comment by crnkovic** [comment]
Yes: https://inertiajs.com/title-and-meta

@nemesisKO make sure to close the issue if this has been resolved.

**Comment by ryzexsp** [comment]
i have same problem 

 Tags with side effect (<script> and <style>) are ignored in client component templates.

Compiled with problems:X

ERROR in ./routes/index.vue?vue&type=template&id=8b496c4a (./node_modules/babel-loader/lib/index.js??clonedRuleSet-1.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[2]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./routes/index.vue?vue&type=template&id=8b496c4a)

Module Error (from ./node_modules/vue-loader/dist/templateLoader.js):

VueCompilerError: Tags with side effect (<script> and <style>) are ignored in client component templates.

**Comment by stormtomz0** [comment]
I also have the same problem with JSON-LD. 

Here is an example. 

```
<Head>
   <component is="script" type="application/ld+json"> {"foo":"bar"} </component>
</Head>
```

After running `npm run build && php artisan inertia:start-ssr` it does show up when you click "view page source" but when you "inspect" the head section there is only empty script tags. So it gets removed in hydration.

- SSR works
- clientside does not work
- Google does not detect the metadata

However when you run `npm run dev` it works, so don't get fooled by that.

When you remove the Head tags and append it to the body section.

`<component is="script" type="application/ld+json"> {"foo":"bar"} </component>`

Then the situation gets kinda flipped.

- SSR does not work (script content is URL-encoded)
- clientside works after hydration
- Google can mostly read the metadata

I would really appreciate any help on this.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
