### ISSUE TITLE
Send Custom Validation Error to Front

### ISSUE THREAD

**Issue by msslgomez** [inertiajs/inertia-laravel#396]
How can I return custom validation errors to the frontend from the server? 

I've tried all these different ways but none work well, where `$message` is any ramdom string
```
throw ValidationException::withMessages([
'pop_objects' => $message
]);

$validator = Validator::make([], []); // Empty data and rules fields
$validator->errors()->add('pop_objects', $message);
throw new ValidationException($validator);

abort(500, $message);

return redirect('pop-helper/deliveries/create')>withErrors($validator)->withInput();

throw new Exception($message);
```

In my Vue file I get the event but I can't get the custom message itself which is the important part.
```
 Inertia.on('invalid', (event) => {
            console.log(`An invalid Inertia response was received.`)
            console.log(event.detail.response)
            event.preventDefault()
        });
```

How can I do this?

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!

**Comment by azankorejo** [comment]
@msslgomez experiencing the same issue, did you find any solution for this?
