### ISSUE TITLE
InertiaJs and Framer motion exit property

### ISSUE THREAD

**Issue by jechazelle** [inertiajs/inertia-laravel#397]
Hi,

I try to use Framer motion with InertiaJs.

I would like to know how can I use exit property with framer motion and InertiaJs please.

Currently I have two pages :

> profil.js

    const { pathname } = window.location
    ...

    <div>
        <motion.div className="flex flex-col" layoutId={`title-3`}
                initial={{opacity: 0}}
                animate={{
                    y: [-20, 0],
                    opacity: [0, 1]
                }}
                exit={{scale: 2}}
                key={{pathname}}
                transition={{duration: 0.2, ease: "easeOut", delay: 0.1}}
    >
        <span>Profil</span>
        </motion.div>
    </div>

> home.js

    const { pathname } = window.location
    ...

    <div>
        <motion.div className="flex flex-col" layoutId={`title-3`}
                initial={{opacity: 0}}
                animate={{
                    y: [-20, 0],
                    opacity: [0, 1]
                }}
                exit={{scale: 2}}
                key={{pathname}}
                transition={{duration: 0.2, ease: "easeOut", delay: 0.1}}
    >
        <span>Home</span>
        </motion.div>
    </div>

And I set AnimateSharedLayout on my App (app.js) :

    import { AnimateSharedLayout } from 'framer-motion';

    return render(
        <Provider store={store}>
            <AnimateSharedLayout>
                <App {...props} />
            </AnimateSharedLayout>
        </Provider>, el
    );

When I click on "home" or "profil" in the sidebar, I see the animate, but I don't see the exit animation.

I use InertiaJs and ReactJs.

I tried to use the AnimatePresence embed (https://www.framer.com/docs/examples/#exit-animations), but same thing :

    <AnimatePresence>
        <motion.div className="flex flex-col" layoutId={`title-3`}
                initial={{opacity: 0}}
                animate={{
                    y: [-20, 0],
                    opacity: [0, 1]
                }}
                exit={{scale: 2}}
                key={{pathname}}
                transition={{duration: 0.2, ease: "easeOut", delay: 0.1}}
        >
        <span>Home</span>
        </motion.div>
    </AnimatePresence>

Do you have an idea why I don't see the exit with InertiaJs ? Maybe a route configuration ?

Thank you so much for your answer !

**Comment by reinink** [comment]
Hey! I'm sorry, but I don't have any experience with Framer motion, so I'm not really in a position to help here. I'm also not sure this is an Inertia issue — it's definitely not an issue with the Laravel adapter. I'd recommend asking this question on our [GitHub discussions](https://github.com/inertiajs/inertia/discussions) or on our [Discord channel](https://discord.gg/inertiajs). Good luck 👍
