### ISSUE TITLE
Support ability to pass array data to root template

### ISSUE THREAD

**Issue by njoguamos** [inertiajs/inertia-laravel#40]
It would be nice if `withViewData()` method could accept array. That way one, can pass multiple value.  

This throws an error `(Too few arguments to function)`
```php
public function index() {
    return Inertia::render('Contact/Index')->withViewData([
        'title'       => 'Contact Us | My App',
        'description' => 'Contact us with your comments, questions, and suggestions',
        'meta'        => 'Some other SEO meta'
    ]);
}
```

Then access the variables in blade as 
```html
<title>{{  $title }}</title>
<meta name="description" content="{{  $description }}.">
<meta name="description" content="{{ $meta }}">
```

Or am I missing something

**Comment by nckrtl** [comment]
Hi @njoguamos 

You can already pass an array, withViewData is not needed. 

`public function index() {
    return Inertia::render('Contact/Index', [
        'title'       => 'Contact Us | My App',
        'description' => 'Contact us with your comments, questions, and suggestions',
        'meta'        => 'Some other SEO meta'
    ]);
}`

If you'll define the props (title, description and meta) in your Index.vue the values will become available.

**Comment by njoguamos** [comment]
I believe the idea of @reinink having `withViewData` is to be able to pass variables to `Laravel blade template`.

@nckrtl the solution you provided works only if one want to pass data to vue (which by the way is okay) but I want the array data to be accessible to my `app.blade.php`

**Comment by nckrtl** [comment]
aha, in that case I misunderstood your question.

**Comment by njoguamos** [comment]
😄 Not really, I am the one who did not explain well.

**Comment by georgehanson** [comment]
@njoguamos I noticed there is a comma after specifying the Vue Component name. The render method on the `ResponseFactory` has the second argument default to an empty array if it has not been provided, so this exception shouldn't be thrown. Have you tried changing it from this:

```php
public function index() {
    return Inertia::render('Contact/Index',)->withViewData([
        'title'       => 'Contact Us | My App',
        'description' => 'Contact us with your comments, questions, and suggestions',
        'meta'        => 'Some other SEO meta'
    ]);
}
```

To this:

```php
public function index() {
    return Inertia::render('Contact/Index')->withViewData([
        'title'       => 'Contact Us | My App',
        'description' => 'Contact us with your comments, questions, and suggestions',
        'meta'        => 'Some other SEO meta'
    ]);
}
```

**Comment by njoguamos** [comment]
@georgehanson Thanks for noting that. It was a typo and have updated my comment. 

However, [I dug deeper to Inertia ](https://github.com/inertiajs/inertia-laravel/blob/ad3b3e6241d347deef2787c9e4db2ad1dfad40e1/src/Response.php#L36) and found out that `withViewData` does not work array

```php
    public function withViewData($key, $value)
    {
        $this->viewData[$key] = $value;
        return $this;
    }
```

Instead it should be as suggested by this [PR](https://github.com/inertiajs/inertia-laravel/pull/38)

```php
    public function withViewData($key, $value = null)
    {
        if (is_array($key)) {
            foreach ($key as $k => $value) {
                $this->viewData[$k] = $value;
            }
        } else {
            $this->viewData[$key] = $value;
        }
        
        return $this;
    }
```

I hope am clear 😄

**Comment by georgehanson** [comment]
@njoguamos that makes sense, passing an array would probably be a good feature to have.

**Comment by connecteev** [comment]
+1 on this...unless I'm missing a way to update the content in the <head> tag for SEO?

**Comment by enzonotario** [comment]
@connecteev check this: https://github.com/inertiajs/inertia-laravel#accessing-data-in-root-template

**Comment by connecteev** [comment]
@enzonotario thanks

**Comment by njoguamos** [comment]
@reinink has updated `withViewData` to support array see [commit](https://github.com/inertiajs/inertia-laravel/commit/1f0a6f61f36ab3b9000c4831a3685790a03a7a6f)
