### ISSUE TITLE
Undefined method Symfony\Component\HttpFoundation\StreamedResponse::header()

### ISSUE THREAD

**Issue by sidneygijzen** [inertiajs/inertia-laravel#400]
Hi,

In one of my projects I'm making use of a streamed response, so `return response()->stream()`. Since the upgrade to 0.6.1 I'm seeing the following error:

`Error: Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::header() in file /var/www/<projectname>/vendor/inertiajs/inertia-laravel/src/Middleware.php on line 90
`

Probably related to changes made in #398?

**Comment by reinink** [comment]
Thanks for reporting this — this has been fixed and published: https://github.com/inertiajs/inertia-laravel/releases/tag/v0.6.2

**Comment by sidneygijzen** [comment]
You're welcome. Thanks for fixing it so quickly :+1:
