### ISSUE TITLE
Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()

### ISSUE THREAD

**Issue by mberneis** [inertiajs/inertia-laravel#401]
When I upgraded my application to the latest and greatest (php8.1, latest Laravel) I encountered this error:

```
 Error: Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header() in .../vendor/inertiajs/inertia-laravel/src/Middleware.php:90
```

Looks like it can be fixed by changing line 90 in `src/Middleware.php`
``` 
$response->header('Vary', 'Accept');
```
 to 
```
$response->headers->set('Vary', 'Accept');
```
according to https://laracasts.com/discuss/channels/laravel/call-to-undefined-method-binaryfileresponseheader-1

**Comment by reinink** [comment]
Thanks for reporting this — this has been fixed and published: https://github.com/inertiajs/inertia-laravel/releases/tag/v0.6.2
