### ISSUE TITLE
Empty object in Response gets transformed to empty array

### ISSUE THREAD

**Issue by cell-0** [inertiajs/inertia-laravel#405]
When updating to the latest version of Inertia-laravel, I encountered a problem where in our Resources empty objects get transformed to empty arrays.

We used to return an empty object this way, which resulted in an empty object in the Inertia response:

```php
class ArticleResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'tag_sets' => new \stdClass(),
        ];
    }
}
```

And in the controller:

```php
return inertia('ArticlePage', [
    'article' => ArticleResource::make($article),
]);
```

Which resulted in a prop:

```js
{
    article: {
        tag_sets: {}
    }
}
```

Since updating to the latest inertia-laravel, this is changed in an empty array:

```js
{
    article: {
        tag_sets: []
    }
}
```

I come from a rather old version, so I'm not sure when it exactly is changed, but I've tracked down the change to this pull request: https://github.com/inertiajs/inertia-laravel/pull/265. In `Reponse.php` the data is requested "associative", which converts objects into arrays. (see https://www.php.net/manual/en/function.json-decode.php)

I am curious if this is intentional, and if it would be a good idea to make it more configurable. I don't see a way now to change the behavior. 

I can change the frontend to also work with empty arrays, but this would need changes in many places where this is used. Therefore it would be better I think to be able to configure it on the backend.

**Comment by reinink** [comment]
Hey! That sucks that you bumped into this, but I think at this point we better leave this how it is, as it's been like this for over six months and I worry that changing it again could actually break things for more people.

We *could* make it an option, but I hate adding unnecessary options to the library, especially if this associative array format is generally the better choice. Of course if I get a lot of feedback about this, I will of course reconsider.

Hope that makes sense 🙏

**Comment by matthias-noetzli** [comment]
Just ran into the same issue. Took me quite a while to even figure out that I'm not just using Laravel Resources incorrectly.
I'm sure there's good reasons for this behaviour, but I find it very unintuitive that my Laravel JsonResponse contains an empty object and my Vue component receives an empty array. Is there a suggested way to handle this?
