### ISSUE TITLE
Incomplete response json from inertia js

### ISSUE THREAD

**Issue by bibekshakyeah** [inertiajs/inertia-laravel#407]
I am getting incomplete json response. I dont know what is causing this issue. Here is sample json
![Screenshot from 2022-05-31 09-23-28](https://user-images.githubusercontent.com/62230809/171088865-93afb8e8-ccfb-44ec-9ddd-1a0d9d5cb843.png)

I have debug the code Response.php from inertia-laravel
Response.php
```
   if ($request->header('X-Inertia')) {
        return new JsonResponse($page, 200, [
            'Vary' => 'Accept',
            'X-Inertia' => 'true',
        ]);
    }
```

which seem right and dump & die giving me correct data.

**Comment by swarakaka** [comment]
[I think, this is how the header should be sent](https://github.com/inertiajs/inertia-laravel/commit/d00512eb3faa5dfc3a432e0778866f34fe5eff62#diff-fe9ea193fb20c81c9a1c52ff17a51129ec6a1e401cbee96e91001a1962c33299R89)

**Comment by reinink** [comment]
Hey! Sorry, but I'm not sure what's causing this — but I don't think this is an Inertia issue. Feel free to provide a minimum reproduction repo, and I'd be happy to look at it, but my gut tells me this is memory or web server related.
