### ISSUE TITLE
Resposes rendering in modal above the current site, duplicating html tags

### ISSUE THREAD

**Issue by jackkitley** [inertiajs/inertia-laravel#412]
We currently host a site on AWS ECS and the desired count of the containers is set to 2 for the web app. We have started to notice strange behaviour with the Inertia js responses where the response is rendered inside a modal where Inertia would normally render a 404 for example or a page has expired error.

<img width="1191" alt="Screenshot 2022-06-05 at 07 24 18" src="https://user-images.githubusercontent.com/3243014/172036614-38ab8f67-5992-4ed7-b709-02664b7b13be.png">

![Screenshot 2022-06-04 at 19 26 52](https://user-images.githubusercontent.com/3243014/172035842-dd2cd895-b6ad-4bf3-93c5-cf5fcccf58b6.png)

This response then renders inside a modal above the current site. We are not sure what is causing this particular behaviour.

![Screenshot 2022-06-05 at 06 44 55](https://user-images.githubusercontent.com/3243014/172035839-8726bcf7-3163-41a5-8e3b-eb1e4183a31f.png)

It doesnt happen all the time but strange that the response has JSON in it along with HTML in the response...

Another Example:

![Screenshot 2022-06-05 at 06 54 55](https://user-images.githubusercontent.com/3243014/172035653-c7c1a9f9-083f-43df-9024-492e777e995a.png)

![Screenshot 2022-06-05 at 06 58 15](https://user-images.githubusercontent.com/3243014/172035798-b564e420-187f-4b5d-93dd-0fff3d8fb5a1.png)

![Screenshot 2022-06-05 at 06 58 07](https://user-images.githubusercontent.com/3243014/172035800-a83bdff9-2086-45a0-ae4b-a67e9f8fe3ac.png)

**Comment by crnkovic** [comment]
What is the response from your application code? It looks like you're trying to respond with both data and a redirect response (via the status code maybe).

@jackkitley remember to close the issue if this has already been resolved.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
