### ISSUE TITLE
How to inject inertia components into existing blade pages

### ISSUE THREAD

**Issue by ben-cheng565** [inertiajs/inertia-laravel#418]
The pages of my current project are all blade files, we now want to refactor some of them using inertia. But I have not figured out how to replace a specific part on the existing page. 

Has inertia already supported this functionality? Or anyone know how to implement it? Really appreciate it.

**Comment by crnkovic** [comment]
What is troubling you? Create a [root template](https://inertiajs.com/server-side-setup#root-template) with your existing design and return an Inertia response from controllers for pages you wish to migrate to Inertia.

```blade
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    @vite('resources/js/app.js')
    @inertiaHead
  </head>
  <body>
    <div>Your stuff</div>

    @inertia
  </body>
</html>
```

All Inertia does is render the Vue/React app and then glue Laravel backend with those frontends, you may get more help from some Laravel + Vue/React setup guides.

You can have some pages be Vue/React (and Inertia), and some regular static pages with Blade.

@ben-cheng565 remember to close the issue if this has been resolved.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this problem.
