### ISSUE TITLE
Redirect without going through Inertia?

### ISSUE THREAD

**Issue by rakk7** [inertiajs/inertia-laravel#42]
Is it possible to do a redirect without going through Inertia?

For example, if I do a post request using ( `$inertia.post` ) to ( `/posts` ) and I have something like this in the store method:

```
// code ...
return redirect()->route('/admin/posts)
````
I want to do a **full page refresh** without going through Inertia.. is this possible?

**Comment by focusiq** [comment]
Hello @rakk7 , were you able to get this done? If yes, how did you go about it?

**Comment by reinink** [comment]
There isn't official support for this in Inertia yet, but it's on our roadmap. Plus there is a workaround. See here: https://github.com/inertiajs/inertia-laravel/issues/57#issuecomment-570581851
