### ISSUE TITLE
Subdirectory urls broken

### ISSUE THREAD

**Issue by andrew1601** [inertiajs/inertia-laravel#421]
#347 breaks Laravel projects that run in a subdirectory.

src/Response.php was changed at line 128 but nothing in the commit message details why. Symfony don't seem to have changed what these methods do and this now returns the incorrect URL which causes the Inertia client adapter to push an incorrect path to the history. So an Inertia app running at https://example.com/app will have https://example.com/app/app pushed to the history on the initial page render automatically.

The issue is also described here: https://laracasts.com/discuss/channels/laravel/root-directory-is-displayed-twice-in-url-on-load-and-reload

PR on the way

**Comment by CristianSitov** [comment]
I'm watching all these issues: current, #422 & #437 
Hopefully, one of them will be merged soon.

**Comment by PrasadChinwal** [comment]
Any update on this issue?

**Comment by claudiodekker** [comment]
https://github.com/inertiajs/inertia-laravel/pull/446#issuecomment-1920171976

**Comment by jessarcher** [comment]
Hi, this should be addressed by #592. Sorry for the delay!

**Comment by driesvints** [comment]
Just FYI: Laravel has never and never will support sub directories and you should avoid running them as such: https://laravel.com/docs/10.x/installation#directory-configuration

**Comment by Dotgix-Technologies** [comment]
i waw facing issue on suburls then urls wars repeating it self so after hours of debugging i found the issue no neet to change in any ventor file just define 
 <base href="/public">
then it work for me
