### ISSUE TITLE
All Inertia requests must receive a valid Inertia response, however a plain JSON response was received.

### ISSUE THREAD

**Issue by cristian807** [inertiajs/inertia-laravel#423]
Hello everyone.

I have an error for a long time and I have not been able to solve it.
**Note** in search of a solution to this problem, I noticed that this only happens to me on the CPANEL production server, the same page was uploaded to a shared server in hostinger and everything was fine.

I already checked the installed PHP extensions and I have not found the solution to this problem.

![Captura de pantalla de 2022-06-25 17-57-49](https://user-images.githubusercontent.com/66740507/175792767-9410e27f-bd26-4481-b0fd-0c885b70006a.png)

**Route**
![Captura de pantalla de 2022-06-25 18-00-37](https://user-images.githubusercontent.com/66740507/175792818-a68b05e8-df85-434e-a9a5-1f28d9ca9e86.png)

**Method Controller**
![Captura de pantalla de 2022-06-25 18-02-45](https://user-images.githubusercontent.com/66740507/175792851-cd5d5fea-130c-4900-ae3a-6839460677e0.png)

If I remove the paginate() method and replace it with limit() and get()  it works.

**Link**
![Captura de pantalla de 2022-06-25 18-04-32](https://user-images.githubusercontent.com/66740507/175792986-19c2b292-4239-416c-b34d-aee1ee531d69.png)

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this problem.
