### ISSUE TITLE
Why many times after update vue component browser shows older content not new?

### ISSUE THREAD

**Issue by clickervinod** [inertiajs/inertia-laravel#424]
Hi,
Plz help !
why many times it happes when i make any changes in vue components and also running npm run watch browser shows old content. when i press ctrl +f5 many times somtime it shows updated content and my time not ..3..

What should i do to show latest update content when i make any changes to it.

Thanks

**Comment by andrewizmaylov** [comment]
Once I faced the same problem. 
The reason was the name of the component. 
npm scripts won't work with `component` and `Component`

**Comment by crnkovic** [comment]
Browser cache is my guess. This is very likely unrelated to Inertia, but you may try what @andrewizmaylov has written.

If you're using Laravel Mix to compile assets, read the docs on cache busting: https://laravel.com/docs/8.x/mix#versioning-and-cache-busting

@clickervinod remember to close the issue if this has been resolved.

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this problem.
