### ISSUE TITLE
Not a valid Inertia response

### ISSUE THREAD

**Issue by ibrahim-999** [inertiajs/inertia-laravel#427]
First : thank you so much for InertiaJs, it's awesome ! slightly_smiling_face

i use 
inertiajs/inertia-laravel 0.6.3
Laravel 8.40

i got this respones every time i run my test and i have checked everything,

sometime i use `Assert` insted of `AssertableInertia`

if someone could point me on the right direction i would be glad 
```
use Inertia\Testing\AssertableInertia;

use RefreshDatabase;

public function test_home_page_sponsors(): void
    {
        $sponsors = Sponsor::factory()->count(5)->create();

        $this->get('/')
            ->assertInertia(fn (AssertableInertia $page) => $page
            ->component('HomePage')
            ->has('sponsors.data', 5)
            ->has(
                'sponsors.data.0',
                fn (AssertableInertia $page) => $page
                    ->where('title', $sponsors[0]->title)
                    ->etc()
            ));
    } 
```

**Comment by amadeann** [comment]
It's related to this change:
https://github.com/inertiajs/inertia-laravel/pull/338

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this problem.
