### ISSUE TITLE
subfission/Cas and CORS

### ISSUE THREAD

**Issue by ProjectesFUAB** [inertiajs/inertia-laravel#430]
I'm using [Subfission/CAS](https://github.com/subfission/cas) to authenticate users through middleware in Laravel:

`if (!cas()->checkAuthentication()) cas->authenticate();`

All works fine until use Link component or partial reloads and cas session has expired. Then  get CORS error:

Access to XMLHttpRequest at '...' (redirected from '...') from origin '...' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Any idea how I can avoid the error?

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
