### ISSUE TITLE
Scroll position is always preserved in reactjs

### ISSUE THREAD

**Issue by truejay** [inertiajs/inertia-laravel#436]
When navigating from one page to another, scroll position is always preserved. Applies to Inertiajs + Reactjs combo only.

See example here:
https://pingcrm-react.herokuapp.com/

Source code:
https://github.com/Landish/pingcrm-react

**Comment by RobertBoes** [comment]
The issue on that example is that the body/document doesn't scroll, but rather an element within the page that scrolls. So you'd have to define a [scroll region](https://inertiajs.com/scroll-management#scroll-regions) on the appropriate element. This means you'd have to add a scroll region here: <https://github.com/Landish/pingcrm-react/blob/main/resources/js/Shared/Layout.js#L21>

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
