### ISSUE TITLE
Laravel has transitioned to Vite from Mix. The Inertia installation guide for Laravel is outdated.

### ISSUE THREAD

**Issue by bit-pax** [inertiajs/inertia-laravel#438]
There should definitely be an installation guide for Laravel using Vite instead of Laravel Mix. Older projects may still use Mix but more recent projects are using Vite.

**Comment by herpaderpaldent** [comment]
Do it! That would be lovely. While you are at it: maybe please update PingCRM as well?

**Comment by CapitaineToinon** [comment]
Would love some quick tldr on how to get it working with vite! I'm trying to use inertia for the first time and it took me about an hour to find this thread. So far I simply couldn't get anything to work.

**Comment by Atif-Bashir-1998** [comment]
Waiting for the new documentation with vite

**Comment by rojtjo** [comment]
The Laravel documentation has a lot of information on how to get things running: https://laravel.com/docs/9.x/vite

**Comment by cookiies** [comment]
Not sure if this helps anyone but it's something I wish I had, would have saved me hours! I couldn't get my head around running `npm run dev` alongside `php artisan serve` simultaneously.

![image](https://user-images.githubusercontent.com/37172252/188463808-15f38600-0eb3-446e-8f83-b374db7875d6.png)

**Comment by jbrooksuk** [comment]
Docs for v1.0 fixes this. https://next.inertiajs.com/client-side-setup

**Comment by tnup** [comment]
> Docs for v1.0 fixes this. https://next.inertiajs.com/client-side-setup

You might mean: https://inertiajs.com/client-side-setup ?
