### ISSUE TITLE
Inertia.delete produces 419 but form.delete does not (only in production)

### ISSUE THREAD

**Issue by Arturexe** [inertiajs/inertia-laravel#440]
I've spent some time trying to find a workaround for `Inertia.delete()` resulting in a `419 | PAGE EXPIRED` error, which ocurred only in production. I tried `form.delete()` instead and now the route works.

Is this a bug or intended? Why does one work and not the other and why only in production? It seems to be a `CSRF` issue?

composer.json
```
        "laravel/framework": "^9.19",
        "inertiajs/inertia-laravel": "^0.5.4",
```
packages.json
```
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
```

**Comment by rojtjo** [comment]
Is the CSRF token included when you inspect the request from `Inertia.delete()` in the network tab?
