### ISSUE TITLE
The DELETE method is not supported for this route. Supported methods: GET, HEAD

### ISSUE THREAD

**Issue by usmanvaince** [inertiajs/inertia-laravel#444]
composer.json

```
"laravel/framework": "^8.75",
"inertiajs/inertia-laravel": "^0.6.3"
```

packages.json
```

"@inertiajs/inertia": "^0.11.0",
"@inertiajs/inertia-react": "^0.8.1",
```

Whenever I call `Inertia.delete(url)`, the delete request is send to the server. And a resource is deleted. But When I redirect back within the same function like `return redirect()->back()`. I get the following error, because next route is also being accessed via `DELETE` method instead of `GET` method.

<img width="1617" alt="Screenshot 2022-09-23 at 3 28 01 PM" src="https://user-images.githubusercontent.com/21067230/191941995-5e816c57-ebd6-4a00-8c94-9e4a5f0b519a.png">

**Comment by usmanvaince** [comment]
ok got the solution, I recently updated the inertiajs/inertia-laravel version, where I was using the implementation in AppService Provider, I just move that implementation in the middleware and it is fixed.

**Comment by reinink** [comment]
Great, glad you got it figured out 👍
