### ISSUE TITLE
PhpUnit or Pest tests fail only in Github Actions

### ISSUE THREAD

**Issue by kayintveen** [inertiajs/inertia-laravel#455]
I have a straightforward test that passes locally, but in a Github Action fails. 

It's about the following assertion: 
```
    $this->get('dashboard')
        ->assertInertia(fn(Assert $page) => $page
            ->component('Dashboard')
            ->has('events', 10)
            ->has('events.0')
            ->where('events.0.id', Event::first()->id)
        );
```

When I run it with ShouldExist on false it passes.
```
            ->component('Dashboard', false)
```

This is the error mesage.
```
Inertia page component file [Dashboard] does not exist
```

I already checked the capitalization as this might impact on a mac vs Unix filesystem but that's all correct.

**Comment by SuperDJ** [comment]
Perhaps you need to change the config of Intertia. It needs to know where it can find the JS files.

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
