### ISSUE TITLE
Page props transform

### ISSUE THREAD

**Issue by bolivir** [inertiajs/inertia-laravel#457]
Hi,

currently my backend is returning page properties as resources. These resources are returned in the json api spec format.

Now my issue is that i cannot transform the page props in vue directly. It would be super nice to have the possibility to hydrate the prop to typescript model/class.

Is there any way to do the transformation before? I cant be the only one who is using json api spec formats and needs those transformations

**Comment by reinink** [comment]
Hey thanks for this suggestion, but in general Inertia is designed to work with ready-to-go data from the server, and we don't currently have any built-in way to transform that data client-side.

I'd recommend discussing this on our [Discord channel](https://discord.gg/inertiajs) or [GitHub Discussions](https://github.com/inertiajs/inertia/discussions), as this isn't a bug with the Laravel adapter.

Good luck! 👍
