### ISSUE TITLE
getting looped in view

### ISSUE THREAD

**Issue by abdullahrahimee** [inertiajs/inertia-laravel#464]
i have an web application which is developed laravel-inertia and Vue3 which is working fine but some of my client reported that they are getting a loop screen in production.
as bellow:
![WhatsApp Image 2022-11-03 at 11 43 03 AM](https://user-images.githubusercontent.com/8949075/199674729-3c029f73-701c-4798-90a8-001be9dbf0c8.png)

**Comment by RobertBoes** [comment]
This is the [Inertia error modal](https://inertiajs.com/error-handling), which is opened whenever a response doesn't return a valid Inertia response. The linked docs explain how you can catch this exception and render an Inertia view instead of a Blade response.

**Comment by reinink** [comment]
Thanks for your help here @RobertBoes! 💪
