### ISSUE TITLE
Inertia responses with http status other than 200

### ISSUE THREAD

**Issue by mtlukaszczyk** [inertiajs/inertia-laravel#465]
Hello,
when returning Inertia response with "inertia()" helper, or by returning new Inertia\Response it is not possible to return a http status other than 200. It would be useful to be able to set this parameter.

**Comment by jbrooksuk** [comment]
You can do the following:

```php
return inertia('Component', [
  // Data...
])->toResponse(request())->setStatusCode(304);
```

**Comment by crnkovic** [comment]
@jbrooksuk is right, the docs give out an example that does this [here](https://inertiajs.com/error-handling) under the "Production" heading, so you can use that as a guide. Example:

```php
public function index(Request $request) : Response
{
    return Inertia::render('Dashboard')
                ->toResponse($request)
                ->setStatusCode(201);
}
```

@mtlukaszczyk make sure to close the issue once your problem is resolved.

**Comment by reinink** [comment]
Thanks for your help here @jbrooksuk and @crnkovic! 👍
