### ISSUE TITLE
handler missing shared props

### ISSUE THREAD

**Issue by pasamsin** [inertiajs/inertia-laravel#468]
I have a handler like below. When I visit an address that is not in the form of https://website.com/a -> 404 ErrorFront and https://website.com/a/b -> 404 ErrorFront, it works fine. If I add the third /c like https://website.com/a/b/c -> 404 ErrorFront, the props disappear. and I cannot access this 
```usePage().props.value.theme```
 prop.
```
    public function render($request, Throwable $e){
        $response = parent::render($request, $e);

        if (in_array($response->status(), [500, 503, 405, 404, 403, 429])) {
            return Inertia::render('ErrorFront', ['status' => $response->status()])
            ->toResponse($request)
            ->setStatusCode($response->status());
        }elseif($response->status() === 419) {
            return back()->with('error',[
                'message' => __('Time Out Bro'),
            ]);
        }

        return $response;
    }
```

If I add below route to web.php file and visit https://website.com/a/b/c I can access ```usePage().props.value.theme```.

```        
Route::get('/{slug?}/{altslug?}/{testslug?}', function (){
            return abort(404);
 });
```
and when I visit https://website.com/a/b/c/d again usePage().props.value.theme is undefined.

**Comment by pasamsin** [comment]
If I add below route to web.php file and visit https://website.com/a/b/c I can access ```usePage().props.value.theme.```
```        Route::get('/{slug?}/{altslug?}/{testslug?}', function (){
            return abort(404);
        });```

**Comment by pasamsin** [comment]
Added the following line to the bottom of the web.php file. did i do it right?
```
Route::fallback(function () {
    return abort(404);
});
```

**Comment by reinink** [comment]
Hey I'd recommend asking this question on our [Discord channel](https://discord.gg/inertiajs) or [GitHub Discussions](https://github.com/inertiajs/inertia/discussions), as this doesn't appear to be an actual bug with this library. Good luck! 👍
