### ISSUE TITLE
V-model no fill field

### ISSUE THREAD

**Issue by majweb** [inertiajs/inertia-laravel#469]
(VUEJS Inertiajs)
Strange situation.
I have a form to edit addresses and locations. Why doesn't it fill my model if I click method fetchAddress.
      
let adress = ref(null);
let loading = ref(false);

const form = useForm({
    _method: 'PUT',
    city_id: props.user.detail.city_id,
    street: props.user.detail.street,
    building:adress.value.house_number || props.user.detail.building,
});

const fetchAddress = async  () => {
        try {
            loading.value = true;
            adress.value = await currentAddress();
            loading.value = true;
        } catch (error) {
            errorMap.value = error;
        }
}

            <div class="col-span-6 sm:col-span-4">
                <InputLabel for="building" value="Nr budynku" />
                <TextInput id="building" v-model="form.building" type="text" class="mt-1 block w-full"
                    autocomplete="building" />
                <InputError :message="form.errors.building" class="mt-2" />
            </div>

            
<button type="button" @click="fetchAddress">Znajdź mnie</button>

**Comment by crnkovic** [comment]
@majweb If you're submitting a form using `form.put()`, you don't need to override the `_method` property.

On the issue itself, `address` is a ref and should reactively update to whatever `currentAddress()` returns. Without seeing the code for that function, nobody can really help you out.

I have a feeling this isn't related to Inertia itself, so please make sure to close the issue if this is resolved and/or unrelated, to help maintainers keep track of issues related to Inertia.

P.S: Read [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) short guide on how to properly format code snippets on GitHub.

**Comment by reinink** [comment]
Thanks again for your help here @crnkovic!

@majweb, if you need further help, I'd recommend asking this question on our [Discord channel](https://discord.gg/inertiajs) or [GitHub Discussions](https://github.com/inertiajs/inertia/discussions), as it's not really an issue with this library.

Good luck! 👍
