### ISSUE TITLE
[Feature Request] Adding make:auth with inertia

### ISSUE THREAD

**Issue by Naoray** [inertiajs/inertia-laravel#47]
There are a few nice inertia presets out there - like mentioned in #35 or [inertiajs-preset](https://github.com/laravel-frontend-presets/inertiajs). Still it would be really nice to have an `official` preset which could also override/extend the default `make:auth` command to publish standard views for
- register
- login
- password forget/email
- verification

and Controllers which handle the `Inertia::render()` responses on the `GET` requests.

**Comment by reinink** [comment]
Yeah, I agree, it would be good to have an official Inertia.js preset for Laravel. Let's maybe wait and see what @taylorotwell does with [laravel/ui](https://github.com/laravel/ui) first.

**Comment by Naoray** [comment]
Ok, didn't know about this repo. Agree... waiting for this is probably better

**Comment by davidangel** [comment]
Might check this out in the meantime: https://github.com/laravel-frontend-presets/inertiajs/pull/5

**Comment by Naoray** [comment]
@reinink with https://github.com/laravel/ui/pull/16 we can now also build a auth preset for inertia. Would you want to put this preset into a separate repository?

**Comment by codeitlikemiley** [comment]
I do have a preset that uses scafold inertia JS but with vuetify not your tailwind css favorites :)

```
https://github.com/codeitlikemiley/vuetified-laravel-preset
```

This is configured to work out of the box with vuetify and vuetify loader 

If your lazy to import all vuetify components, also save you tons of assets cause you only compiled the components that you needed...

**Comment by reinink** [comment]
Closing this for now, as I think there's a good chance that official support might be coming from Laravel via the [laravel/ui](https://github.com/laravel/ui) package. 👍
