### ISSUE TITLE
Redirect via redirect()->intended() to a file download not working after re-login 

### ISSUE THREAD

**Issue by mauthi** [inertiajs/inertia-laravel#472]
I used your [demo application](https://inertiajs.com/demo-application) as boilerplate and nearly everything works fine. Great work.

My current problem:

I have an endpoint which allows users to download a file
```
    public function download(Download $download)
    {
        return response()->download(storage_path(Download::BASE_DIR . $download->filename));
    }
```
If a user is logged in it works correctly.

If a user is not logged in and tries to reach a download url it looks the following after login:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/7204559/205499191-72b94782-5d03-45f1-84fe-65a19d4a65e0.png">

The redirect via `redirect()->intended()` in the `AuthenticatedSessionController` redirects to the correct url but it seems that something is mixed up in response.

(FYI: I had a similar looking problem before when I am using <Link> component to link to the download, changing this to a normal `<a href="...">` solved this, also described here https://github.com/inertiajs/inertia-laravel/issues/101)

**Comment by mauthi** [comment]
Sorry, I updated to v0.6.4 and it seems that this was fixed already (now it's redirecting to HOME after login if you try to download a file)

**Comment by malik-krehic** [comment]
Is it somehow possible to actually download file after login?
