### ISSUE TITLE
Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()

### ISSUE THREAD

**Issue by takielias** [inertiajs/inertia-laravel#473]
```shell       
removeTweet(id) {
     if (confirm('Are you sure you want to delete this tweet?')) {
     Inertia.delete(route("tweet.delete", id));
    }
 }
```
```shell
Route::delete('/tweet/{tweet}', [\App\Http\Controllers\TweetController::class, 'removeTweet'])->middleware(['auth'])->name('tweet.delete');
```

Is there anything wrong with my code? But I'm getting the following error.

![image](https://user-images.githubusercontent.com/38932580/206239368-dfaabe73-a34d-4b21-b350-5996c22a52d5.png)

I did not event use soft delete.

**Comment by crnkovic** [comment]
This is not related to Inertia, but you need to use [SoftDeletes trait](https://laravel.com/docs/9.x/eloquent#soft-deleting) in the model, since that model provides you with the `withTrashed` scope.

**Comment by reinink** [comment]
Thanks @crnkovic, that's correct 👍
