### ISSUE TITLE
withViewData() method accept key and value but array given in documentation

### ISSUE THREAD

**Issue by sazzadh88** [inertiajs/inertia-laravel#49]
withViewData() method accept key and value  but in documentation it is mention that key and value pair will be an array but correct implementation is like this

//In controller

```
$meta['description'] = 'You description';
$meta['keywords'] = 'Your keyword';

return Inertia::render('Event', ['event' => $event])->withViewData('meta', $meta);

```

//in root template

```
<meta name="description" content="{{ $meta['description'] }}">
 <meta name="keywords" content="{{ $meta['keywords'] }}">
```

**Comment by reinink** [comment]
Nice catch! I've updated the `withViewData()` to support both ways, like Laravel [views work](https://github.com/laravel/framework/blob/5.8/src/Illuminate/View/View.php#L184-L193).

**Comment by sazzadh88** [comment]
Thanks :)
