### ISSUE TITLE
SSR  Invalid vnode type when creating vnode

### ISSUE THREAD

**Issue by touhid12310** [inertiajs/inertia-laravel#497]
i have installed everything working on client side but server side showing this issue...

Starting SSR server on port 13714...
Inertia SSR server started.
[Vue warn]: Invalid vnode type when creating vnode: undefined.
[Vue warn]: Invalid vnode type when creating vnode: undefined.
[Vue warn]: Invalid vnode type when creating vnode: undefined.
[Vue warn]: Invalid vnode type when creating vnode: undefined.
[Vue warn]: Invalid vnode type when creating vnode: undefined.

**Comment by ramonrietdijk** [comment]
Hi @touhid12310, 

This is likely because of your `setup` method, please see issue #498.

**Comment by reinink** [comment]
Yes, agreed, setup must use `App` instead of `app`. Also this isn't a bug with the Laravel adapter, so I'm going to close this 👍
