### ISSUE TITLE
Small error in SSR documentation for Inertia 1.0

### ISSUE THREAD

**Issue by ramonrietdijk** [inertiajs/inertia-laravel#498]
Hi,

When reading the documentation of [server side rendering](https://inertiajs.com/server-side-rendering) you will come across the heading `Add server entry-point`. In the code samples for `Vue 2` and `Vue 3` the `setup` method uses the variable `app` with a lowercase `a`. This should be updated to `App` as stated in the [upgrade guide](https://inertiajs.com/upgrade-guide) under `Setup arguments`.

If `app` is used instead of `App`, the following error will be produced:

```
[Vue warn]: Invalid vnode type when creating vnode: undefined.
```

**Comment by reinink** [comment]
Ahh shoot, good catch! This has been fixed 👍

https://github.com/inertiajs/inertiajs.com/commit/64d41305d10c71f779427fad22700460ce2d0e6c
