### ISSUE TITLE
Inertia.js (React) page loaded event required

### ISSUE THREAD

**Issue by vbulash** [inertiajs/inertia-laravel#501]
I need to change some geometry after Inertia.js page loaded. 
In pure JS it is `DOMContentLoaded` event. Guess Inertia.js' page similar to React component and `componentDidMount` will applicable for this. 
The problems is - `componentDidMount` is method for `React.Component` class, but Inertia.js' page just a function, not class. 
How to catch page loaded event on Inertia.js page?

**Comment by rojtjo** [comment]
You should be able to use the `useEffect` hook for this. You might also be able to hook into one of Inertia's events. 

https://reactjs.org/docs/hooks-reference.html#useeffect
https://inertiajs.com/events#event-callbacks

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
