### ISSUE TITLE
Counting items passing a where assertion

### ISSUE THREAD

**Issue by k3kornel** [inertiajs/inertia-laravel#502]
Hello, is it possible to count the items passing a where assertion?
For example I would like to assert that the response has 3 elements and there are two elements with active property = 1
products {
	"data": [
		{
			"id": 1,
			"plu": "2808",
			"name": "aut earum voluptates",
			"active": 1
		},
		{
			"id": 2,
			"plu": "5249",
			"name": "fugit et ex",
			"active": 1
		},
		{
			"id": 3,
			"plu": "6856",
			"name": "et error dolorem",
			"active": 0
		}
	]
}

Thank you

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
