### ISSUE TITLE
Feature Request : Modals Classes Prop Merge

### ISSUE THREAD

**Issue by prezire** [inertiajs/inertia-laravel#506]
It would be nice to have a mergeable classes prop for both Modal and ConfirmationModal. I was thinking of having something like this to align them vertically, for example:
```html
<Modal classes="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" :show="showModal" @close="showModal = false">
    <div class="p-3">
      Hello World
    </div>
</Modal>
 ```
Please let me know if there's a better way to do this.

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
