### ISSUE TITLE
Inertia Testing does not load eager loaded relations properly

### ISSUE THREAD

**Issue by felixele217** [inertiajs/inertia-laravel#509]
Hey guys,

for managing permission and roles we are using the awesome laravel-permission package from Spatie.

When we send a User-Model to the frontend (we are using react), we want roles.permissions to be attached always.

Therefore we added the following to our User-Model:

![image](https://user-images.githubusercontent.com/50794814/221165064-01af3baa-1f28-447a-97e9-459842d7dc9d.png)

If we inspect with React Devtools in Frontend, we see the following:

![image](https://user-images.githubusercontent.com/50794814/221165647-8032f1a0-2e90-4588-a732-c6dc47c88549.png)

Now we wrote the following test to assert, that this is happening properly:

![image](https://user-images.githubusercontent.com/50794814/221165797-f182d410-a84d-4bdd-bc01-043eb890da9b.png)

But the test fails and says the following:

![image](https://user-images.githubusercontent.com/50794814/221166044-80bda070-47bb-4fbf-854c-671ed25c6943.png)

And if we dd() the response we see this:

![image](https://user-images.githubusercontent.com/50794814/221166165-dbf55fcd-dc4d-43a4-8812-f08877baec69.png)

Somehow the permissions are not loaded with the roles but seperate in the test. Is this functionality missing for the Inertia-Testing feature or am I doing it wrong somehow?

Any help appreciated!
Greetings Felix

**Comment by flavio-paqt** [comment]
Did you check both documentations? Did you remove `0` and tested it again? 

How can we reproduce this?

**Comment by aknEvrnky** [comment]
How you pass the object to frontend? Do you use api resource which is created by `php artisan make:resource`.
It is possible to that converting the object to json may be differs when it is handled by laravel.

As I see, in your frontend root object which is auth is an object. But in your backend it is an array.

**Comment by willard-wpu** [comment]
you can use API Resource

**Comment by jessarcher** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this problem.
