### ISSUE TITLE
Link can not click and throw Error in v-on handler: "TypeError: (0 , G.default) is not a function"

### ISSUE THREAD

**Issue by huuphuong** [inertiajs/inertia-laravel#510]
Hi team, 
I have 3 component <Link /> and they are rendered in browser as <a> tag.
But when i click link, it's not redirect to new page and browser throw Error in v-on handler: "TypeError: (0 , G.default) is not a function"
`app.js?id=a1cb23da6a52057a79ee:42657 TypeError: (0 , G.default) is not a function
    at A.visit (app.js?id=a1cb23da6a52057a79ee:710:42)
    at click (app.js?id=a1cb23da6a52057a79ee:5543:87)
    at invokeWithErrorHandling (app.js?id=a1cb23da6a52057a79ee:42625:26)
    at HTMLAnchorElement.invoker (app.js?id=a1cb23da6a52057a79ee:40572:14)
    at original._wrapper (app.js?id=a1cb23da6a52057a79ee:46627:25)`

Can you guys support me this problem? 
Thanks
![image_2023-02-28_11-42-06](https://user-images.githubusercontent.com/13657033/221758280-fc48cd7c-7b13-4e7f-822b-846ec340ec7c.png)
![image_2023-02-28_11-42-06 (2)](https://user-images.githubusercontent.com/13657033/221758322-cd1328f5-0bbb-439b-92a4-1a118c1fb5a1.png)
![image_2023-02-28_11-42-06 (4)](https://user-images.githubusercontent.com/13657033/221758400-68f38e2d-a011-4491-ad7f-8566fe5d47c3.png)

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
