### ISSUE TITLE
redirect back but not clearing form and state

### ISSUE THREAD

**Issue by DeviJv** [inertiajs/inertia-laravel#513]
how to redirect back with reseting form and clear the usestate

**Comment by paulmax-os** [comment]
Assuming you're using Vue:

```javascript
const form = useForm({
    // your v-models / inputs
});

const submitForm = () => {
    form.post('/profile', {
        onSuccess: () => form.reset('password'),
    });
}
```

There are a couple of form helpers available, it's worth having a look: https://inertiajs.com/forms#form-helper

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
