### ISSUE TITLE
Using Inertia+Vite+Laravel with one Codebase but 2 Domains

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [inertiajs/inertia-laravel#519]
Hey Guys,

is it possible to create a laravel setup with Vite, Vue3 and InertiaJS to build a webseite and admin backend in one codebase but to access the website over the main domain and the admin backend over a subdomain?

Main website: example.de
Admin Backend: portal.example.de

If yea, so how can i set this?

Cheers and Thanks.

**Comment by aknEvrnky** [comment]
the correct place to ask this is not here. You may ask this on laracasts or stackoverflow.

**Comment by wwwDESIGN-basti** [comment]
ok, posted here: https://laracasts.com/discuss/channels/vite/using-inertiavitelaravel-with-one-codebase-but-2-domains
