### ISSUE TITLE
How to add a Google Analytics script?

### ISSUE THREAD

**Issue by jeangomes** [inertiajs/inertia-laravel#522]
Whats is the better way?

**Comment by rswfire** [comment]
I think he might be asking how to add scripts to the createInertiaApp() function. I think some documentation on this would be greatly appreciated; I need to add Sentry there and I could not figure it out...

(Op, are you sure you don't want to just put your scripts in the blade template?)

```
createInertiaApp({
    title: (title) => `${title}`,
    resolve: (name) => resolvePageComponent(`${name}.vue`, import.meta.glob(/**/*.vue')),
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue)
            .use(flareVue)

// somehow, Sentry needs to go here; perhaps he's trying to add Google Analytics here?
            .mount(el)
    },
```

**Comment by rswfire** [comment]
Have you tried placing it in your app.blade.php file?

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
