### ISSUE TITLE
can not found callSilently

### ISSUE THREAD

**Issue by yunshuaip** [inertiajs/inertia-laravel#524]
inertiajs version: 0.6.9
laravel version: 6.x

When I use inertiajs within laravel, I can not found this method https://github.com/inertiajs/inertia-laravel/blob/v0.6.9/src/Commands/StartSsr.php#L53

But I can found another method called callSilent https://github.com/laravel/framework/blob/6.x/src/Illuminate/Console/Concerns/CallsCommands.php#L38

I am not sure is a feature or a bug. Could you investigate this issue?

**Comment by jameshulse** [comment]
It looks like `callSilently` was added in Laravel 8.x so it's a Laravel version support issue. I'm not sure which versions of Laravel Inertia aims to support, but it apparently won't support 6.x when using SSR currently.

If upgrading Laravel to 8.x isn't possible, then if I were you I would fork the package and change that line to "callSilent". You could open a pull request too.

**Comment by yunshuaip** [comment]
It works at laravel10.x. I close this issue now.
