### ISSUE TITLE
How to handle load balancing and asset versioning

### ISSUE THREAD

**Issue by HarryLee186** [inertiajs/inertia-laravel#525]
Hi,

Assuming a scenario where a Laravel application is load balanced across multiple server, and assets are built for production using Vite on each server, how would one handle the asset versioning for Inertia? Each `build/manifest.json` returns a separate md5 string, so every request ends up resulting in a 409.

Open to ideas, I'm aware one could build assets in one location and copy them over to each server, set an asset_url and serve the assets from a subdomain, override the default `version()` functionality etc, but I'm curious as to whether there is a fairly standard solution to this.

**Comment by marcuschristiansen** [comment]
We ran into the same problem. We enabled sticky sessions on the load balancer which seems to have resolved the issue.

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!

**Comment by oheck** [comment]
In case anyone still stumbles upon this issue...

While ultimately centralized assets is the more scalable approach, you can make this work with just a few changes by adjusting the version() method and the vite.config.js. 

See full example [here](https://www.blackbits.io/blog/why-inertia-breaks-across-multiple-servers).
