### ISSUE TITLE
nginx header limitation

### ISSUE THREAD

**Issue by dnkmdg** [inertiajs/inertia-laravel#529]
Opening this issue to aid others running into a somewhat bizarre issue, might also be cause for some documentation. 

When applying the `@inertia` directive the yielded result contains both the page template and links for all dynamically fetched modules and styles. Recently we started seeing `502 Bad Gateway`errors when navigating directly to certain routes in our app, but not when arriving at the same routes from programmatic navigation ie. SPA navigation. After some debugging we found that all of the rendered `<script>` tags caused response header section `links` to blow up, thereby causing nginx to fail with a 502. 

The solution for this is to increase nginx buffers:
```bash
proxy_buffer_size   4096k;
proxy_buffers   128 4096k;
proxy_busy_buffers_size   4096k;
```

A single response could easily look like this, where the "link" section alone is too much for the standard configuration of nginx to handle.
```bash
server	nginx
content-type	text/html; charset=UTF-8
vary	Accept-Encoding
cache-control	no-cache, private
date	Wed, 21 Jun 2023 13:39:41 GMT
link	<https://my-production-inertia-app.io/build/assets/app-70b4ce10.css>; rel="preload"; as="style", <https://my-production-inertia-app.io/build/assets/CoolCard-15f160be.css>; rel="preload"; as="style", <https://my-production-inertia-app.io/build/assets/AuthenticatedLayout-55f1c4db.css>; rel="preload"; as="style", <https://my-production-inertia-app.io/build/assets/FileUpload-aad0cdad.css>; rel="preload"; as="style", <https://my-production-inertia-app.io/build/assets/ImageGallery-6f214b75.css>; rel="preload"; as="style", <https://my-production-inertia-app.io/build/assets/CoolSelect-8cfc798d.css>; rel="preload"; as="style", <https://my-production-inertia-app.io/build/assets/Show-f86228ba.css>; rel="preload"; as="style", <https://my-production-inertia-app.io/build/assets/app-af524a63.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/Show-d2c761ab.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/GlobalSearchModal-038356f7.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/TextInput-7c60560f.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/UiStore-1d771fae.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/Toast-46e71053.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/BaseButton-9b394d38.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/PrimaryButton-2cf62d91.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/UnderlinedLink-6a468b5c.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/AnonDialog-e37a92bf.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/OutlineButton-76aafa00.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/ImageControls-ccbc8a04.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/CoolCard-30520ede.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/InputError-74da528d.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/index-41b1ba78.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/ShippingItem-ce415210.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/vue-drawing-canvas.esm-f7af890c.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/file-2ba84ccc.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/date-cdab97b8.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/WhiteButton-30bc2cb4.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/PickingLayout-29a854e6.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/use-tracked-pointer-b8f4a78b.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/use-resolve-button-type-3ac7b00a.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/use-controllable-e9af45ec.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/mitt-3a6e1e85.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/_plugin-vue_export-helper-c27b6911.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/FileUpload-5dd25a12.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/ImageGallery-645e2648.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/DangerButton-84d21b86.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/CoolSelect-b9092254.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/ApplicationLogo-6e0281ba.js>; rel="modulepreload", <https://my-production-inertia-app.io/build/assets/ToastArea-73aadd4a.js>; rel="modulepreload"
vary	X-Inertia
```

**Comment by trippo** [comment]
I have the same problem... a route gives me a `502 Bad Gateway` error...
If I remove a component and put its code directly inside the page content all work fine...

But this configuration don't solve the problem... 
```
proxy_buffer_size   4096k;
proxy_buffers   128 4096k;
proxy_busy_buffers_size   4096k;
```
How can I solve this problem?

**Comment by trippo** [comment]
I solve with
```
	fastcgi_buffers 128 4k;
	fastcgi_buffer_size 12k;
	fastcgi_busy_buffers_size 16k;
```

**Comment by jessarcher** [comment]
Thanks for sharing your insights! Going to close this one but feel free to continue the discussion :slightly_smiling_face:

**Comment by FerVillanuevas** [comment]
The proxy solution works fine for me with Octane

proxy_buffer_size   4096k;
proxy_buffers   128 4096k;
proxy_busy_buffers_size   4096k;

thanks @trippo

**Comment by rstefanic** [comment]
This was a life safer. Thank you @dnkmdg. I have been banging my head against a wall trying to fix it for a couple of days now. In my case, we weren't getting a 502 error. The response was a blank page with no content and a 200 status response. The HTTP message body was 0 bytes _every time_.

It wasn't until I added an extra header that I got the 502 error and then stumbled upon this post. I checked the header size that page was returning, and the header was **4.6kb**! Our machine running the Inertia application had the default `fastcgi_buffer_size` of 4k (which is the NGINX default taken the host machine's page size). Bumping it up to 8k is what did the trick for us and everything's working smoothly!

```
fastcgi_buffer_size 8k;
```

**Comment by GDanielRG** [comment]
> This was a life safer. Thank you @dnkmdg. I have been banging my head against a wall trying to fix it for a couple of days now. In my case, we weren't getting a 502 error. The response was a blank page with no content and a 200 status response. The HTTP message body was 0 bytes _every time_.
> 
> It wasn't until I added an extra header that I got the 502 error and then stumbled upon this post. I checked the header size that page was returning, and the header was **4.6kb**! Our machine running the Inertia application had the default `fastcgi_buffer_size` of 4k (which is the NGINX default taken the host machine's page size). Bumping it up to 8k is what did the trick for us and everything's working smoothly!
> 
> ```
> fastcgi_buffer_size 8k;
> ```

Was having random Nginx errors, the fastest way I found how to replicate it was going to a specific page and just reloading and i would get the nginx error. So its different if inertia loads the page initially with html or just sends the json on subsequent requests. Either way this fixed it and you are a savior for me and 2 of my customers.  Thanks!

**Comment by aigletter** [comment]
It was helpful for me. 
I needed both options. I used Nginx Proxy Manager and it was solved with fastcgi_* directives for nginx of my application and proxy_* directives for Nginx Proxy Manager.
Thank you all very much!

**Comment by alamgir-napollo** [comment]
proxy_buffer_size   4096k;
proxy_buffers   128 4096k;
proxy_busy_buffers_size   4096k;
Everyone talking to add these line but where to add this line as i am using plesk where i deployed laravel with inertia and react js?

**Comment by Barbapapazes** [comment]
> proxy_buffer_size 4096k; proxy_buffers 128 4096k; proxy_busy_buffers_size 4096k; Everyone talking to add these line but where to add this line as i am using plesk where i deployed laravel with inertia and react js?

In your nginx config: 

```nginx
server {
    location ~ \.php$ {
        fastcgi_buffer_size 8k;
    }
}
```

**Comment by iamnurr** [comment]
Default **path** for nginx config will be
 ```php
 /etc/nginx/nginx.conf
 ```
you can open it with nano using the **command**
```php
sudo nano /etc/nginx/nginx.conf
````

and only need to add in the **http block** 
```php
fastcgi_buffer_size 8k;
```
save it and restart the nginx.

![Screenshot from 2024-12-30 19-37-33](https://github.com/user-attachments/assets/ef2a612e-8f34-465c-82d8-658e3de3e89e)

Also, it can be added on the server block inside the location php block.

![Screenshot from 2024-12-30 19-48-39](https://github.com/user-attachments/assets/d00cc970-b512-44d4-97ab-aa13c47d10a2)

**Comment by JharoldCataluna** [comment]
I love you guyz. This fixed my issue

**Comment by syamsoul** [comment]
is this the best solution or is there better solution?

**Comment by dnkmdg** [comment]
> is this the best solution or is there better solution?

Yes, this is effectively the only viable solution. The core issue stems from Inertia sending large and complex headers that exceed default Nginx buffer limits.

To handle this gracefully, Nginx must be explicitly configured to allow larger buffer sizes. This isn’t a workaround or a hack; it’s a standard server configuration adjustment, similar to increasing PHP’s `memory_limit` or `post_max_size` settings. These adjustments are common and necessary when dealing with modern frameworks and large payloads.

**Comment by JohnDotOwl** [comment]
Thank you guys! I got so confused when this issue came out. Thank god claude analysed the logs and directed me here 

Laravel Octane (High-Performance)
```
proxy_buffer_size           128k;
proxy_buffers               4 256k;
proxy_busy_buffers_size     256k;
```

PHP-FPM (Traditional)
```
fastcgi_buffers 128 4k;
fastcgi_buffer_size 12k;
fastcgi_busy_buffers_size 16k;
```

**Comment by lauroguedes** [comment]
Hello everyone, thank you so much. I suspected that the issue might be with the SSR server and my code. I spent nearly a week trying to solve the problem using AI, and what ultimately helped me was a simple Google search. This is quite ironic!

**Comment by petert82** [comment]
Is there documentation somewhere on which Inertia functionality is responsible for adding content to the `link` header?

i.e. how can I (or can I not?) avoid my app adding 10KB+ of header content in the first place?

**Comment by dnkmdg** [comment]
> Is there documentation somewhere on which Inertia functionality is responsible for adding content to the `link` header?
> 
> i.e. how can I (or can I not?) avoid my app adding 10KB+ of header content in the first place?

I’d say you can’t - since the data added in the headers is everything built in your app you’d either need to produce a single-file bundle or heavily reduce the amount of components. 

I suppose @jessarcher could give a more detailed insight in the underlying mechanics but it feels risky to remove stuff from there.
