### ISSUE TITLE
Error When Run Command Inertia:SSR in Server

### ISSUE THREAD

**Issue by dimyatiutoyo** [inertiajs/inertia-laravel#533]
I got error when running command `php artisan inertia:ssr` in centos8 server. In local development, it is fine, no problem.
The error is "`There are no commands defined in the "inertia" namespace.`"
Can you all help me?

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
