### ISSUE TITLE
Unable to get SSR Working on Laravel 10-Jetstream-Vue3

### ISSUE THREAD

**Issue by muthiyalu** [inertiajs/inertia-laravel#536]
Hello,

after many attempts at trying to get SSR on Jetstream work, following standard procedures and steps in the official documentation. I came across this article .https://whoknows.tech/posts/8/ssr-vilt-laravel-seo

It seems there is an issue . Is there a fix to the issues highlighted in that article or is there something else I am missing?

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
