### ISSUE TITLE
Inertia link blocks the toggle menu and nav of my template admin

### ISSUE THREAD

**Issue by ingcol** [inertiajs/inertia-laravel#541]
I use inertia with laravel, and I have a template manager. When you load the site, the browser and the toggle menu work. However, when I click on an internia link it disables the entire browser and toogle-menu

https://github.com/inertiajs/inertia-laravel/assets/22689367/129e68af-5eb6-4e10-9cfb-d7e45cccae9c

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
