### ISSUE TITLE
Connecting to an external host using NodeJS

### ISSUE THREAD

**Issue by DlouhyDavid** [inertiajs/inertia-laravel#546]
Is there a way to link Laravel to use a node process from another host? Specifically, I have a container with PHP. Then I have a second container with NodeJS. I want SSR to work and Laravel to use the Node container from the PHP container.

**Comment by jessarcher** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question that may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use the functionality provided by this repository, you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked, and everyone is free to discuss solutions to your problem!
