### ISSUE TITLE
Redirect Back issue

### ISSUE THREAD

**Issue by stescacom** [inertiajs/inertia-laravel#551]
This caught me by surprise, In dev response `back()` would redirect back to the proper page. In production inertia shows a modal with the statement `{} redirecting to ....` What is causing this issue?

I have tried `to_route()` as well. The first redirect on this is proper, recurring redirect shows the modal again.

**Comment by reinink** [comment]
Hey! So without more information (a code snippet) or git repo demonstrating this issue it's really hard to help out here. Based on what you're saying I can even think of any common issues that people run into here. Going to close this one for now, but if you're able to share a minimal reproduction I'd be happy to have another look 👍
