### ISSUE TITLE
Multiple definitions exist for class 'Route'

### ISSUE THREAD

**Issue by galtsevt** [inertiajs/inertia-laravel#557]
What is this for? I don't like that ide underlines my code.

![image](https://github.com/inertiajs/inertia-laravel/assets/104002161/13d04af3-16fd-4e4b-95d0-25ac73cc0cef)

**Comment by johnpyp** [comment]
If anyone is still having this issue, I recommend you use https://github.com/barryvdh/laravel-ide-helper to unify and normalize the type definitions. Seems to make everything more well behaved.

**Comment by driesvints** [comment]
Thanks @johnpyp

**Comment by galtsevt** [comment]
> If anyone is still having this issue, I recommend you use https://github.com/barryvdh/laravel-ide-helper to unify and normalize the type definitions. Seems to make everything more well behaved.

I don't need this package
