### ISSUE TITLE
Improve developer experience for handling server errors

### ISSUE THREAD

**Issue by sebastiandedeyne** [inertiajs/inertia-laravel#56]
There's a lot of confusion around error handling at the moment. When a server error happens, Laravel returns a non-Inertia response, which means Inertia renders the response in a modal.

People often ask for a way to disable the modal behaviour. This is not the idiomatic solution to the problem; the correct solution is to ensure your server _always_ returns an Inertia response.

In Laravel, this can be achieved by modifying the [exception handler](https://github.com/laravel/laravel/blob/bb433725483803a27f21d3b21317072610bc3e9c/app/Exceptions/Handler.php#L40-L50).

A basic example:

```php
public function render($request, Exception $exception)
{
    if ($exception instanceof ModelNotFoundException) {
        return Inertia::render('Errors/NotFound');
    }

    return parent::render($request, $exception);
}
```

This is a tedious job; you need to ensure you've caught all default Laravel cases, and it's a lot of boilerplate code to add to every project. 

Laravel's default bahaviour is to render a Blade view based on the error's response code, like `errors.404`, `errors.500` etc. The inertia-laravel package could mimic this method.

```php
public function render($request, Exception $exception)
{
    return Inertia::renderException($request, $exception);
}
```

We could also ship a "check" for applications with multiple parts, including non-Inertia parts like an API or separate homepage.

```php
public function render($request, Exception $exception)
{
    if (Inertia::isInertiaRequest($request)) {
        return Inertia::renderException($request, $exception);
    }

    return parent::render($request, $exception);
}
```

This would return an response with a standardized component name, for example `Inertia::render('Errors/NotFound')`. Note that JavaScript functions aren't allowed to start with a number, so we'd need to either use explicit names (`NotFound`), or a prefix (`Error404`).

What needs to be done?

- First of all, this idea needs to be validated. Looking for input!
- We'd need to create a mapping of Laravel exceptions to component names
- There needs to be a way to specify the response code in `Inertia::render`

**Comment by reinink** [comment]
I just [updated the docs](https://inertiajs.com/error-handling) with a pretty straight forward solution:

```php
use Inertia\Inertia;

public function render($request, Exception $exception)
{
    $response = parent::render($request, $exception);

    if ($request->header('X-Inertia') && in_array($response->status(), [500, 503, 404, 403])) {
        return Inertia::render('Error', ['status' => $response->status()])
            ->toResponse($request)
            ->setStatusCode($response->status());
    }

    return $response;
}
```

Basically I decided it was an act of futility to try and figure out every possible exception that could get thrown. Instead, I just let Laravel generate the correct `Response`, and I use that decide whether I want to show an Inertia error page.

A corresponding error page component could look like this:

```vue
<template>
  <div>
    <h1>{{ title }}</h1>
    <div>{{ description }}</div>
  </div>
</template>

<script>
export default {
  props: {
    status: Number,
  },
  computed: {
    title() {
      return {
        503: '503: Service Unavailable',
        500: '500: Server Error',
        404: '404: Page Not Found',
        403: '404: Forbidden',
      }[this.status]
    },
    description() {
      return {
        503: 'Sorry, we are doing some maintenance. Please check back soon.',
        500: 'Whoops, something went wrong on our servers.',
        404: 'Sorry, the page you are looking for could not be found.',
        403: 'Sorry, you are forbidden from accessing this page.',
      }[this.status]
    },
  },
}
</script>
```

This gives developers tons of flexibility to create their own custom designed error pages.

I'm kind of happy with this as a final solution. I'm not sure this library needs to do anything more...although I'm still open to it.

**Comment by reinink** [comment]
I guess we could do something like this:

```php
public function render($request, Exception $exception)
{
    return Inertia::renderErrorResponse(
        string $component,
        Response $response,
        array $codes
    );
}
```

For example:

```php
public function render($request, Exception $exception)
{
    return Inertia::renderErrorResponse(
        'Error',
        parent::render($request, $exception),
        [500, 503, 404, 403]
    );
}
```

Again, not sure that this is worth adding to the framework, since it really doesn't require that much code to just do this yourself.

**Comment by reinink** [comment]
Closing this, because I think the above solution is actually perfect. 👌

**Comment by kevnk** [comment]
I've implemented the solution outlined in the docs, but anytime I run into a 403, it's still showing laravel's stubbed 403 page... Any ideas why this might be happening?

**Comment by kevnk** [comment]
Never mind... 🤦 I was testing locally so I got rid of the `!app()->environment(['local', 'testing'])` condition and I can see everything now...

**Comment by cristian807** [comment]
Hello!

I have gotten an error when taking my app to production in a shared hosting (cpanel).

The error is that when I try to render a view, it does not render as such, but instead displays the data coming from the controller in a modal.

How can I solve this?

Thank you.
