### ISSUE TITLE
Show toast or message after request complete.

### ISSUE THREAD

**Issue by Minhazul-Islam18** [inertiajs/inertia-laravel#563]
Hey there.
I'm pretty new to Inertia. Using Vue3, I would like to do something like this if I hit the route and my process is completed then show a message/Toast to let the user know about processes.

Like I update something in the database, then now shows the toast that "Updated successfully." 
Thanks in advance, I've tried every possible way that I've found on the internet. But alas!

**Comment by davadams97** [comment]
Have you looked into router [events](https://inertiajs.com/events#registering-listeners)?

**Comment by Minhazul-Islam18** [comment]
Yeah, I'm doing it another way and have seen this also. both works. thanks.
