### ISSUE TITLE
Login not working with Laravel + Inertia + React

### ISSUE THREAD

**Issue by Hernanarica** [inertiajs/inertia-laravel#567]
Hello, I realized that Laravel's manual authentication does not work with inertia, I am doing everything as the documentation says but the user's credentials are not kept saved.

**web.php**
<img width="1055" alt="Captura de pantalla 2023-12-04 a las 22 57 49" src="https://github.com/inertiajs/inertia-laravel/assets/44417976/b3013d84-1c21-4554-9e49-0065be227cef">

**AuthController**
<img width="503" alt="Captura de pantalla 2023-12-04 a las 22 57 40" src="https://github.com/inertiajs/inertia-laravel/assets/44417976/379b10e6-0b89-4b16-a78b-4cc8ea5f4b16">

**SignIn view React**
<img width="840" alt="Captura de pantalla 2023-12-04 a las 22 57 54" src="https://github.com/inertiajs/inertia-laravel/assets/44417976/af16ce32-4710-429b-998b-8b52f869f57e">

**HandleInertiaRequest**
<img width="784" alt="Captura de pantalla 2023-12-04 a las 23 32 19" src="https://github.com/inertiajs/inertia-laravel/assets/44417976/a3e1038f-353e-46e3-9685-9fe40c11c848">

**Error**
<img width="1187" alt="Captura de pantalla 2023-12-04 a las 23 32 38" src="https://github.com/inertiajs/inertia-laravel/assets/44417976/36bf6129-53ec-4737-8e74-7b7afffd666d">

**Comment by taylorotwell** [comment]
I would suggest looking at how the Laravel Breeze + React Inertia stack works.

**Comment by FuzzyNat26** [comment]
Hi! @Hernanarica

I know this issue has been closed, but I've encountered the same situation. Have you made any discovery regarding this topic?

**Comment by Hernanarica** [comment]
@FuzzyNat26 Hello! Yes, since I was never able to solve it from the programming side, what I did was create a new project and start everything from scratch, migrating the views, controllers, etc., etc., and the authentication now worked.

**Comment by FuzzyNat26** [comment]
Thanks for the reply.

I came across the same conclusion, which is pretty weird on what's bugged out the authentication.

**Comment by smif15** [comment]
I know it's outdated.
But I had the same problem before, and I've already solved it.
In my case, the issue happened because I **moved users table migration to a new file.** When I moved the users table back to the default migration file created when the project was first initialized, the problem was solved.
