### ISSUE TITLE
Laravel / Vue 3 Install Issues

### ISSUE THREAD

**Issue by Zenkylo** [inertiajs/inertia-laravel#578]
The installation guide for adding Inertia with Vue 3 to Laravel is out dated or inaccurate. I suggest going through the installation pages on a boilerplate Laravel app to witness.

For those who also spent hours following the install guide I'd suggest taking the install guide as far as you can, then visit the Laravel.com pages below to piece together the lapse in documentation.

https://laravel.com/docs/10.x/vite#vue
https://laravel.com/docs/10.x/vite#inertia

**Comment by driesvints** [comment]
We'd really appreciate PR's for this, thanks.
