### ISSUE TITLE
Inertia with Laravel + SSR + pm2

### ISSUE THREAD

**Issue by svkmedia** [inertiajs/inertia-laravel#579]
Hi 
we successfully deployed our app to server.
App is built in Laravel + Inertia and is using SSR.
Everything works as expected but sometimes we get following error:

fread(): supplied resource is not a valid stream resource
"/vendor/symfony/process/Pipes/UnixPipes.php:122"

We are using pm2 process manager to take care about SSR.
Any idea what's the reason of error?
Everything is working fine just sometimes this error pops in laravel log...

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
