### ISSUE TITLE
Add shared key only if not null?

### ISSUE THREAD

**Issue by rakk7** [inertiajs/inertia-laravel#58]
For now, when adding a shared data, you must set a key for the shared data.
```php
Inertia::share('auth.user', function () {
    if ($NotNull) {
        return [
            'key' => 'value',
        ];
    }
});
```
If this key didn't pass the if statement, the key will have a `null` as a value.

Is there a way to add a shared key in this way:
```php
Inertia::share(function () {
    $sharedData = [];

    if ($NotNull) {
        $sharedData['some-key'] = [
            'key' => 'value',
        ];
    }

    if ($NotNull) {
        $sharedData['some-key-2'] = [
            'key' => 'value',
        ];
    }

    return $sharedData;
});
```

This way the key will be shared only if it has some value. I don't want to have many shared keys with "null" values.

**Comment by sebastiandedeyne** [comment]
What's wrong with sharing keys with null values? Imo it's better to explicitly have them there than to silently omit them when empty.

**Comment by rakk7** [comment]
Never mind, found a way around this. closing.
