### ISSUE TITLE
Safari can not handle redirect()->back()

### ISSUE THREAD

**Issue by StefanNeuser** [inertiajs/inertia-laravel#581]
When we use `return redirect()->back()` instead of `return redirect()->route(...)` Safari is going to load `/` root url. Anybody also forcing that problem? We have that issue only in Safari within a iFrame application so far :-( 

Replacing back() with route() is not the way to go about it because of the Validation handling with a redirect()->back() 

Any ideas, what could cause to that issue?

**Comment by RobertBoes** [comment]
That sounds like a cookie/session and/or referer issue. Laravel uses the referer to determine the previous URL (https://github.com/laravel/framework/blob/10.x/src/Illuminate/Routing/UrlGenerator.php#L166) with a fallback to sessions.
For example, if you're using a `Referrer-Policy` and have it set to `origin` the browser would only send the domain as the referrer, thus Laravel would interpret that as being the previous page URL. If it's not sent at all (`no-referrer`) then Laravel will fallback to sessions.
