### ISSUE TITLE
$page variable cannot be found

### ISSUE THREAD

**Issue by kapsonic** [inertiajs/inertia-laravel#59]
I have set it up and run this to test.
I am getting following error
Undefined variable: page (View: /var/www/resources/views/layouts/app.blade.php) (View: /var/www/resources/views/layouts/app.blade.php)

Below is my main view
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">
    <script src="{{ mix('/js/app.js') }}" defer></script>
</head>
<body>

@inertia

</body>
</html>
`

and Controller 
`<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class WelcomeController
{
    public function show()
    {
        return Inertia::render('Event')->with('event', "Good");
    }
}
`

Please help

**Comment by kapsonic** [comment]
Just after submitting this issue I figured it out.
Sorry. Closing

**Comment by msslgomez** [comment]
How did you fix it?

**Comment by smbdelse** [comment]
@kapsonic or @msslgomez, did you resolve the issue? Can explain it?

**Comment by smbdelse** [comment]
Blade file was ok, it ended up to be a stupid problem with a controller (just a typo). Thanks anyway! :)

**Comment by mizanur75** [comment]
> Just after submitting this issue I figured it out.
> Sorry. Closing

How could you solve?

**Comment by riddla** [comment]
This "Undefined variable $page" error might happen, if your routing doesn't respond with an inertia response.

You can respond within a controller as shown in https://inertiajs.com/responses#creating-responses.

```php
// routes/web.php
Route::get('/demo', [DemoController::class, 'show']);
```

```php
<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

class DemoController extends Controller
{
    public function show(): Response
    {
        return Inertia::render('Demo', [
            'demodata' => 'foobar',
        ]);
    }
}
```

--- 

Or you can shortcut the routing as mentioned at https://inertiajs.com/routing#route-helpers:

```php
// routes/web.php
Route::inertia('/demo', 'Demo');
```

**Comment by kmuenkel** [comment]
I was able to clear this error just by running `php artisan optimize:clear`. Turned out there was an old "{any}" route still cached from before Breeze overwrote it.

**Comment by Daeoss** [comment]
![image](https://github.com/inertiajs/inertia-laravel/assets/146491276/d3e6b23f-7647-49fb-97cd-27590144bd5e)

What worked for me was switching from view('app') to inertia('app')
