### ISSUE TITLE
There is no automatic follow protocol, http is used under https, how to solve it

### ISSUE THREAD

**Issue by phpmac** [inertiajs/inertia-laravel#602]
There is no automatic follow protocol, http is used under https, how to solve it

**Comment by phpmac** [comment]
不知道在哪里设置选择，跟随协议还是定义协议(http|https)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by phpmac** [comment]
What is generated by route() in the vue file is not https. How to solve it? ? I encountered this problem using laravel11, please advise

**Comment by RobertBoes** [comment]
@phpmac That has nothing to do with Inertia, the `route()` helper is provided by https://github.com/tighten/ziggy. Likely it's a setup issue, for example using a reverse proxy and not having the `TrustProxies` middleware set up properly, so Laravel doesn't detect it's served through HTTPS and thus Ziggy would generate http URLs.
