### ISSUE TITLE
Laravel 11 update and Nova issue

### ISSUE THREAD

**Issue by rbruhn** [inertiajs/inertia-laravel#603]
When trying to update from Laravel 10 to Laravel 11, Nova v4 requires a lower version of inertia-laravel making it impossible to update.

```
laravel/nova 4.27.13 requires inertiajs/inertia-laravel ^0.4.5|^0.5.2|^0.6.0 -> satisfiable by inertiajs/inertia-laravel[v0.4.5, ..., v0.6.11].
```

I opened an issue with Nova but it was moved to discussion for some reason. It seems the composer.json files need to be updated accordingly for the new versions unless there is some conflict? In the Nova update docs, there is nothing about updating inertiajs/inertia-laravel. 
https://github.com/laravel/nova-issues/discussions/6283

**Comment by driesvints** [comment]
Nova supports Inertia v1 as off v4.33.0 so just update to that version and you should be good.

**Comment by rbruhn** [comment]
Meaning, I have to renew my license for $249. Thx.

**Comment by liamjoc** [comment]
@driesvints will Larave Nova support Inertia v2 in an upcoming release? I can't seem to upgrade Laravel inertia?
