### ISSUE TITLE
-

### ISSUE THREAD

**Issue by mickedplay** [inertiajs/inertia-laravel#608]
-

**Comment by driesvints** [comment]
Thanks. Unfortunately we cannot provide support for external packages. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
