### ISSUE TITLE
redirection to /dashboard after login does not work

### ISSUE THREAD

**Issue by albertopinilla** [inertiajs/inertia-laravel#609]
### Version:

- `@inertiajs/vue3` version: #.#.#

### Describe the problem:

I just installed Laravel 11 with the laravel new installer, using Laravel Breeze with Inertia.js and Vue 3. After creating the migrations and registering a user, I cannot log in. The exception that occurs is Illuminate\\Auth\\AuthenticationException: Unauthenticated, even though the credentials are correct. I notice that it makes a GET request to dashboard?%2Fdashboard, but it returns nothing.

### Steps to reproduce:

I did a clean installation with laravel new. The strange thing is that if I use a SQLite database, it works, but it doesn't work with MySQL.

**Comment by driesvints** [comment]
Just tried a fresh setup. I can login just fine. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
