### ISSUE TITLE
Ziggy2.0 and Laravel11 and Breeze for Inertia + React, TypeScript and SSR starter kit throws error on initial setting

### ISSUE THREAD

**Issue by tokstar** [inertiajs/inertia-laravel#612]

**Comment by tokstar** [comment]
Using official starter kit from Laravel website, 
composer create-project laravel/laravel example-app
composer require laravel/breeze --dev
and enabled, React, Typescript, SSR option.  
Then run npm run dev and npm run build ,
I get error says 

````

resources/js/ssr.tsx:18:17 - error TS2769: No overload matches this call.
  Overload 1 of 4, '(name: string & {}, params?: RouteParams<string & {}> | undefined, absolute?: boolean | undefined, config?: Config | undefined): string', gave the following error.
    Argument of type 'ParameterValue | RouteParams<string & {}> | undefined' is not assignable to parameter of type 'RouteParams<string & {}> | undefined'.
      Type 'string' is not assignable to type 'RouteParams<string & {}> | undefined'.
  Overload 2 of 4, '(name: string & {}, params?: ParameterValue | undefined, absolute?: boolean | undefined, config?: Config | undefined): string', gave the following error.
    Argument of type 'ParameterValue | RouteParams<string & {}> | undefined' is not assignable to parameter of type 'ParameterValue | undefined'.
      Type 'GenericRouteParamsObject' is not assignable to type 'ParameterValue | undefined'.
        Type 'GenericRouteParamsObject' is not assignable to type 'DefaultRoutable'.
          Property 'id' is missing in type 'GenericRouteParamsObject' but required in type '{ id: RawParameterValue; }'.
  Overload 3 of 4, '(name: undefined, params: undefined, absolute?: boolean | undefined, config?: Config | undefined): Router', gave the following error.
    Argument of type 'string & {}' is not assignable to parameter of type 'undefined'.

18                 route(name, params, absolute, {
                   ~~~~~

  vendor/tightenco/ziggy/src/js/index.d.ts:35:26
    35 type DefaultRoutable = { id: RawParameterValue } & Record<keyof any, unknown>;
                                ~~
    'id' is declared here.


Found 1 error in resources/js/ssr.tsx:18


````

with ZIggy 2.0, SSR is not working as default starter kit.  Could anyone can show me how to fix this ???    Many thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
