### ISSUE TITLE
Inertia components/hooks wrapped with redux Provider stopped working

### ISSUE THREAD

**Issue by domjesus** [inertiajs/inertia-laravel#614]
Hello everyone. I don't know if here is the correct place to this, if don't feel free to guide me. I'm using Laravel 10 with Inertia. Now I'm trying to integrate a layout that uses redux to manage UI state. I noticed that when I imported the redux tools 

`import { configureStore } from "@reduxjs/toolkit";`
`import rootReducer from "./slices";`
`import { Provider } from "react-redux";`

`const store = configureStore({ reducer: rootReducer, devTools: false });`

 and wrapped the App component with provider 

`<Provider store={store}>`
`    <App {...props} />`
`</Provider>` 

some Inertia features stopped working, such as Link component and form submission like `post(route("login"))`, showing on console the error `@inertiajs_react.js?v=d680deed:3399 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x-inertia')
    at C.isInertiaResponse (@inertiajs_react.js?v=d680deed:3399:45)
    at @inertiajs_react.js?v=d680deed:3441:17`

<img width="578" alt="image" src="https://github.com/inertiajs/inertia-laravel/assets/8082632/0779f816-a21d-471e-91a2-7193e369c4d2">

The requests (GET or POST), through Link or hook forms don't even reachs the backend.

The routes on backend are still working and when I changed a Link to a `<a></a>` tag works, but full reloading the page. If someone can help me I'll really appreciate. 

Thank you very much.

My stack:
Laravel Version: 10.48.8
InertiaJS/React: 1.0.0 
Vite: 4.0.0
React 18.2.0.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by domjesus** [comment]
Thank you for your directions. I’ll try these channels.


Wandeir Carneiro


Em qui., 25 de abr. de 2024 às 04:21, Dries Vints ***@***.***>
escreveu:
