### ISSUE TITLE
SSR high CPU usage

### ISSUE THREAD

**Issue by akorajac** [inertiajs/inertia-laravel#616]
I have a website with a documentation page, majority of the docs pages display code in a json format, the biggest of them is 1k lines. When I run SSR, I notice that my digitalcoean droplet CPU usage skyrockets to 100%.

-I use Laravel 11
-Installed inertiajs ssr via `php artisan breeze:install vue --ssr`
-My digitalocean droplet 2GB ram, 50GB storage

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
