### ISSUE TITLE
Default Layout

### ISSUE THREAD

**Issue by forgecodex** [inertiajs/inertia-laravel#628]
copy and paste

https://inertiajs.com/pages#default-layouts

<img width="941" alt="Screenshot 2024-05-26 at 10 29 04 AM" src="https://github.com/inertiajs/inertia-laravel/assets/79809955/6d1c1bc0-9635-400c-b7d8-8c3d6f0c12d1">
npm run build

<img width="1038" alt="Screenshot 2024-05-26 at 10 35 45 AM" src="https://github.com/inertiajs/inertia-laravel/assets/79809955/b8a32be2-84a5-419f-9741-295fed0d2582">

There is no build js 
but if I don't use default layout

<img width="1113" alt="Screenshot 2024-05-26 at 10 30 37 AM" src="https://github.com/inertiajs/inertia-laravel/assets/79809955/1f570ac7-0b54-4a0b-8346-22a1c2b45611">

everything is normal

<img width="1107" alt="Screenshot 2024-05-26 at 10 31 17 AM" src="https://github.com/inertiajs/inertia-laravel/assets/79809955/abdb3832-e982-4a5c-9dee-03e5f59f930f">

 how to fix it. 
Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
