### ISSUE TITLE
Running inertia:start-ssr continuosly fails with message 'Node.js v18.19.0'

### ISSUE THREAD

**Issue by admench** [inertiajs/inertia-laravel#637]
Using the following stack

Laravel 11.4.0
inertiajs/inertia-laravel: 1.2.0

@inertia/vue3 1.1.0
vue 3.4.27

I cannot run the `inertia:start-ssr` command. (FYI I'm doing this on Forge using the built in toggle to turn inertia ssr on).

This exception is thrown continuously as a result of the Daemon retrying.

[scratch_17.json](https://github.com/user-attachments/files/15657427/scratch_17.json)

```
  "class": "Inertia\\Ssr\\SsrException",
  "file": "\/home\/forge\/mysite.com\/vendor\/inertiajs\/inertia-laravel\/src\/Commands\/StartSsr.php",
  "line": 84,
  "message": "\nNode.js v18.19.0\n",
  "context": null,
```

**Comment by craigrileyuk** [comment]
Do you have access to a shell for your server?

If so, what happens if you run `node bootstrap/ssr/ssr.js`  (or wherever your SSR entry file compiles to) directly rather than through the PHP command?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
