### ISSUE TITLE
Using inertia component inside blade file

### ISSUE THREAD

**Issue by mouayed-keziz** [inertiajs/inertia-laravel#644]
Is it possible to include an inertia component inside a blade file (while passing props from the controller to the blade view to the inertia component) .. or u should strictly declare if a specific page is gonna use inertia or blade view

Im thinking about something similar to livewire's integration inside blade files (livewire is blade at the end of the day but could inertia go there one day?)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
