### ISSUE TITLE
SSR Not Rendering Content After Changing Default Port

### ISSUE THREAD

**Issue by DevShaded** [inertiajs/inertia-laravel#647]
I recently attempted to change the SSR port in the `ssr.js` file from the default `13714` to `13715`. However, after making this change, the server-rendered content is not appearing in the browser source code.

#### Steps to Reproduce
1. Changed the port in `ssr.js` from `13714` to `13715`.
2. Ran the command `php artisan inertia:start-ssr`.
3. Observed the source code in the browser, which shows no server-rendered content.

#### Expected Behavior
The server-rendered content should appear in the browser source code, similar to when the default port `13714` is used.

#### Actual Behavior
No server-rendered content is visible in the browser source code after changing the port.

#### Additional Information
- There are no error messages when running the `inertia:start-ssr` command.
- No errors occur when building the application with `npm run build`.

#### Output Comparison
- **Output when port is changed to `13715`**:
  ![image](https://github.com/user-attachments/assets/47ed6349-75e7-4a0a-8d81-ab5f0be0d69f)
- **Output when using the default port `13714`**:
  ![image](https://github.com/user-attachments/assets/7747c8d4-8692-49d6-ac94-4db42096006d)

**Comment by RobertBoes** [comment]
Did you also update the config so Inertia can grab the SSR content from the correct place? See https://github.com/inertiajs/inertia-laravel/blob/1.x/config/inertia.php#L26

**Comment by DevShaded** [comment]
Thanks for the reply! No, I haven't changed the config. I'll try to do that, and see if that has any changes

**Comment by DevShaded** [comment]
This fixed the issue with the SSR rendering. Maybe it should state in the docs how to change the ssr ports... Anyways, thanks for the help.
