### ISSUE TITLE
[Feature] Does Inertia-Laravel support Nuxt.js? If not, will it in the future?

### ISSUE THREAD

**Issue by miztizm** [inertiajs/inertia-laravel#648]
Hello,

I am currently exploring the use of Inertia with Laravel for my project and I'm particularly interested in using Nuxt 3 as the frontend framework.

Does Inertia-Laravel currently support Nuxt integration?
If not, are there any plans or ongoing efforts to support Nuxt in the future?
Any guidance or information on this topic would be greatly appreciated.

Thank you!

**Comment by reinink** [comment]
No, as of right now there is no Nuxt integration and we don't have any plans to support it. To be honest I'm not sure they're compatible, as Nuxt ships with it's own client-side router.
