### ISSUE TITLE
[Bug] Inertia Route macro does not work with Route Parameters

### ISSUE THREAD

**Issue by marvinrabe** [inertiajs/inertia-laravel#66]
In web.php I have:

    Route::inertia('{any}', 'MyPage');

When calling `http://foo.test/` this works fine. MyPage will be loaded. If I call `http://foo.test/bar` an exception is raised:

```
ErrorException thrown with message "array_merge(): Expected parameter 2 to be an array, string given"

Stacktrace:
#59 ErrorException in /Users/marvin/Sites/laravel/vendor/inertiajs/inertia-laravel/src/ResponseFactory.php:53
#58 array_merge in /Users/marvin/Sites/laravel/vendor/inertiajs/inertia-laravel/src/ResponseFactory.php:53
#57 Inertia\ResponseFactory:render in /Users/marvin/Sites/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237
#56 Illuminate\Support\Facades\Facade:__callStatic in /Users/marvin/Sites/laravel/vendor/inertiajs/inertia-laravel/src/Controller.php:9
#55 Inertia\Controller:__invoke in /Users/marvin/Sites/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48
#54 Illuminate\Routing\ControllerDispatcher:dispatch in /Users/marvin/Sites/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
```

## Debugging

When I dump the arguments of the render function in `inertiajs/inertia-laravel/src/ResponseFactory.php`. I get the following:

`$component` is `bar` and `$props` is `MyPage`.

It seems like there are Issues with the route bindings in the Inertia Controller when the route contains a route parameter. When I change the Inertia Controller to be like this: 

```
public function __invoke($component, $props, $x)
    {
        dd($component, $props, $x);
        return Inertia::render($component, $props);
    }
```

This will dump `$component` is `bar` and `$props` is `MyPage` and `$x` is an empty array.

So the `any` parameter in the route is mapped to `$component`. Which is obviously wrong.

## Workaround

A possible solution for this might be the following:

```
public function __invoke()
    {
        return Inertia::render(request('component'), request('props'));
    }
```

**Comment by sebastiandedeyne** [comment]
This looks like a bug to me. @peterfox any chance you could do a follow up PR that fixes this? 😇

**Comment by peterfox** [comment]
@sebastiandedeyne sure I'll try and fit in some time to take a look

**Comment by peterfox** [comment]
It's really weird this behaviour seems to happen with Macros but doesn't happen with the router `view` method that does literally the same thing.

The following code for the controller I believe fixes the issue. I have a feeling this might be related to the Laravel version as well, it looks like the controller for `Route::view` has changed in L6, it might just be a cosmetic reason for changing though. @marvinrabe are you using Laravel 6?

```php
<?php

namespace Inertia;

use Illuminate\Http\Request;

class Controller
{
    public function __invoke(Request $request)
    {
        return Inertia::render(
            $request->route()->defaults['component'],
            $request->route()->defaults['props']
        );
    }
}
```

**Comment by marvinrabe** [comment]
@marvinrabe No, I am still on Laravel 5.8. Haven't tested it with Laravel 6 yet.

**Comment by marvinrabe** [comment]
@peterfox It seems like injecting parameters in controller methods is always done by order. See the [documentation](https://laravel.com/docs/6.0/routing#required-parameters):

```
Route parameters are injected into route callbacks / controllers based on their order - the names of the callback / controller arguments do not matter.
```

Up until now I did not know this. I find this quite unintuitive. I opened a [feature proposal](https://github.com/laravel/ideas/issues/1817) for changing this behaviour.

**Comment by Lelectrolux** [comment]
@marvinrabe 
> I find this quite unintuitive

It allows you to do this :
```php
// matches 'GET /1/my-article-slug'
Route::get('/{writer}/{article_slug}', function(Writer $writer, Article $article) {
    // Here I can use $article instead of $article_slug/$articleSlug
});
```
