### ISSUE TITLE
Form submission using GET instead of POST

### ISSUE THREAD

**Issue by Scott-McMullan-ABB** [inertiajs/inertia-laravel#660]
I have just setup a brand new Laravel App with Breeze/InertiaJS/Vue.

In my `Login.vue` component, I have the default form submission method

```js
const submit = () => {
    form.post(route("login"), {
        onFinish: () => form.reset("password"),
    });
};
```

I've registered the login route in `routes/auth.php`

```php
 Route::post('login', [AuthenticatedSessionController::class, 'store'])
        ->name('login');
```

When I submit the login for, though, I get the error 
> The GET method is not supported for route login. Supported methods: POST.

So, for some reason, it's GETting when it should be POSTing. I can't figure out why this is. Any help would be appreciated. 

php: 8.2
inertiajs/inertia-laravel: 1.3
laravel/framework: 11.9

**Comment by RobertBoes** [comment]
What's likely happening here: there is a validation error, then Laravel will redirect back to the login page, which is done using a GET request. If you look at your browser's devtools you'll likely see a POST request followed up by a GET request

**Comment by Scott-McMullan-ABB** [comment]
@RobertBoes you're right, that's exactly what's happening. I think something is going wrong `\App\Http\Controllers\Auth\AuthenticatedSessionController::store`. I'll figure out the issue from there, thanks.
