### ISSUE TITLE
explode() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by FaizAhmadSE** [inertiajs/inertia-laravel#67]
ErrorException  : explode() expects parameter 2 to be string, object given

  at C:\wamp64\www\58FP\vendor\laravel\framework\src\Illuminate\Support\Arr.php:516
             if (is_null($key)) {
                 return $array = $value;
             }
    
  >         **$keys = explode('.', $key);**
    
             while (count($keys) > 1) {
                 $key = array_shift($keys);
    

  Exception trace:

  1   explode(".", Object(Closure))
      C:\wamp64\www\58FP\vendor\laravel\framework\src\Illuminate\Support\Arr.php:516

  2   Illuminate\Support\Arr::set([], Object(Closure))
      C:\wamp64\www\58FP\vendor\inertiajs\inertia-laravel\src\ResponseFactory.php:25

**Comment by sebastiandedeyne** [comment]
Could you provide a bigger stack trace?

And could you also provide a snippet of your code that causes this exception? Probably an `Inertia::share` call or `Inertia::component`
