### ISSUE TITLE
Not Supporting Central Domain Routes Correctly

### ISSUE THREAD

**Issue by usmanibrahim74** [inertiajs/inertia-laravel#676]
I have Laravel 11 setup with inertia, vue and Multitenant setup using TenancyForLaravel Package. Here is routing code for multitenant setup. Its working fine except for the routes the are limited to central domain only.

    ->withRouting(
        using: function () {
            $centralDomains = config('tenancy.central_domains');
            foreach ($centralDomains as $domain) {
                Route::middleware('web')->domain($domain)->group(base_path('routes/web.php'));
                Route::middleware('api')->prefix('api')->domain($domain)->group(base_path('routes/api.php'));
            }
            Route::middleware("web")->group(base_path('routes/tenant.php'));
        },
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )

here are example routes
    
    Route::prefix('roles')->group(function () {
        Route::get('/', [RolesController::class, 'index'])->name('roles.index');
        Route::get('/table', [RolesController::class, 'table'])->name('roles.table');
        Route::get('/options', [RolesController::class, 'options'])->name('roles.options');
        Route::get('/create', [RolesController::class, 'create'])->name('roles.create');
        Route::post('/', [RolesController::class, 'store'])->name('roles.store');
        Route::get('/{role}/edit', [RolesController::class, 'edit'])->name('roles.edit');
        Route::delete('/{role}', [RolesController::class, 'destroy'])->name('roles.destroy');
    });

    Route::prefix('tenants')->group(function () {
        Route::get('/', [TenantController::class, 'index'])->name('tenants.index');
        Route::get('/table', [TenantController::class, 'table'])->name('tenants.table');
        Route::get('/create', [TenantController::class, 'create'])->name('tenants.create');
        Route::post('/', [TenantController::class, 'store'])->name('tenants.store');
        Route::get('/{tenant}/edit', [TenantController::class, 'edit'])->name('tenants.edit');
        Route::get('/{tenant}/refresh', [TenantController::class, 'refresh'])->name('tenants.refresh');

        Route::get('/{id}/modules', [TenantController::class, 'modules']);
        Route::post('/{id}/modules', [TenantController::class, 'assign']);
    });

    Route::prefix('/feedbacks')->group(function () {
        Route::get('/', [FeedbackController::class, 'index'])->name('feedbacks.index');
        Route::get('/table', [FeedbackController::class, 'table'])->name('feedbacks.table');
    });
    
The Roles routes are common in both sides. but tenants and feedbacks routes are only central domain routes.
Problem is for the central domain routes only the last domain in the list of central domains in `config/tenancy.php` work if accessed but if I access through prior domain, links shows last domain in the list instead of the domain through I access.
I have a work around to set a central domain in .env file and place it in the list at last. I just want to highlight the issue.

**Comment by RobertBoes** [comment]
Don't think this has anything to do with Inertia? Inertia is just a connecting glue between frontend and backend. Routing would still be registered by the backend (Laravel), Inertia doesn't interfere there in any way. The only thing that wouldn't be possible is navigating between domains through Inertia requests (but navigating between different domains likely wouldn't really work anyway, as sessions wouldn't be shared between different domains)

**Comment by usmanibrahim74** [comment]
> Don't think this has anything to do with Inertia? Inertia is just a connecting glue between frontend and backend. Routing would still be registered by the backend (Laravel), Inertia doesn't interfere there in any way. The only thing that wouldn't be possible is navigating between domains through Inertia requests (but navigating between different domains likely wouldn't really work anyway, as sessions wouldn't be shared between different domains)

maybe you are right. But the route list I get through @routes directive, it has tenants.index with different domain instead of the one which I'm using to access other routes even though that route is actually registered. here is the route list

![image](https://github.com/user-attachments/assets/7f074f6f-cb42-4285-a816-33643ce5ca4a)

my point is maybe routes directive pickup routes by names and if 2 routes are registered with same name then it used last route instead of matching it with the current domain through it is being accessed.

**Comment by RobertBoes** [comment]
Well yes, a route name would need to be unique to be used effectively, if you have multiple routes with the same name then what route would need to be returned? It would be either one of them.

The `@routes` directive you're referring to is Ziggy (https://github.com/tighten/ziggy), that's not provided by Inertia.

**Comment by usmanibrahim74** [comment]
I think it should first check the domain specific routes.
as this issue related to Ziggy we can close this issue here.

**Comment by RobertBoes** [comment]
@usmanibrahim74 Just so you know, it isn't an issue with Ziggy either. You're registering routes with the same name multiple times, a name should be unique, otherwise there would not be a way to get any of those routes reliably by its name.

You should probably consider using a different way of registering routes; register the routes _once_, use a `Route::domain()` to attach those routes to the domains.

**Comment by usmanibrahim74** [comment]
> You should probably consider using a different way of registering routes; register the routes _once_, use a `Route::domain()` to attach those routes to the domains.

I'm already doing that if you see the route list and route registering method above

**Comment by RobertBoes** [comment]
You're looping over domains, then requiring the same file within that loop. This would register those same routes multiple times
