### ISSUE TITLE
Page shows json instead of page

### ISSUE THREAD

**Issue by SimonOnbelet** [inertiajs/inertia-laravel#695]
Sometimes when you browse through the pages and you go back a page, JSON is shown instead of the page. An issue was previously created for this, but it was closed due to lack of overview.

The issue is still not resolved. I cannot give any hard conditions on how to reproduce this, only that it only happens when you go back to a previous page after a number of pages.

You will then see something like the following:

![Screenshot 2024-12-10 at 13 36 08](https://github.com/user-attachments/assets/57c52cbf-2695-4c31-8292-5c18f6408585)

We are using inertia version 1.2.0

**Comment by pascalbaljet** [comment]
Check if the `Vary` header is coming through: https://github.com/inertiajs/inertia-laravel/pull/398

**Comment by SimonOnbelet** [comment]
@pascalbaljet ,

Thanks for the tip. It wasn't that the header wasn't being set, but is wasn't set correctly. 
We fixed this and so far it looks like this solved the issue.
