### ISSUE TITLE
All responses are 409

### ISSUE THREAD

**Issue by grantholle** [inertiajs/inertia-laravel#76]
Not an issue, more of a question.

I am getting 409 responses when using `<inertia-link>`. The page then reloads the intended url and is working fine, due to [this behavior](https://github.com/inertiajs/inertia/blob/master/src/inertia.js#L83).

Any idea what could be causing this? When visiting directly/testing everything is 200. I feel like there's a conflicting header?

Here are the headers according to Telescope:

```
{
cookie: "remember_web:applicants_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IlRja01BVGdhNERGMDVsYzNPaXVVUXc9PSIsInZhbHVlIjoidGRiN2tJRUJldWhcLzJTWE1QanpZQlpzd0dYV3V1em4xWEl6WnJuXC9yVUhPV0FtZDhrVFc0MmMxTkJcL1MyYmlMZFhuZStHZE5uR0s0NjFCM2pJV25ZNGxBUXU1NjVhTGJwVE5SV2RNNWpHNmpSeDFuN1Bmam5nMzBId3BGK2wwYkdzZHRuVHVWVW82a3JMYjlmeG9hdXcxXC9XS3BpdHJPZFZ0YWIrbHZkTkxuOD0iLCJtYWMiOiIxM2JmYWJkYjJlNGM2OTM0YmNiNWZlODFlNTI3MmQ0Yjg5MDEzMTljZmNlMDdlZmE4MmMwMDI2MzQ1NTc3MzMzIn0%3D; XSRF-TOKEN=eyJpdiI6InRUYzMyZjFWeFJtUmFpVTZqdHR1emc9PSIsInZhbHVlIjoickN2a0Jyem5uQ242VW1MWjA4SnFLTFlnSFJSOXF4UWFlXC85eEo4WTB3aGQwNUpSbytoRkl1eVFrOTRPWXZ0dTciLCJtYWMiOiI1ODQ3MzM4ZjZlNDU1NjUxYzY5NWQ3YTkzNjRiMTYyZDZjYTQzMzM4NWU0ZDM0N2JhNmRlYjRmYWUwMWFlY2E5In0%3D; ldi_apply_session=eyJpdiI6Ims3WG5GR2dvOUdiMWlyRGhPZ2h5M0E9PSIsInZhbHVlIjoiejJkd0tOSHFWRFwvUFVqcEpyV2syaVwvSlpYMndrRitQaHJGdWRGTnphOFwvY3BVZjQ3dmlYXC9XZjdXclRtaEhZNjciLCJtYWMiOiIwNzAwNDE5YzhlMmIzOTIyNGYxYWE1MTAyZDVmOWFjZTNlOGZkOTUyNzAwZTM3MjdhNDJjMjlkNjMxMWUyNTExIn0%3D",
accept-language: "en-US,en;q=0.9,ar;q=0.8,fr;q=0.7",
accept-encoding: "gzip, deflate",
referer: "http://ldi-apply.test/steps/1/forms/3/edit",
x-requested-with: "XMLHttpRequest",
x-inertia-version: "a86ad0584af7daf29b57549e69872177",
accept: "text/html, application/xhtml+xml",
content-type: "application/json;charset=utf-8",
user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
x-inertia: "true",
x-xsrf-token: "eyJpdiI6InRUYzMyZjFWeFJtUmFpVTZqdHR1emc9PSIsInZhbHVlIjoickN2a0Jyem5uQ242VW1MWjA4SnFLTFlnSFJSOXF4UWFlXC85eEo4WTB3aGQwNUpSbytoRkl1eVFrOTRPWXZ0dTciLCJtYWMiOiI1ODQ3MzM4ZjZlNDU1NjUxYzY5NWQ3YTkzNjRiMTYyZDZjYTQzMzM4NWU0ZDM0N2JhNmRlYjRmYWUwMWFlY2E5In0=",
cache-control: "no-cache",
pragma: "no-cache",
connection: "keep-alive",
host: "ldi-apply.test",
content-length: ""
}
```

The response in Telescope just says `"HTML Response"`.

**Comment by reinink** [comment]
Yes, this is caused by [asset versioning](https://inertiajs.com/asset-versioning). A 409 response is sent when your assets are out of date. You can use this to force an asset update, which is really helpful!

**Comment by grantholle** [comment]
Does this happen automatically or will I need to include

```php
Inertia::version(function () {
    return md5_file(public_path('mix-manifest.json'));
});
```

in my AppServiceProvider? This behavior has started relatively recently when it had been working fine. This behavior is good when it's needed, I just don't know why it has started suddenly.

**Comment by reinink** [comment]
No, it doesn't happen automatically. It should only happen if you're using `Inertia::version()`. Are you not using this?

**Comment by grantholle** [comment]
Actually I just realized I had it already. Removing it solves my issue 🤷‍♂️

**Comment by reinink** [comment]
Okay cool. I would recommend not removing it, as this is very helpful behaviour if you're using code splitting.

**Comment by grantholle** [comment]
Yes absolutely. I just figured out what is happening.

I've extended Inertia to support API resources (#70), and the middleware isn't using my class, therefore not my version! Adding in the additional `version()` call resolves everything...

Thanks so much Jonathan!

**Comment by marcuschristiansen** [comment]
@reinink I have a similar issue but it keeps refreshing every time. What do I do to bring these assets up-to-date?

**Comment by yamchinghann** [comment]
> @reinink I have a similar issue but it keeps refreshing every time. What do I do to bring these assets up-to-date?

i have similar your issue as well

**Comment by marcuschristiansen** [comment]
> @reinink I have a similar issue but it keeps refreshing every time. What do I do to bring these assets up-to-date?

For me this was an issue with the fact that we have a load balancer in place. Using sticky sessions resolved it for us.

**Comment by JIscariot** [comment]
Use @inertiajs/inertia-vue3 instead of @inertiajs/vue3

**Comment by jjdreba** [comment]
I had the same issue for a while, so I wanted to share my approach for any future readers: 

if you use any Vue specific handlers such as @click="selectSortOption(option)", this will cause a full page refresh as it is not in line with inertias asset versioning. Save yourself some troubles and read the Inertia docs, use < Link > and Inertia native navigation if you want to avoid frequent issues with 409s.

**Comment by mattfoster7** [comment]
> Use @inertiajs/inertia-vue3 instead of @inertiajs/vue3

LITERALLY HOURS I spent with inertia-vue3 causing a 409 response and triggering a full page reload when submitting via useForm. Changed to vue3 and it fixes the error. GRRR.

**Comment by vearse** [comment]
What about React? I am having a similar issue with Laravel react

**Comment by vearse** [comment]
I have been able to solve my  issue by using import { useForm } from '@inertiajs/react'; instead of using import { useForm } from '@inertiajs/inertia-react';

**Comment by bliveinhack** [comment]
same problem with @inertiajs/react also.

**Comment by vearse** [comment]
Those the suggestion works fo you?
