### ISSUE TITLE
Forcing the response into modal

### ISSUE THREAD

**Issue by pdiveris** [inertiajs/inertia-laravel#77]
I  know that the opposite has already been discussed (and I struggled with that too) - namely getting non-inertia responses not to load into a modal. However, I wonder if it would be possible to have an Inertia Response load **into a moda**l? Is there any way of triggering this (other than re-implementing Response and reneder to fiddle with the `x-inertia` on my side?

Thank you.

**Comment by pdiveris** [comment]
I am closing this as I see no interest. I've created a helper that handles the response in way so that I can force a modal. Thanks.

**Comment by Juhlinus** [comment]
Hi @pdiveris ! 

There's usually a pretty slow response when it comes to issues, unfortunately. 

You can re-open the issue if you feel that this would be a feature you'd like to see in the adapter. 🙂

**Comment by reinink** [comment]
Sorry folks. I work on this project as I have time. I often don't respond to issues the day they are opened, but rather when I get a moment to sit down and work through them.

For what it's worth, I wouldn't even know how to get an Inertia response to load in a modal instead of the root layout as it does now. The way Inertia works is by utilizing an existing React/Vue.js/Svelte instance, so loading it in an entirely separate part of the DOM doesn't sound easy. That said, modals are totally doable in Inertia, I use them all the time. I simply add them as child components to my page components.

Good luck! 👍

**Comment by pdiveris** [comment]
No worries, I gathered that you are thin on time so I closed the issue after finding a way of achieving just that. My comment was not meant to sound as negative or a complain. I appreciate your work with inertiajs, I was trying to something along these lines too, and I am using it heavily. Keep up the good work!

**Comment by reinink** [comment]
Thanks @pdiveris, I appreciate that! 💪

**Comment by Neophen** [comment]
@pdiveris could you post that solution of yours please? I'm interested into something similar.

**Comment by stygiansabyss** [comment]
@reinink / @pdiveris could you post your solutions to modals?  I am trying to make a "confirm" modal when a user tries to delete something.  I was thinking of something like the error display modals but don't know if inertia has a clever way to do this built in.

Thanks!

**Comment by destinybravos** [comment]
@Neophen and @stygiansabyss you can easily load modal on your component as follows;

on the main component where you want the modal to stay; you do something like this.
`<template>
   <div>
       .... Your Component content goes here!
     <button @click="showDetails=true"> Show Modal</button>

<modal-component :prop-show="showDetails" @closeModal="closeModal()">
        <div>
               .... Modal Content Goes here!
           <button @click="confirmMethod"> Confirm </button>
           <button @click="closeModalMethod"> Cancel </button>
     </div>
</modal-component>
  </div>
</template>`

then your script can then look like this;

`<script>
import ModalComponent from '../ModalComponent';

export default {
components:{ModalComponent},
data() {
    return {
        showDetails: false
    };
},
methods: {
    confirmMethod() {
       // ..Content of your confirm goes here
    },
        closeModal(){
            this.showDetails = false;
        },
},
};
</script>`

Lastly, the content of you modal component can be like this;
`
<template>
    <transition name="fade">
        <div v-if="showModal" id="modal" class="h-full fixed top-0 left-0 w-full flex content-center flex-wrap">
            
            <div :class="'modal-'+propSize" class="bg-white modal-dialog shadow rounded mx-auto flex flex-col w-full  mt-8 transform transition-all" style="max-height:96vh;">
                <div>
                    <button class="float-right mt-4 mr-6 font-light" @click="closeModal" >
                        <font-awesome-icon icon="times" class="font-light" style="font-size:1.3rem; font-weight:normal;" />
                    </button>
                </div>
                <div class="modal-body py-3 px-4 overflow-y-auto transform transition-all"> 
                    <slot></slot>
                </div>
            </div>
        </div>
  </transition>
</template>

<script>
export default {
    name: 'ModalComponent',
    props: {
        propShow: Boolean,
        propSize: {
        default: 'md',
        type: String
        }
    },
    data() {
        return {
        showModal: false,
        };
    },
    watch: {
        propShow: function (state) {
        this.showModal = state;
        },
    },
    methods: {
        closeModal(){
            this.$emit('closeModal')
        }
    },
};
</script>

<style scoped>
    .fade-enter-active, .fade-leave-active {
        transition: opacity .5s;
    }
    .fade-enter, .fade-leave-to { /* .fade-leave-active below version 2.1.8 */
        opacity: 0;
    }
    #modal {
        z-index: 1000;
        background-color: rgba(0, 0, 0, 0.5);
        /* display: none; */
        align-items: center;
    }
    .modal-dialog{
        max-width: 95%;
    }
    .modal-lg{
        width: 900px;
    }
    .modal-md{
        width: 640px;
    }
    .modal-sm{
        width: 400px;
    }
</style>
`

I don't know if this is still helpful cos it is been long this issues was raised. I believe it might help someone though.
