### ISSUE TITLE
FOUC/Slight jerk when navigating pages

### ISSUE THREAD

**Issue by JunaidQadirB** [inertiajs/inertia-laravel#78]
I'm using the bare-minimum setup as described in the documentation.
When I navigate pages via `inertia-link` tag, page does a slight jump/jerk.

In this gif I'm clicking the `About` link to demonstrate the behaviour.  

![Peek 2019-10-13 23-51](https://user-images.githubusercontent.com/642353/66720410-c0ed1e80-ee15-11e9-8607-f2bbc0c1ea2c.gif)

So why is this happening and how to prevent this jumpiness?

**Comment by hawezo** [comment]
Can you share a repository with the issue?

**Comment by JunaidQadirB** [comment]
I solved the issue with re-configuring my styles and markup but installing `bootstrap-vue`

**Comment by JunaidQadirB** [comment]
I don't understand. I'm getting this FOUC / jerk again.
But the example project I prepared from my existing project didn't have the issue becuase perhaps it has very little to no content and data coming from the controller

**Comment by druc** [comment]
@JunaidQadirB Maybe it's a weirdly styled nprogress?

**Comment by reinink** [comment]
This is really weird. I have not seen this before. It's worth noting that when you click on an Inertia link, or make an Inertia visit manually, Inertia will manually reset the scroll position to the top of the page. You can see that here: https://github.com/inertiajs/inertia/blob/472c1d3daa455b67df68aa71b6e2a656724d9652/src/inertia.js#L129-L134

That's the only thing Inertia does though. 🤷‍♂

**Comment by druc** [comment]
The easiest way to check if that's what is causing the flicker is to tell inertia to preserve the scroll position.

```
<inertia-link href="/" preserve-scroll>About</inertia-link>
```

**Comment by reinink** [comment]
Good call @druc 👍

**Comment by reinink** [comment]
Closing this, as I don't really think this is related to the Laravel adapter.
