### ISSUE TITLE
[Idea] Make InertiaViewFactory

### ISSUE THREAD

**Issue by oanhnn** [inertiajs/inertia-laravel#81]
We should make `InertialViewFactory` implements `\Illuminate\Contracts\View\Factory` instead of default `ViewFactory` of Laravel. With `InertialViewFactory`

- Using same `view()` function ( `return view('viewName', [ /* data */])` )
   * return blade view when request is non inertia request
   * return inertial when request is inertia request
- Using same concept ViewComponent, ... with blade.

**Comment by reinink** [comment]
I considered highjacking the `view()` method, but decided against it. I think I prefer the clarity that `Inertia:render()` and `inertia()` provided when making responses. Seeing the `view()` method suggests to developers that a Blade view will be returned, when it won't.

Thanks either way for the idea! 👍
