### ISSUE TITLE
Make the Inertia macroable

### ISSUE THREAD

**Issue by mojtabaahn** [inertiajs/inertia-laravel#84]
Hi there nice work 🎉
I'm developing my admin app using inertia and I got some Resource classes on my front-end so all my controllers pass a `resource` parameter to pages like this:
```php
Inertia::render('Resource/Index',[
    'resource' => 'BlogPost',
    // ...
])
```
so it's good unless i have more than one methods on my resource controller ( mostly all CRUD methods ). so i prefer `share` resource parameter in `__constructor` method instead of repeating it at every method like :
```php
Class BlogPostController extends Controller{
    __constructor(){
        Inertia::share('resource','BlogPost');
    }
    //...
}
```

So i though it's cleaner to make Inertia macroable so it would be possible do something like:
```php
Class BlogPostController extends Controller{
    __constructor(){
        Inertia::resource('BlogPost');
    }
    //...
}
```

**Comment by reinink** [comment]
Done 🤟

**Comment by mojtabaahn** [comment]
You Rock 👊🔥
