### ISSUE TITLE
How to use laravel's Storage::download response?

### ISSUE THREAD

**Issue by Naoray** [inertiajs/inertia-laravel#85]
How can I use `Storage::download()` with Inertia? Currently it just opens up a modal with the contents of the downloaded file..

**Comment by reinink** [comment]
You need to make a normal, non-Inertia request to download files. All Inertia requests must return a valid Inertia response, which a file download of course isn't. So, instead of using an `<inertia-link>`, just use a regular `<a>`. 👍

**Comment by nwaweru** [comment]
> gular `<a>`.

Did you find a way around this?

I need to send a post request to download the file.

**Comment by rojtjo** [comment]
You should be able to just use a regular form. Optionally with the target set to `_blank` to ensure a new window/tab opens and your Inertia app will just keep running.

```jsx
<form action={yourDownloadUrl} method="post" target="_blank">
    <button>Download</button>
</form>
```

**Comment by javdome** [comment]
You can do it with a form... but remember the `csrf` token.

First, send the token to the Inertia view where you are going to insert the form:

```php
return inertia ( 'YourView', [ 'token' => csrf_token() ] );
```

Now, in the view, insert the csrf token in a hidden input.
For instance, in a React view:

```js
<form action = { route ('your.named.route', your.param) } method = "post">
    <input type="hidden" name="_token" value={props.token}/>
    <button>Download</button>
</form>
```

**Comment by boparaiamrit** [comment]
You can use this in onClick

```
fetch(route('documents.download', { id: document.id }))
    .then((res) => res.blob())
    .then((blob) => {
      const file = window.URL.createObjectURL(blob)
      window.location.assign(file)
    })
```

**Comment by omidgfx** [comment]
Is there any new and convenient way to do this, just with inertiajs form ?
