### ISSUE TITLE
@push

### ISSUE THREAD

**Issue by uwejan** [inertiajs/inertia-laravel#87]
Is there the ability to do sth similar to laravel's blade template '@push',
using inertia-vue with laravel, say i have base template, but based on different componenets, i wish to make sth similar to `@push('custom1'), @push('custom2')`?

**Comment by reinink** [comment]
This isn't really an Inertia related issue/feature request, but rather a Vue related one. That said, you can use [slots](https://vuejs.org/v2/guide/components-slots.html) to accomplish something similar to this. 👍
