### ISSUE TITLE
Using Inertia::render with views outside Pages

### ISSUE THREAD

**Issue by lucaros97** [inertiajs/inertia-laravel#88]
Hello,
I'm trying to render a Vue Component that it is outside of the Pages folder but it's inside a directory on the same level of the Pages folder.
Is there a way to render it?

Example:
```php
return Inertia::render('Shared/Example');
```

Instead of :
```php
return Inertia::render('Pages/Example');
```

**Comment by XaBerr** [comment]
In app.js you can set the render path

```js
new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
    },
  }),
}).$mount(app)
```

**Comment by The7-Ivan** [comment]
I tryed to change from 

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.tsx`,
            import.meta.glob('./Pages/**/*.tsx'),
        ),
    setup({ el, App, props }) {
        const root = createRoot(el);

        root.render(<App {...props} />);
    },
    progress: {
        color: '#4B5563',
    },
});

to

        resolvePageComponent(
            `./Router/${name}.tsx`,
            import.meta.glob('./Router/**/*.tsx'),
        ),
        
  Route::get('/', function () {
    return Inertia::render('Router');
});

  it renders the Router.tsx but always trows a console error 
  
  localhost/:21      
       GET http://[::1]:5173/resources/js/Pages/Router.tsx net::ERR_ABORTED 404 (Not Found)
       
 even defining a new path something in Innertia defautly trys to search for the file inside Pages/Router.tsx
