### ISSUE TITLE
Requests don't respect forced https scheme

### ISSUE THREAD

**Issue by iKlsR** [inertiajs/inertia-laravel#89]
I have ` \URL::forceScheme('https');` in app boot. However I noticed that requests still go to `http://...` and this doesn't seem to complete visually. If I refresh the page I can see that the `POST` or `DELETE` was successful but nprogress never completes and it and the page goes into a crawl state.

**Comment by druc** [comment]
@iKlsR I'm just making assumptions but there's a good chance this is caused by ziggy. I remember also having issues with https and ended up adding this in `app.blade`:

```
@routes

@if(config('app.env') !== 'local')
     <script>window.Ziggy.baseProtocol = 'https';</script>
@endif
```

Long way from being perfect/nice, but it did the job.

**Comment by iKlsR** [comment]
@druc Thanks, seeing some success with this so it will do for now.

**Comment by reinink** [comment]
I'd recommend taking this issue up in the ziggy repo (https://github.com/tightenco/ziggy). The issue here is that the client-side doesn't realize that it should be HTTPS.
