### ISSUE TITLE
[Suggestion] Using Inertiajs views in Laravel Package

### ISSUE THREAD

**Issue by ycs77** [inertiajs/inertia-laravel#92]
If I build a Laravel package, I hope I can load Inertia views into the package.

Load Inertia views example:

```php
use Inertia\Inertia;

public function boot()
{
    Inertia::loadViewsFrom(__DIR__.'/path/to/views', 'my-package');
}
```

Usage Inertia views example:

```php
use Inertia\Inertia;

class HomeController extends Controller
{
    public function index()
    {
        return Inertia::render('my-package::Home/Index', [
            ...
        ]);
    }
}
```

Can it be achieved?

---

Update on 2022/07/03:

Thanks all for the ideas, inspired me to create the [Inertia Plugin](https://github.com/ycs77/inertia-plugin) to resolve this issue.

**Comment by beeglebug** [comment]
I've also hit this. I have some of my optional routes defined inside a package, and the javascript component ends up being published out to `resources/vendor/MyPackage/js/Pages/MyPackagePage.js`

In the package controller, I can't just do `return Inertia::render('MyPackagePage');` because that would look inside `resources/js/Pages` not the vendor folder, I would need to do something like `return Inertia::render('../vendor/MyPackage/js/Pages/MyPackagePage');` which isn't ideal, and i'm not sure it even works.

**Comment by herpaderpaldent** [comment]
I would love this feature too, however i found my way around this which i gonna post here in hope it might help you?

for production i publish the resources to the app's resource folder:
https://github.com/seatplus/web/blob/develop/src/WebServiceProvider.php#L52-L64

during development i have `npm run watch` running and refering the pages in my package alike:
https://github.com/seatplus/core/blob/develop/webpack.mix.js#L19

**Comment by beeglebug** [comment]
The only problem with that is that the `app.js` would need to be aware of all the possible packages in order to resolve the paths, rather than the package being able inject themselves.

The suggestion from OP seems better in terms of isolation / injection, you would tell inertia that you have views in a package folder, and then when you call `Inertia::render('my-package::Component')`, it could internally check the map of namespaces and convert the component argument before passing it down to the javascript.

This would allow the javascript `resolveComponent` function to remain unaware of the existence of any packages.

**Comment by beeglebug** [comment]
I've spent a bit longer on this today and realised @sebastiandedeyne is right. You need the requires to have at least the partial path to allow webpack to statically analyse the lazy load possibilities, so doing it inside the componentResolver makes a lot more sense.

**Comment by yashiroiori** [comment]
This is may solution to call and component from modules and packages

app.js
![image](https://user-images.githubusercontent.com/17031855/74459141-6d84ee80-4e50-11ea-9b15-43bb0602f665.png)

Call from modules using https://github.com/nWidart/laravel-modules
![image](https://user-images.githubusercontent.com/17031855/74459222-8db4ad80-4e50-11ea-9163-97775a40bb32.png)

Call from package
![image](https://user-images.githubusercontent.com/17031855/74459283-a6bd5e80-4e50-11ea-88ea-60bd684febe3.png)

**Comment by robsontenorio** [comment]
I am facing a related issue. How to propper install insertia inside a package? 

In my package:
```
composer require inertiajs/inertia-laravel

```


```php
class MyPackageServiceProvider extends ServiceProvider

   
    public function boot()
    {
        Inertia::version(function () {
             return md5_file(public_path('mix-manifest.json'));
        });
    }
   
   ....
}
```

Then, when I `composer require mypackage`  i got
```
  Class 'Inertia\Inertia' not found
```

Any tips?

**Comment by robsontenorio** [comment]
Just wondering at this point a guide about creating packages with Inertia would be a nice addition :)

**Comment by robsontenorio** [comment]
For future reference here is my approach. Built a package with standalone dashboard using inertia, where target app does not has inertia or laravel mix. 

https://github.com/robsontenorio/lighthouse-dashboard

**Comment by vortechron** [comment]
my current implementation for laravel package 

resources/js/app.js
```javascript
new Vue({
    render: (h) =>
        h(InertiaApp, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                resolveComponent: (name) => {
                    let splited = name.split('::')

                    if (splited.length == 1) return require(`./Pages/${name}`).default
                    
                    let [first, page] = splited
                    let [author, plugin] = first.split('/')

                    // '~': path.resolve('vendor')
                    return require(`~/${author}/${plugin}/resources/js/Pages/${page}`).default
                },
            },
        }),
}).$mount(app);
```

Author/PackageName/Controller/DashboardController.php
```php
class DashboardController extends Controller
{
    public function index()
    {
        return inertia('author/package-name::Dashboard');
    }
}
```

i hope there is a better and proper way to implement inertiajs return view on laravel package.

**Comment by herpaderpaldent** [comment]
@vortechron this looks very promising i am likely ditching my approach in favors of yours

**Comment by herpaderpaldent** [comment]
i gave @vortechron 's solution a try and i wasn't satisfied. running dev/prod with npm took way to long.

**Comment by maicol07** [comment]
I'm also interested on this feature. Has anyone found a workaround for this?

**Comment by yashiroiori** [comment]
> I'm also interested on this feature. Has anyone found a workaround for this?

Actually work with modules package + inertiajs + vue/react + bootstrap/tailwind

**Comment by maicol07** [comment]
@yashiroiori can you explain how did you manage to setup the packages, so that views are loaded with Inertia?

**Comment by adam-devapp** [comment]
> @yashiroiori can you explain how did you manage to setup the packages, so that views are loaded with Inertia?

+1

**Comment by jenky** [comment]
I think this can be done using `symlink` and I had it working on my local but there are few things need to be addressed.

This is an example directory

```
.
├── app
├── resources/
│   └── js/
│       ├── app.js
│       └── Pages/
└── vendor/
    └── my-package/
        ├── config/
        ├── src/
        │   └── ServiceProvider.php
        └── js/
            ├── ComponentA.vue
            └── ComponentB.vue
```
In your package `ServiceProvider`, register the component hint path

```php
Inertia::loadComponentsFrom(__DIR__.'../js', 'my-package');
```

Then have artisan command similar to `storage:link` to generate the symlink from `vendor/my-package/js` to `resources/js/Pages/vendor`

```
.
├── app
├── resources/
│   └── js/
│       ├── app.js
│       └── Pages/
│           └── vendor/
│               └── my-package -> symlink to vendor/my-package/js/
└── vendor/
    └── my-package/
        ├── config/
        ├── src/
        │   └── ServiceProvider.php
        └── js/
            ├── ComponentA.vue
            └── ComponentB.vue
```

In your controller you can use something like this

```php
Inertia::render('my-package::ComponentA');
```

It will replace the the component from `my-package::ComponentA` to `vendor/my-package/ComponentA` and you don't have to update your `app.js`

The command can be added to composer `post-autoload-dump` script to generate the `symlink` automatically. However there is a case when assets are published to `resources` folder, the symlink need to be updated also. The good news is there is `VendorTagPublished` event for this but the bad news is it only available since Laravel 8. I can create a PR for this when I have time to address this issue.

How do you guys think about this approach?

**Comment by ycs77** [comment]
OK. I think I got the answer. Thanks all for the ideas, inspired me to create a plugin.

---

### [Inertia Plugin](https://github.com/ycs77/inertia-plugin)

> **Warning**: This plugin status is experimental, don't use it for the production application.

The plugin page loader for Inertia.js, powered by **unplugin**, supports **Vite** and **Laravel Mix**.

Define the namespace mapping for plugins pages directory, also can be extract namespace from any directory in the current application or npm / composer the plugin:

```js
// webpack.mix.js
const inertiaPlugin = require('inertia-plugin/webpack').default

mix
  .webpackConfig({
    plugins: [
      inertiaPlugin({
        namespaces: ({ npm, composer }) => [
          // define namespace mapping:
          { MyPackage1: 'node_modules/my-plugin1/src/Pages' },
          { MyPackage2: 'node_modules/my-plugin2/src/Pages' },

          // load namespace from npm package:
          npm('my-plugin2'),

          // load namespace from composer package:
          composer('ycs77/my-php-package'),
        ],
      }),
    ],
  })
```

The npm package in `node_modules/my-plugin2/package.json`:

```json
{
  "name": "my-plugin2",
  "inertia": {
    "MyPackage2": "src/other-pages"
  }
}
```

The composer package in `vendor/ycs77/my-php-package/composer.json`:

```json
{
    "name": "ycs77/my-php-package",
    "extra": {
        "inertia": {
            "MyPhpPackage": "resources/js/Pages"
        }
    }
}
```

For full usage see the [docs](https://github.com/ycs77/inertia-plugin).

Try it~ 😊

**Comment by anditsung** [comment]
> my current implementation for laravel package
> 
> resources/js/app.js
> 
> ```js
> new Vue({
>     render: (h) =>
>         h(InertiaApp, {
>             props: {
>                 initialPage: JSON.parse(app.dataset.page),
>                 resolveComponent: (name) => {
>                     let splited = name.split('::')
> 
>                     if (splited.length == 1) return require(`./Pages/${name}`).default
>                     
>                     let [first, page] = splited
>                     let [author, plugin] = first.split('/')
> 
>                     // '~': path.resolve('vendor')
>                     return require(`~/${author}/${plugin}/resources/js/Pages/${page}`).default
>                 },
>             },
>         }),
> }).$mount(app);
> ```
> 
> Author/PackageName/Controller/DashboardController.php
> 
> ```
> class DashboardController extends Controller
> {
>     public function index()
>     {
>         return inertia('author/package-name::Dashboard');
>     }
> }
> ```
> 
> i hope there is a better and proper way to implement inertiajs return view on laravel package.

when i try to use this. i have an error javascript heap out of memory
looks like it will compile all the package.
