### ISSUE TITLE
[0.2] [bug?] A single resource has its properties nested in a data attribute.

### ISSUE THREAD

**Issue by johanvanhelden** [inertiajs/inertia-laravel#93]
Since the upgrade to 0.2 a resource collection has a data property that contains the collection of resources. I get that. That is awesome.

What I don't understand, and I hope this is a bug, is why this also applies to a single resource.

For example:
```php
return Inertia::render('Home', [
	'projects' => ProjectResource::collection($projects),	
```
Gives me a Vue object like this:
![Screenshot from 2020-01-03 15-34-10](https://user-images.githubusercontent.com/19389981/71728845-8906dd80-2e3e-11ea-9471-2e8e5af390a8.png)

Again, makes complete sense to me! You just create a loop over `project.data` in Vue and can simply use `{{ project.name }}` to render data for a single project.

But, this example:
```php
return Inertia::render('Project/Show', [
    'project' => new ProjectResource($project),
```
Gives me a Vue object like this:
![Screenshot from 2020-01-03 15-35-36](https://user-images.githubusercontent.com/19389981/71728899-b6538b80-2e3e-11ea-8989-c67c6f477dff.png)

And here I would have expected the old behavior. A project object with the properties directly inside  it and not nested within a data property. Because now I would have to rewrite everything from
`{{ project.name }}` to `{{ project.data.name }}`.

So for a single project inside a project collection I can use `{{ project.name }}` but for the single resource I need to use `{{ project.data.name }}`. That is just not consistent.

So again, I would just like to make sure that this is the intended behavior for a single resource. It just looks to much like a bug to me.

**Comment by reinink** [comment]
This is simply how API resources in Laravel work. Even on single resources, it nests them within the `data` property. You can disable this behaviour using `Resource::withoutWrapping()`. See [here](https://laravel.com/docs/6.x/eloquent-resources#data-wrapping) for more info.
