### ISSUE TITLE
Session ID is newly generated after each request

### ISSUE THREAD

**Issue by fabianpnke** [inertiajs/inertia-laravel#94]
I'm creating an application for seat reservations. Therefor I'm saving the Session ID to the Model, in order to prevent duplicate reservations. Now I have the problem, that the returned Session ID from `Session::getId();` is different on every request.

I'm using the following Session config:
```env
SESSION_DRIVER=redis
SESSION_LIFETIME=120
```

Here is my Vue Method:
```vue
<script>
export default {
    props: ['seat'],
    methods: {
        addSeatToCart() {
            this.$inertia.post(this.$route('seat.cart', this.seat.id), null, {
                replace: false,
                preserveState: true,
                preserveScroll: true,
                only: [],
            })
        },
    },
}
</script>
```

And here is the respondig Contoller Action:
```php
use Illuminate\Support\Facades\Session;

public function addSeatToCart(Seat $seat)
{
    return redirect()->back()->with(['status' => Session::getId()]);
}
```

Here I visualized it with Status Notifications
![Bild](https://user-images.githubusercontent.com/36986615/71729381-d768ac00-2e3f-11ea-8f68-1a1ce6ffcd75.gif):

Many thanks for your support!

**Comment by fabianpnke** [comment]
Fixed it. Here is the Solution:
https://laracasts.com/discuss/channels/laravel/session-id-is-different-in-constructor-and-action

**Comment by reinink** [comment]
👍
