### ISSUE TITLE
API Resource - Relationships

### ISSUE THREAD

**Issue by transasic** [inertiajs/inertia-laravel#98]
So, I've added support for "Responsable" props: 2b966ac27964534ee3bbe585b0ea0fff8babb53a

This approach is more like #70. I still don't understand how this was superior to that solution. Sorry if I've missed something.

I've tested this with both single resource responses and collection resource responses, and it works great.

_Originally posted by @reinink in https://github.com/inertiajs/inertia-laravel/pull/82#issuecomment-570242405_

**Comment by reinink** [comment]
> This approach is more like #70. I still don't understand how this was superior to that solution. Sorry if I've missed something.

Have you seen my comment here? https://github.com/inertiajs/inertia-laravel/pull/70#issuecomment-570243307

Also, I'm not really sure what you're asking in this issue. Can you please clarify?

**Comment by transasic** [comment]
Sorry had to go. I didn't pay attention to explicit  $wrap = null;
I used json resource before your commit and when I upgraded to 0.2 all the properties had to be referenced as user.data.*

**Comment by reinink** [comment]
Great! 🤟
